/* Generated by tools/bs2c.py from data/scenes/debug/template_scene.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "src/code_080068f8.h"
#include "src/scenes/debug_template_scene.h"
#include "src/scenes/riq_main_scene.h"
#include <stddef.h>   // offsetof, for the scene-variable offsets below
#include "src/scenes/debug_template_scene.h"

extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x09[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char xC[];   /* undeclared in any header */
extern const struct Beatscript script_scene_template[];
extern const struct SubScene sub_scene_template;
extern struct Scene scene_template;

const struct Beatscript script_scene_template[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(func_08007324), (uintptr_t)(TRUE) },
    { 0x09, INT8, (const void *)(offsetof(struct TemplateSceneData, inputsEnabled)), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x09, INT8, (const void *)(offsetof(struct TemplateSceneData, inputsEnabled)), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_template = {
    /* start  */ (void (*)())template_scene_start, 0,
    /* paused */ (void (*)())template_scene_paused, 0,
    /* update */ (void (*)())template_scene_update, 0,
    /* stop   */ (void (*)())template_scene_stop, 0,
    /* script */ script_scene_template,
};

struct Scene scene_template = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_template),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(0),
    /* end    */ (void (*)())NULL, (void *)(0),
    /* memory */ 0xC,
};
