/* Generated by tools/bs2c.py from games/power_calligraphy/power_calligraphy.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/prologues/power_calligraphy.h"
#include "include/sequence_data.h"
#include "src/code_080068f8.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805d24c[];   /* undeclared in any header */
extern char D_0805d25c[];   /* undeclared in any header */
extern char D_0805d260[];   /* undeclared in any header */
extern char D_0805d274[];   /* undeclared in any header */
extern char D_0805d288[];   /* undeclared in any header */
extern char D_0805d2a8[];   /* undeclared in any header */
extern char D_0805d2c0[];   /* undeclared in any header */
extern char D_0805d2dc[];   /* undeclared in any header */
extern char D_0805d2f0[];   /* undeclared in any header */
extern char D_0805d300[];   /* undeclared in any header */
extern char D_0805d318[];   /* undeclared in any header */
extern char D_0805d33c[];   /* undeclared in any header */
extern char D_0805d350[];   /* undeclared in any header */
extern char D_0805d374[];   /* undeclared in any header */
extern char D_0805d37c[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char power_calligraphy_engine[];   /* undeclared in any header */
extern char power_calligraphy_prologue_engine[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_chikara[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_chikara_init[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_comma[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_comma_init[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_face[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_face_init[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_kokoro[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_kokoro_init[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_onore[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_onore_init[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_re[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_re_init[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_sun[];   /* undeclared in any header */
extern char script_power_calligraphy_sub_sun_init[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x0F[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x100[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x29[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x4C[];   /* undeclared in any header */
extern char x50[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern char x80[];   /* undeclared in any header */
extern char xFF[];   /* undeclared in any header */
extern const struct Beatscript script_power_calligraphy_entry[];
extern const struct SubScene sub_scene_power_calligraphy;
extern struct Scene scene_power_calligraphy;
extern const struct Beatscript script_power_calligraphy_skipped_practice_entry[];
extern const struct SubScene sub_scene_power_calligraphy_skipped_practice;
extern struct Scene scene_power_calligraphy_skipped_practice;
extern const struct Beatscript script_power_calligraphy_prologue[];
extern const struct MarkingCriteria power_calligraphy_marking_criteria_0;
extern const struct MarkingCriteria power_calligraphy_marking_criteria_1;
extern const struct MarkingCriteria power_calligraphy_marking_criteria_2;
extern const struct MarkingCriteria power_calligraphy_marking_criteria_3;
extern const struct MarkingCriteria *power_calligraphy_marking_criteria[];
extern const struct Beatscript script_power_calligraphy_main[];
extern const struct Beatscript script_power_calligraphy_practice[];
extern const struct Beatscript script_power_calligraphy_skipped_practice[];

const struct Beatscript script_power_calligraphy_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_prologue), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_power_calligraphy = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_power_calligraphy_entry,
};

struct Scene scene_power_calligraphy = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_power_calligraphy),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_power_calligraphy_skipped_practice_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_skipped_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_power_calligraphy_skipped_practice = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_power_calligraphy_skipped_practice_entry,
};

struct Scene scene_power_calligraphy_skipped_practice = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_power_calligraphy_skipped_practice),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_power_calligraphy_prologue[] = {
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(8) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(power_calligraphy_prologue_engine) },
    { 0x03, 0, (const void *)(stop_all_soundplayers), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x29, 0, NULL, (uintptr_t)(&s_jingle_iai_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(func_080461f4), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(func_08006d80), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct MarkingCriteria power_calligraphy_marking_criteria_0 = {
    /* positive */ D_0805d25c,
    /* negative */ D_0805d24c,
    /* flags    */ (CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x00,
    /* minHitsBeforeFail   */ 0x80,
    /* maxMissesBeforeFail */ 0x4C,
};

const struct MarkingCriteria power_calligraphy_marking_criteria_1 = {
    /* positive */ D_0805d274,
    /* negative */ D_0805d260,
    /* flags    */ (CHECK_AVERAGE_HITS) & 0xFF, ((CHECK_AVERAGE_HITS) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x100,
    /* minHitsBeforeFail   */ 0x4C,
    /* maxMissesBeforeFail */ 1,
};

const struct MarkingCriteria power_calligraphy_marking_criteria_2 = {
    /* positive */ D_0805d2a8,
    /* negative */ D_0805d288,
    /* flags    */ (CHECK_AVERAGE_HITS) & 0xFF, ((CHECK_AVERAGE_HITS) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x100,
    /* minHitsBeforeFail   */ 0x80,
    /* maxMissesBeforeFail */ 2,
};

const struct MarkingCriteria power_calligraphy_marking_criteria_3 = {
    /* positive */ D_0805d2c0,
    /* negative */ D_0805d25c,
    /* flags    */ (CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x100,
    /* minHitsBeforeFail   */ 0x00,
    /* maxMissesBeforeFail */ 0x100,
};

const struct MarkingCriteria *power_calligraphy_marking_criteria[] = {
    (const struct MarkingCriteria *)(&power_calligraphy_marking_criteria_0),
    (const struct MarkingCriteria *)(&power_calligraphy_marking_criteria_1),
    (const struct MarkingCriteria *)(&power_calligraphy_marking_criteria_2),
    (const struct MarkingCriteria *)(&power_calligraphy_marking_criteria_3),
    (const struct MarkingCriteria *)(NULL),
};

const struct Beatscript script_power_calligraphy_main[] = {
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(127) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_shuji_bgm1_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d2dc) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_start_perfect_campaign), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(results_set_header), (uintptr_t)(D_0805d2f0) },
    { 0x03, 0, (const void *)(results_import_marking_criteria), (uintptr_t)(power_calligraphy_marking_criteria) },
    { 0x03, 0, (const void *)(gameplay_set_mercy_count), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_sun_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_sun), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_kokoro_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_kokoro), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(LITTLE_PEOPLE_DANCE) },
    { 0x04, SET_PEOPLE_STATE, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(161) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_shuji_bgm2_seqData) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_chikara), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_sun_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_sun), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_onore), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_kokoro_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_kokoro), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(LITTLE_PEOPLE_END_BOW) },
    { 0x04, SET_PEOPLE_STATE, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_face_init), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(98) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_shuji_bgm3_seqData) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(LITTLE_PEOPLE_BOW) },
    { 0x04, SET_PEOPLE_STATE, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(3) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_face), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x50, 0, NULL, (uintptr_t)(84) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(KANA_END_KANJI) },
    { 0x04, SET_KANA, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, SET_KANA_ANIM_CEL, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)((60 & 0xFF)) },
    { 0x04, SET_BRUSH, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(scene_stop_music), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(gameplay_check_for_perfect), (uintptr_t)(FALSE) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_shuji_bgm_end_seqData) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(LITTLE_PEOPLE_END_BOW) },
    { 0x04, SET_PEOPLE_STATE, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x00, 0, NULL, (uintptr_t)((9 * 24)) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_power_calligraphy_practice[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(140) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_mario2_seqData) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d300) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_display_skip_icon), (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(&scene_power_calligraphy_skipped_practice) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d318) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(beatscript_disable_loops), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re_init), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_re), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d33c) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d350) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(beatscript_disable_loops), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma_init), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_power_calligraphy_sub_comma), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, REMOVE_PAPER, (const void *)(gameplay_run_engine_event), (uintptr_t)(power_calligraphy_engine) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d374) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(NULL) },
    { 0x50, 0, NULL, (uintptr_t)(144) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805d37c) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_power_calligraphy_main), (uintptr_t)(0) },
};

const struct Beatscript script_power_calligraphy_skipped_practice[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_power_calligraphy_main), (uintptr_t)(0) },
};
