/* Generated by tools/bs2c.py from data/scenes/medal_corner/scene.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "src/code_080068f8.h"
#include "src/scenes/medal_corner.h"
#include "src/scenes/riq_main_scene.h"

extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x09[];   /* undeclared in any header */
extern char x1C[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern const struct Beatscript script_medal_corner_menu[];
extern const struct SubScene sub_scene_toys_menu;
extern struct Scene scene_toys_menu;
extern const struct SubScene sub_scene_endless_menu;
extern struct Scene scene_endless_menu;
extern const struct SubScene sub_scene_lessons_menu;
extern struct Scene scene_lessons_menu;

const struct Beatscript script_medal_corner_menu[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(140) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08007324), (uintptr_t)(TRUE) },
    { 0x4A, 0, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(medal_corner_start_music), (uintptr_t)(0) },
    { 0x09, INT8, NULL, (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x09, INT8, NULL, (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_toys_menu = {
    /* start  */ (void (*)())medal_corner_scene_start, 0,
    /* paused */ (void (*)())medal_corner_scene_paused, 0,
    /* update */ (void (*)())medal_corner_scene_update, 0,
    /* stop   */ (void (*)())medal_corner_scene_stop, 0,
    /* script */ script_medal_corner_menu,
};

struct Scene scene_toys_menu = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_toys_menu),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(0),
    /* end    */ (void (*)())NULL, (void *)(0),
    /* memory */ 0x1C,
};

const struct SubScene sub_scene_endless_menu = {
    /* start  */ (void (*)())medal_corner_scene_start, (s32)(1),
    /* paused */ (void (*)())medal_corner_scene_paused, 0,
    /* update */ (void (*)())medal_corner_scene_update, 0,
    /* stop   */ (void (*)())medal_corner_scene_stop, 0,
    /* script */ script_medal_corner_menu,
};

struct Scene scene_endless_menu = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_endless_menu),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(0),
    /* end    */ (void (*)())NULL, (void *)(0),
    /* memory */ 0x1C,
};

const struct SubScene sub_scene_lessons_menu = {
    /* start  */ (void (*)())medal_corner_scene_start, (s32)(2),
    /* paused */ (void (*)())medal_corner_scene_paused, 0,
    /* update */ (void (*)())medal_corner_scene_update, 0,
    /* stop   */ (void (*)())medal_corner_scene_stop, 0,
    /* script */ script_medal_corner_menu,
};

struct Scene scene_lessons_menu = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_lessons_menu),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(0),
    /* end    */ (void (*)())NULL, (void *)(0),
    /* memory */ 0x1C,
};
