/* Generated by tools/bs2c.py from data/scenes/warning/scene.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "src/scenes/riq_main_scene.h"
#include "src/scenes/warning.h"

extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x09[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x8[];   /* undeclared in any header */
extern const struct Beatscript script_scene_warning[];
extern const struct SubScene sub_scene_warning;
extern struct Scene scene_warning;

const struct Beatscript script_scene_warning[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(warning_scene_render_anim), (uintptr_t)(0) },
    { 0x09, INT8, NULL, (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_warning = {
    /* start  */ (void (*)())warning_scene_start, 0,
    /* paused */ (void (*)())NULL, 0,
    /* update */ (void (*)())warning_scene_update, 0,
    /* stop   */ (void (*)())warning_scene_stop, 0,
    /* script */ script_scene_warning,
};

struct Scene scene_warning = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_warning),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(0),
    /* end    */ (void (*)())NULL, (void *)(0),
    /* memory */ 0x8,
};
