#ifdef PLATFORM_PC

/* Weak stubs.
 *
 * ELF and Mach-O treat a weak *definition* as a real definition that any
 * strong definition overrides.  PE/COFF does not: mingw turns
 * __attribute__((weak)) into a weak external alias that stays unresolved
 * unless something else defines the symbol, so a stub with no real
 * counterpart becomes an undefined reference at link time.
 *
 * On Windows the stubs are therefore plain definitions, and the same
 * override is achieved with link order instead: Makefile.pc puts this object
 * LAST and passes --allow-multiple-definition, so ld keeps the first
 * definition it saw — the real one — for each of the 735 symbols that have
 * both.  Symbols with only a stub still resolve, which is the whole point.
 */
#ifdef _WIN32
#  define RTPC_WEAK
#else
#  define RTPC_WEAK __attribute__((weak))
#endif
#include <stdint.h>
typedef uint8_t  u8; typedef uint16_t u16; typedef uint32_t u32;
typedef int8_t   s8; typedef int16_t  s16; typedef int32_t  s32;

u32 __umodsi3(u32 a, u32 b) { return b ? a % b : 0; }
// fast_udivsi3 is a function POINTER (u32 (*fast_udivsi3)(u32, u32))
// The GBA copies ARM code to IWRAM and sets this pointer. On PC, point to a real C function.
static u32 pc_fast_udivsi3_impl(u32 a, u32 b) { return b ? a / b : 0; }
u32 (*fast_udivsi3)(u32 a, u32 b) = pc_fast_udivsi3_impl;
const u8 fast_udivsi3_rom[4] = {0};
const u8 fast_udivsi3_rom_end[1] = {0};
void func_08000a00(void) {}
const u8 func_08000a00_end[1] = {0};
// IWRAM
u8 D_03004428;
volatile u16 D_03004438;
volatile u16 D_0300443a;
void *D_0300443c;   // struct struct_0300443c * — pointer-sized!
u8 D_03004440;
u8 D_03004498;
s32 D_030046a0;
u16 D_030046b0;
u16 D_030046b4;
u16 D_030046b8;
// Palette D_030046c0[32]: 32 palettes x 16 colours x u16 = 0x400 bytes.
// func_08006f84 dma3_set()s 0x400 bytes here every frame during fades —
// a smaller definition corrupts adjacent globals (was: u32 = 4 bytes).
u16 D_030046c0[32][16];
u16 D_03004ac0;
s16 D_03004aec;
u16 D_03004af4;
u16 D_03004afc;
u16 D_03004b00;
s16 D_03005370;
u16 D_03005378;
u16 D_0300537c;
// RLE decompression save state: graphics_table.c copies 8 u32 words in/out.
u32 D_03005390[8];
u32 D_030053b0;
u16 D_030053b8;
// D_030053c0 = BeatscriptScene (defined in globals.c)
// D_03005588 = u32 * current scene variable (defined in globals.c)
// D_0300558c = s16 * current sprite pool (defined in globals.c)
u32 D_03005590;
u32 D_030055d4;
// ROM stubs
// Function stubs
RTPC_WEAK int arrival_bg_map(void) { return 0; }
RTPC_WEAK int arrival_bg_tiles(void) { return 0; }
RTPC_WEAK int bmp_font_obj_print_text(void) { return 0; }
RTPC_WEAK int bon_dance_bg_map(void) { return 0; }
RTPC_WEAK int bon_dance_bg_map_lanterns(void) { return 0; }
RTPC_WEAK int bon_dance_bg_tiles(void) { return 0; }
RTPC_WEAK int bon_dance_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int bon_dance_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int bon_dance_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int bon_dance_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int bon_dance_obj(void) { return 0; }
RTPC_WEAK int bon_dance_prologue_bg_map(void) { return 0; }
RTPC_WEAK int bon_dance_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int bon_dance_prologue_obj(void) { return 0; }
RTPC_WEAK int bon_odori_bg_map(void) { return 0; }
RTPC_WEAK int bon_odori_bg_map_blank(void) { return 0; }
RTPC_WEAK int bon_odori_bg_map_lanterns(void) { return 0; }
RTPC_WEAK int bon_odori_bg_tiles(void) { return 0; }
RTPC_WEAK int bon_odori_bg_tiles_blank(void) { return 0; }
RTPC_WEAK int bon_odori_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int bon_odori_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int bon_odori_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int bon_odori_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int bon_odori_obj(void) { return 0; }
RTPC_WEAK int bon_odori_prologue_bg_map(void) { return 0; }
RTPC_WEAK int bon_odori_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int bon_odori_prologue_obj(void) { return 0; }
RTPC_WEAK int bouncy_road_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int bouncy_road_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int bouncy_road_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int bouncy_road_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int bouncy_road_obj(void) { return 0; }
RTPC_WEAK int bouncy_road_prologue_bg_map(void) { return 0; }
RTPC_WEAK int bouncy_road_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int bouncy_road_prologue_obj(void) { return 0; }
RTPC_WEAK int bouncy_road_remix_5_bg_map_1(void) { return 0; }
RTPC_WEAK int bouncy_road_remix_5_bg_map_2(void) { return 0; }
RTPC_WEAK int bouncy_road_remix_5_bg_map_3(void) { return 0; }
RTPC_WEAK int bouncy_road_remix_5_bg_tiles(void) { return 0; }
RTPC_WEAK int bunny_hop_bg_map(void) { return 0; }
RTPC_WEAK int bunny_hop_bg_map_ground(void) { return 0; }
RTPC_WEAK int bunny_hop_bg_map_water(void) { return 0; }
RTPC_WEAK int bunny_hop_bg_tiles(void) { return 0; }
RTPC_WEAK int bunny_hop_common_beat_animation(void) { return 0; }
RTPC_WEAK int bunny_hop_common_display_text(void) { return 0; }
RTPC_WEAK int bunny_hop_common_init_tutorial(void) { return 0; }
RTPC_WEAK int bunny_hop_cue_barely(void) { return 0; }
RTPC_WEAK int bunny_hop_cue_despawn(void) { return 0; }
RTPC_WEAK int bunny_hop_cue_hit(void) { return 0; }
RTPC_WEAK int bunny_hop_cue_miss(void) { return 0; }
RTPC_WEAK int bunny_hop_cue_spawn(void) { return 0; }
RTPC_WEAK int bunny_hop_cue_update(void) { return 0; }
RTPC_WEAK int bunny_hop_engine_event_stub(void) { return 0; }
RTPC_WEAK int bunny_hop_engine_start(void) { return 0; }
RTPC_WEAK int bunny_hop_engine_stop(void) { return 0; }
RTPC_WEAK int bunny_hop_engine_update(void) { return 0; }
RTPC_WEAK int bunny_hop_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int bunny_hop_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int bunny_hop_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int bunny_hop_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int bunny_hop_input_event(void) { return 0; }
RTPC_WEAK int bunny_hop_obj(void) { return 0; }
RTPC_WEAK int bunny_hop_prologue_bg_map(void) { return 0; }
RTPC_WEAK int bunny_hop_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int bunny_hop_prologue_obj(void) { return 0; }
RTPC_WEAK int cafe_bg_map(void) { return 0; }
RTPC_WEAK int cafe_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int cafe_bg_tiles(void) { return 0; }
RTPC_WEAK int cafe_obj(void) { return 0; }
RTPC_WEAK int cat_machine_bg_map(void) { return 0; }
RTPC_WEAK int cat_machine_bg_tiles(void) { return 0; }
RTPC_WEAK int cat_machine_obj(void) { return 0; }
RTPC_WEAK int clappy_trio_bg_map(void) { return 0; }
RTPC_WEAK int clappy_trio_bg_tiles(void) { return 0; }
RTPC_WEAK int clappy_trio_common_beat_animation(void) { return 0; }
RTPC_WEAK int clappy_trio_cue_hit(void) { return 0; }
RTPC_WEAK int clappy_trio_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int clappy_trio_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int clappy_trio_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int clappy_trio_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int clappy_trio_obj(void) { return 0; }
RTPC_WEAK int clappy_trio_prologue_bg_map(void) { return 0; }
RTPC_WEAK int clappy_trio_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int clappy_trio_prologue_obj(void) { return 0; }
RTPC_WEAK int cosmic_dance_bg_map_1(void) { return 0; }
RTPC_WEAK int cosmic_dance_bg_map_2(void) { return 0; }
RTPC_WEAK int cosmic_dance_bg_tiles(void) { return 0; }
RTPC_WEAK int cosmic_dance_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int cosmic_dance_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int cosmic_dance_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int cosmic_dance_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int cosmic_dance_obj(void) { return 0; }
RTPC_WEAK int cosmic_dance_prologue_bg_map(void) { return 0; }
RTPC_WEAK int cosmic_dance_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int cosmic_dance_prologue_obj(void) { return 0; }
RTPC_WEAK int data_room_bg_map(void) { return 0; }
RTPC_WEAK int data_room_bg_tiles(void) { return 0; }
RTPC_WEAK int data_room_obj(void) { return 0; }
RTPC_WEAK int drum_boys_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_boys_live_bg_map(void) { return 0; }
RTPC_WEAK int drum_boys_live_obj(void) { return 0; }
RTPC_WEAK int drum_girls_live_bg_map(void) { return 0; }
RTPC_WEAK int drum_girls_live_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_girls_live_obj(void) { return 0; }
RTPC_WEAK int drum_intro_common_beat_animation(void) { return 0; }
RTPC_WEAK int drum_intro_common_display_text(void) { return 0; }
RTPC_WEAK int drum_intro_cue_barely(void) { return 0; }
RTPC_WEAK int drum_intro_cue_barely_auto(void) { return 0; }
RTPC_WEAK int drum_intro_cue_despawn(void) { return 0; }
RTPC_WEAK int drum_intro_cue_despawn_auto(void) { return 0; }
RTPC_WEAK int drum_intro_cue_hit(void) { return 0; }
RTPC_WEAK int drum_intro_cue_hit_auto(void) { return 0; }
RTPC_WEAK int drum_intro_cue_miss(void) { return 0; }
RTPC_WEAK int drum_intro_cue_miss_auto(void) { return 0; }
RTPC_WEAK int drum_intro_cue_spawn(void) { return 0; }
RTPC_WEAK int drum_intro_cue_spawn_auto(void) { return 0; }
RTPC_WEAK int drum_intro_cue_update(void) { return 0; }
RTPC_WEAK int drum_intro_cue_update_auto(void) { return 0; }
RTPC_WEAK int drum_intro_engine_event_stub(void) { return 0; }
RTPC_WEAK int drum_intro_engine_start(void) { return 0; }
RTPC_WEAK int drum_intro_engine_stop(void) { return 0; }
RTPC_WEAK int drum_intro_engine_update(void) { return 0; }
RTPC_WEAK int drum_intro_input_event(void) { return 0; }
RTPC_WEAK int drum_intro_play_bg_map(void) { return 0; }
RTPC_WEAK int drum_intro_play_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_intro_play_obj(void) { return 0; }
RTPC_WEAK int drum_intro_talk_bg_map(void) { return 0; }
RTPC_WEAK int drum_intro_talk_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_intro_talk_obj(void) { return 0; }
RTPC_WEAK int drum_lessons_bg_map(void) { return 0; }
RTPC_WEAK int drum_lessons_bg_map_level_up(void) { return 0; }
RTPC_WEAK int drum_lessons_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_lessons_menu_bg_map(void) { return 0; }
RTPC_WEAK int drum_lessons_menu_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_lessons_menu_obj(void) { return 0; }
RTPC_WEAK int drum_lessons_obj(void) { return 0; }
RTPC_WEAK int drum_live_bg_map(void) { return 0; }
RTPC_WEAK int drum_live_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_10(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_11(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_3(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_4(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_5(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_6(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_7(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_8(void) { return 0; }
RTPC_WEAK int drum_live_crowd_bg_map_9(void) { return 0; }
RTPC_WEAK int drum_live_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int drum_live_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int drum_live_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int drum_live_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_live_menu_common_beat_animation(void) { return 0; }
RTPC_WEAK int drum_live_menu_common_display_text(void) { return 0; }
RTPC_WEAK int drum_live_menu_common_init_tutorial(void) { return 0; }
RTPC_WEAK int drum_live_menu_cue_barely(void) { return 0; }
RTPC_WEAK int drum_live_menu_cue_despawn(void) { return 0; }
RTPC_WEAK int drum_live_menu_cue_hit(void) { return 0; }
RTPC_WEAK int drum_live_menu_cue_miss(void) { return 0; }
RTPC_WEAK int drum_live_menu_cue_spawn(void) { return 0; }
RTPC_WEAK int drum_live_menu_cue_update(void) { return 0; }
RTPC_WEAK int drum_live_menu_engine_event_stub(void) { return 0; }
RTPC_WEAK int drum_live_menu_engine_start(void) { return 0; }
RTPC_WEAK int drum_live_menu_engine_stop(void) { return 0; }
RTPC_WEAK int drum_live_menu_engine_update(void) { return 0; }
RTPC_WEAK int drum_live_menu_input_event(void) { return 0; }
RTPC_WEAK int drum_live_menu_obj(void) { return 0; }
RTPC_WEAK int drum_samurai_live_bg_map(void) { return 0; }
RTPC_WEAK int drum_samurai_live_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_samurai_live_obj(void) { return 0; }
RTPC_WEAK int drum_studio_beach_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_beach_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_beach_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_bg_map(void) { return 0; }
RTPC_WEAK int drum_studio_bg_map_lessons(void) { return 0; }
RTPC_WEAK int drum_studio_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_checkerboard_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_checkerboard_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_checkerboard_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_circles_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_circles_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_circles_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_city_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_city_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_city_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_clouds_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_clouds_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_clouds_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_engine_stop(void) { return 0; }
RTPC_WEAK int drum_studio_fish_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_fish_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_fish_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_flowers_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_flowers_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_flowers_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_fruit_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_fruit_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_fruit_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_hearts_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_hearts_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_hearts_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_japan_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_japan_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_japan_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_lines_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_lines_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_lines_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_obj(void) { return 0; }
RTPC_WEAK int drum_studio_sparkles_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_sparkles_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_sparkles_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_squares_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_squares_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_squares_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_stars_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_stars_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_stars_bg_tiles(void) { return 0; }
RTPC_WEAK int drum_studio_stationery_bg_map_1(void) { return 0; }
RTPC_WEAK int drum_studio_stationery_bg_map_2(void) { return 0; }
RTPC_WEAK int drum_studio_stationery_bg_tiles(void) { return 0; }
RTPC_WEAK int endless_games_menu_bg_map(void) { return 0; }
RTPC_WEAK int endless_games_menu_bg_tiles(void) { return 0; }
RTPC_WEAK int endless_games_menu_obj(void) { return 0; }
RTPC_WEAK int fast_blend_col_to_pal(void) { return 0; }
RTPC_WEAK int fast_blend_pal_to_pal(void) { return 0; }
RTPC_WEAK int fireworks_bg_map(void) { return 0; }
RTPC_WEAK int fireworks_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int fireworks_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int fireworks_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int fireworks_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int fireworks_obj(void) { return 0; }
RTPC_WEAK int fireworks_prologue_bg_map(void) { return 0; }
RTPC_WEAK int fireworks_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int fireworks_prologue_obj(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_map_1(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_map_2(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_map_3(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_map_4(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_tiles_1(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_tiles_2(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_tiles_3(void) { return 0; }
RTPC_WEAK int fireworks_remix_5_bg_tiles_4(void) { return 0; }
// Affine-parameter manager (func_080020ec .. func_08002584) is fully
// implemented in platform/affine_pc.c — no stubs needed.
RTPC_WEAK int func_08002e78(void) { return 0; }
RTPC_WEAK int func_08004070(void) { return 0; }
RTPC_WEAK int func_0800716c(void) { return 0; }
RTPC_WEAK int func_08008608(void) { return 0; }
RTPC_WEAK int func_0800861c(void) { return 0; }
RTPC_WEAK int func_08008628(void) { return 0; }
RTPC_WEAK int func_0800869c(void) { return 0; }
RTPC_WEAK int func_08008910(void) { return 0; }
// func_0800cb28 implemented in asm_stubs.c with proper BeatscriptThread handling
RTPC_WEAK int func_0800eebc(void) { return 0; }
RTPC_WEAK int func_080226d4(void) { return 0; }
RTPC_WEAK int func_080229bc(void) { return 0; }
RTPC_WEAK int func_08022ba0(void) { return 0; }
RTPC_WEAK int func_08022f00(void) { return 0; }
RTPC_WEAK int func_08022f1c(void) { return 0; }
RTPC_WEAK int func_08023150(void) { return 0; }
RTPC_WEAK int func_08023164(void) { return 0; }
RTPC_WEAK int func_080239a0(void) { return 0; }
RTPC_WEAK int func_080239bc(void) { return 0; }
RTPC_WEAK int func_08023bb8(void) { return 0; }
RTPC_WEAK int func_08023bcc(void) { return 0; }
RTPC_WEAK int func_08023bf4(void) { return 0; }
RTPC_WEAK int func_08023c0c(void) { return 0; }
RTPC_WEAK int func_08023c44(void) { return 0; }
RTPC_WEAK int func_08023c58(void) { return 0; }
RTPC_WEAK int func_08023da4(void) { return 0; }
RTPC_WEAK int func_08023df8(void) { return 0; }
RTPC_WEAK int func_08023e50(void) { return 0; }
RTPC_WEAK int func_08023edc(void) { return 0; }
RTPC_WEAK int func_08023f68(void) { return 0; }
RTPC_WEAK int func_08023f6c(void) { return 0; }
RTPC_WEAK int func_08023ffc(void) { return 0; }
RTPC_WEAK int func_080240a4(void) { return 0; }
RTPC_WEAK int func_08024134(void) { return 0; }
RTPC_WEAK int func_080241c0(void) { return 0; }
RTPC_WEAK int func_0802497c(void) { return 0; }
RTPC_WEAK int func_080249c0(void) { return 0; }
RTPC_WEAK int func_08024a4c(void) { return 0; }
RTPC_WEAK int func_08024ae4(void) { return 0; }
RTPC_WEAK int func_08024ba0(void) { return 0; }
RTPC_WEAK int func_08024be8(void) { return 0; }
RTPC_WEAK int func_08024ef4(void) { return 0; }
RTPC_WEAK int func_08024f64(void) { return 0; }
RTPC_WEAK int func_08024fb4(void) { return 0; }
RTPC_WEAK int func_08024fbc(void) { return 0; }
RTPC_WEAK int func_08024fc4(void) { return 0; }
RTPC_WEAK int func_08024ff4(void) { return 0; }
RTPC_WEAK int func_08025020(void) { return 0; }
RTPC_WEAK int func_08025038(void) { return 0; }
RTPC_WEAK int func_080251d0(void) { return 0; }
RTPC_WEAK int func_080251d8(void) { return 0; }
RTPC_WEAK int func_080251e8(void) { return 0; }
RTPC_WEAK int func_080251ec(void) { return 0; }
RTPC_WEAK int func_080251f0(void) { return 0; }
RTPC_WEAK int func_080251fc(void) { return 0; }
RTPC_WEAK int func_08025204(void) { return 0; }
RTPC_WEAK int func_0802520c(void) { return 0; }
RTPC_WEAK int func_08025214(void) { return 0; }
RTPC_WEAK int func_08025218(void) { return 0; }
RTPC_WEAK int func_0802521c(void) { return 0; }
RTPC_WEAK int func_08025220(void) { return 0; }
RTPC_WEAK int func_08027304(void) { return 0; }
RTPC_WEAK int func_08027350(void) { return 0; }
RTPC_WEAK int func_0802739c(void) { return 0; }
RTPC_WEAK int func_080273e4(void) { return 0; }
RTPC_WEAK int func_0802742c(void) { return 0; }
RTPC_WEAK int func_08027474(void) { return 0; }
RTPC_WEAK int func_080274d0(void) { return 0; }
RTPC_WEAK int func_08027518(void) { return 0; }
RTPC_WEAK int func_08027560(void) { return 0; }
RTPC_WEAK int func_080275a8(void) { return 0; }
RTPC_WEAK int func_080275d0(void) { return 0; }
RTPC_WEAK int func_080275f8(void) { return 0; }
RTPC_WEAK int func_08027728(void) { return 0; }
RTPC_WEAK int func_08027744(void) { return 0; }
RTPC_WEAK int func_08027760(void) { return 0; }
RTPC_WEAK int func_0802777c(void) { return 0; }
RTPC_WEAK int func_080277a0(void) { return 0; }
RTPC_WEAK int func_08027888(void) { return 0; }
RTPC_WEAK int func_080278d0(void) { return 0; }
RTPC_WEAK int func_080278e8(void) { return 0; }
RTPC_WEAK int func_08027bd8(void) { return 0; }
RTPC_WEAK int func_08027c54(void) { return 0; }
RTPC_WEAK int func_08027c90(void) { return 0; }
RTPC_WEAK int func_08027d08(void) { return 0; }
RTPC_WEAK int func_08027fc8(void) { return 0; }
RTPC_WEAK int func_0802818c(void) { return 0; }
RTPC_WEAK int func_080281c4(void) { return 0; }
RTPC_WEAK int func_080281e8(void) { return 0; }
RTPC_WEAK int func_080281fc(void) { return 0; }
RTPC_WEAK int func_080283ac(void) { return 0; }
RTPC_WEAK int func_080283f8(void) { return 0; }
RTPC_WEAK int func_08028444(void) { return 0; }
RTPC_WEAK int func_080284a4(void) { return 0; }
RTPC_WEAK int func_08028504(void) { return 0; }
RTPC_WEAK int func_08028564(void) { return 0; }
RTPC_WEAK int func_080285d4(void) { return 0; }
RTPC_WEAK int func_08028634(void) { return 0; }
RTPC_WEAK int func_08028694(void) { return 0; }
RTPC_WEAK int func_080286f4(void) { return 0; }
RTPC_WEAK int func_0802871c(void) { return 0; }
RTPC_WEAK int func_08028744(void) { return 0; }
RTPC_WEAK int func_08029178(void) { return 0; }
RTPC_WEAK int func_0802918c(void) { return 0; }
RTPC_WEAK int func_080291bc(void) { return 0; }
RTPC_WEAK int func_080292e0(void) { return 0; }
RTPC_WEAK int func_08029b8c(void) { return 0; }
RTPC_WEAK int func_08029cec(void) { return 0; }
RTPC_WEAK int func_0802be10(void) { return 0; }
RTPC_WEAK int func_0802c40c(void) { return 0; }
RTPC_WEAK int func_0802ce70(void) { return 0; }
RTPC_WEAK int func_0802cf8c(void) { return 0; }
RTPC_WEAK int func_0802d104(void) { return 0; }
RTPC_WEAK int func_0802d2bc(void) { return 0; }
RTPC_WEAK int func_0802d394(void) { return 0; }
RTPC_WEAK int func_0802d81c(void) { return 0; }
RTPC_WEAK int func_0802d918(void) { return 0; }
RTPC_WEAK int func_0802d96c(void) { return 0; }
RTPC_WEAK int func_0802da84(void) { return 0; }
RTPC_WEAK int func_080303a4(void) { return 0; }
RTPC_WEAK int func_08030f04(void) { return 0; }
RTPC_WEAK int func_08030f34(void) { return 0; }
RTPC_WEAK int func_0803113c(void) { return 0; }
RTPC_WEAK int func_0803118c(void) { return 0; }
RTPC_WEAK int func_08031770(void) { return 0; }
RTPC_WEAK int func_08031bc0(void) { return 0; }
RTPC_WEAK int func_08031c54(void) { return 0; }
RTPC_WEAK int func_08032430(void) { return 0; }
RTPC_WEAK int func_080324a4(void) { return 0; }
RTPC_WEAK int func_08033960(void) { return 0; }
RTPC_WEAK int func_08033b24(void) { return 0; }
RTPC_WEAK int func_08033b34(void) { return 0; }
RTPC_WEAK int func_08033b9c(void) { return 0; }
RTPC_WEAK int func_08033e00(void) { return 0; }
RTPC_WEAK int func_08033f28(void) { return 0; }
RTPC_WEAK int func_08033f80(void) { return 0; }
RTPC_WEAK int func_08034544(void) { return 0; }
RTPC_WEAK int func_080346e0(void) { return 0; }
RTPC_WEAK int func_080347c0(void) { return 0; }
RTPC_WEAK int func_0803481c(void) { return 0; }
RTPC_WEAK int func_08034850(void) { return 0; }
RTPC_WEAK int func_08034ae4(void) { return 0; }
RTPC_WEAK int func_08034d6c(void) { return 0; }
RTPC_WEAK int func_08034db0(void) { return 0; }
RTPC_WEAK int func_08034e84(void) { return 0; }
RTPC_WEAK int func_08034f18(void) { return 0; }
RTPC_WEAK int func_0803516c(void) { return 0; }
RTPC_WEAK int func_08035314(void) { return 0; }
RTPC_WEAK int func_08035780(void) { return 0; }
RTPC_WEAK int func_080357c4(void) { return 0; }
RTPC_WEAK int func_080358b0(void) { return 0; }
RTPC_WEAK int func_080358d8(void) { return 0; }
RTPC_WEAK int func_080358f8(void) { return 0; }
RTPC_WEAK int func_080364f4(void) { return 0; }
RTPC_WEAK int func_08036758(void) { return 0; }
RTPC_WEAK int func_08036848(void) { return 0; }
RTPC_WEAK int func_08036f94(void) { return 0; }
RTPC_WEAK int func_0803709c(void) { return 0; }
RTPC_WEAK int func_08037280(void) { return 0; }
RTPC_WEAK int func_080372c0(void) { return 0; }
RTPC_WEAK int func_080373ac(void) { return 0; }
RTPC_WEAK int func_080373dc(void) { return 0; }
RTPC_WEAK int func_08037a64(void) { return 0; }
RTPC_WEAK int func_08037be0(void) { return 0; }
RTPC_WEAK int func_08037bf4(void) { return 0; }
RTPC_WEAK int func_08037cb8(void) { return 0; }
RTPC_WEAK int func_08037cd0(void) { return 0; }
RTPC_WEAK int func_08037d00(void) { return 0; }
RTPC_WEAK int func_08037d0c(void) { return 0; }
RTPC_WEAK int func_08037d1c(void) { return 0; }
RTPC_WEAK int func_08037d2c(void) { return 0; }
RTPC_WEAK int func_08037d6c(void) { return 0; }
RTPC_WEAK int func_08037d90(void) { return 0; }
RTPC_WEAK int func_08037dc8(void) { return 0; }
RTPC_WEAK int func_08037e24(void) { return 0; }
RTPC_WEAK int func_08038248(void) { return 0; }
RTPC_WEAK int func_080382b0(void) { return 0; }
RTPC_WEAK int func_080382f4(void) { return 0; }
RTPC_WEAK int func_08038314(void) { return 0; }
RTPC_WEAK int func_0803833c(void) { return 0; }
RTPC_WEAK int func_080383f0(void) { return 0; }
RTPC_WEAK int func_0803899c(void) { return 0; }
RTPC_WEAK int func_0803934c(void) { return 0; }
RTPC_WEAK int func_080395dc(void) { return 0; }
RTPC_WEAK int func_0803a158(void) { return 0; }
RTPC_WEAK int func_0803a1d4(void) { return 0; }
RTPC_WEAK int func_0803a1e4(void) { return 0; }
RTPC_WEAK int func_0803a1f8(void) { return 0; }
RTPC_WEAK int func_0803a204(void) { return 0; }
RTPC_WEAK int func_0803a2a8(void) { return 0; }
RTPC_WEAK int func_0803a350(void) { return 0; }
RTPC_WEAK int func_0803a3b8(void) { return 0; }
RTPC_WEAK int func_0803a41c(void) { return 0; }
RTPC_WEAK int func_0803a434(void) { return 0; }
RTPC_WEAK int func_0803a47c(void) { return 0; }
RTPC_WEAK int func_0803a490(void) { return 0; }
RTPC_WEAK int func_0803a798(void) { return 0; }
RTPC_WEAK int func_0803aa58(void) { return 0; }
RTPC_WEAK int func_0803ac98(void) { return 0; }
RTPC_WEAK int func_0803ad50(void) { return 0; }
RTPC_WEAK int func_0803b034(void) { return 0; }
RTPC_WEAK int func_0803bc98(void) { return 0; }
RTPC_WEAK int func_0803be04(void) { return 0; }
RTPC_WEAK int func_0803be88(void) { return 0; }
RTPC_WEAK int func_0803bf74(void) { return 0; }
RTPC_WEAK int func_0803c034(void) { return 0; }
RTPC_WEAK int func_0803c08c(void) { return 0; }
RTPC_WEAK int func_0803c2b8(void) { return 0; }
RTPC_WEAK int func_0803c400(void) { return 0; }
RTPC_WEAK int func_0803c5cc(void) { return 0; }
RTPC_WEAK int func_0803c5f8(void) { return 0; }
RTPC_WEAK int func_0803c638(void) { return 0; }
RTPC_WEAK int func_0803c6fc(void) { return 0; }
RTPC_WEAK int func_0803c960(void) { return 0; }
RTPC_WEAK int func_0803c9f8(void) { return 0; }
RTPC_WEAK int func_0803ca8c(void) { return 0; }
RTPC_WEAK int func_0803cad0(void) { return 0; }
RTPC_WEAK int func_0803cb0c(void) { return 0; }
RTPC_WEAK int func_0803ccb4(void) { return 0; }
RTPC_WEAK int func_0803cce0(void) { return 0; }
RTPC_WEAK int func_0803d2c0(void) { return 0; }
RTPC_WEAK int func_0803d3fc(void) { return 0; }
RTPC_WEAK int func_0803d408(void) { return 0; }
RTPC_WEAK int func_0803d414(void) { return 0; }
RTPC_WEAK int func_0803d460(void) { return 0; }
RTPC_WEAK int func_0803d4bc(void) { return 0; }
RTPC_WEAK int func_0803d4e0(void) { return 0; }
RTPC_WEAK int func_0803d588(void) { return 0; }
RTPC_WEAK int func_0803e0bc(void) { return 0; }
RTPC_WEAK int func_0803e0f8(void) { return 0; }
RTPC_WEAK int func_0803e10c(void) { return 0; }
RTPC_WEAK int func_0803e160(void) { return 0; }
RTPC_WEAK int func_0803e1a4(void) { return 0; }
RTPC_WEAK int func_0803e208(void) { return 0; }
RTPC_WEAK int func_0803e258(void) { return 0; }
RTPC_WEAK int func_0803e2e0(void) { return 0; }
RTPC_WEAK int func_0803e2f4(void) { return 0; }
RTPC_WEAK int func_0803e310(void) { return 0; }
RTPC_WEAK int func_0803e324(void) { return 0; }
RTPC_WEAK int func_0803e338(void) { return 0; }
RTPC_WEAK int func_0803e354(void) { return 0; }
RTPC_WEAK int func_0803e448(void) { return 0; }
RTPC_WEAK int func_0803e884(void) { return 0; }
RTPC_WEAK int func_0803e9b0(void) { return 0; }
RTPC_WEAK int func_0803ea08(void) { return 0; }
RTPC_WEAK int func_0803f0b8(void) { return 0; }
RTPC_WEAK int func_0803f12c(void) { return 0; }
RTPC_WEAK int func_0803f1bc(void) { return 0; }
RTPC_WEAK int func_0803f390(void) { return 0; }
RTPC_WEAK int func_0803f3b0(void) { return 0; }
RTPC_WEAK int func_0803fb00(void) { return 0; }
RTPC_WEAK int func_08040064(void) { return 0; }
RTPC_WEAK int func_080400d0(void) { return 0; }
RTPC_WEAK int func_08040434(void) { return 0; }
RTPC_WEAK int func_08040dd8(void) { return 0; }
RTPC_WEAK int func_080415c0(void) { return 0; }
RTPC_WEAK int func_080417ac(void) { return 0; }
RTPC_WEAK int func_0804188c(void) { return 0; }
RTPC_WEAK int func_08041c98(void) { return 0; }
RTPC_WEAK int func_08041ddc(void) { return 0; }
RTPC_WEAK int func_08041f80(void) { return 0; }
RTPC_WEAK int func_08042020(void) { return 0; }
RTPC_WEAK int func_080420c0(void) { return 0; }
RTPC_WEAK int func_0804231c(void) { return 0; }
RTPC_WEAK int func_08042438(void) { return 0; }
RTPC_WEAK int func_08042504(void) { return 0; }
RTPC_WEAK int func_08042548(void) { return 0; }
RTPC_WEAK int func_080429e8(void) { return 0; }
RTPC_WEAK int func_0804e1c8(void) { return 0; }
RTPC_WEAK int game_select_bg_map_description(void) { return 0; }
RTPC_WEAK int game_select_bg_map_perfect_notice(void) { return 0; }
RTPC_WEAK int game_select_bg_tiles(void) { return 0; }
RTPC_WEAK int game_select_obj(void) { return 0; }
RTPC_WEAK int gameplay_obj(void) { return 0; }
RTPC_WEAK int init_texture_loader_task(void) { return 0; }
RTPC_WEAK int karate_man_bg_map(void) { return 0; }
RTPC_WEAK int karate_man_bg_map_serious(void) { return 0; }
RTPC_WEAK int karate_man_bg_tiles(void) { return 0; }
RTPC_WEAK int karate_man_bg_tiles_serious(void) { return 0; }
RTPC_WEAK int karate_man_bg_tiles_unused_face_1(void) { return 0; }
RTPC_WEAK int karate_man_bg_tiles_unused_face_2(void) { return 0; }
RTPC_WEAK int karate_man_bg_tiles_unused_face_3(void) { return 0; }
RTPC_WEAK int karate_man_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int karate_man_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int karate_man_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int karate_man_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int karate_man_obj(void) { return 0; }
RTPC_WEAK int karate_man_prologue_bg_map(void) { return 0; }
RTPC_WEAK int karate_man_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int karate_man_prologue_obj(void) { return 0; }
RTPC_WEAK int love_machine_bg_map(void) { return 0; }
RTPC_WEAK int love_machine_bg_tiles(void) { return 0; }
RTPC_WEAK int love_machine_obj(void) { return 0; }
RTPC_WEAK int main_menu_bg_map(void) { return 0; }
RTPC_WEAK int main_menu_bg_tiles(void) { return 0; }
RTPC_WEAK int main_menu_obj(void) { return 0; }
RTPC_WEAK int mannequin_common_beat_animation(void) { return 0; }
RTPC_WEAK int mannequin_common_display_text(void) { return 0; }
RTPC_WEAK int mannequin_common_init_tutorial(void) { return 0; }
RTPC_WEAK int mannequin_cue_barely(void) { return 0; }
RTPC_WEAK int mannequin_cue_despawn(void) { return 0; }
RTPC_WEAK int mannequin_cue_hit(void) { return 0; }
RTPC_WEAK int mannequin_cue_miss(void) { return 0; }
RTPC_WEAK int mannequin_cue_spawn(void) { return 0; }
RTPC_WEAK int mannequin_cue_update(void) { return 0; }
RTPC_WEAK int mannequin_engine_event_stub(void) { return 0; }
RTPC_WEAK int mannequin_engine_start(void) { return 0; }
RTPC_WEAK int mannequin_engine_stop(void) { return 0; }
RTPC_WEAK int mannequin_engine_update(void) { return 0; }
RTPC_WEAK int mannequin_factory_bg_map(void) { return 0; }
RTPC_WEAK int mannequin_factory_bg_map_practice(void) { return 0; }
RTPC_WEAK int mannequin_factory_bg_tiles(void) { return 0; }
RTPC_WEAK int mannequin_factory_obj(void) { return 0; }
RTPC_WEAK int mannequin_input_event(void) { return 0; }
RTPC_WEAK int marching_common_beat_animation(void) { return 0; }
RTPC_WEAK int marching_common_display_text(void) { return 0; }
RTPC_WEAK int marching_common_init_tutorial(void) { return 0; }
RTPC_WEAK int marching_cue_barely(void) { return 0; }
RTPC_WEAK int marching_cue_despawn(void) { return 0; }
RTPC_WEAK int marching_cue_hit(void) { return 0; }
RTPC_WEAK int marching_cue_miss(void) { return 0; }
RTPC_WEAK int marching_cue_spawn(void) { return 0; }
RTPC_WEAK int marching_cue_update(void) { return 0; }
RTPC_WEAK int marching_engine_event_stub(void) { return 0; }
RTPC_WEAK int marching_engine_start(void) { return 0; }
RTPC_WEAK int marching_engine_stop(void) { return 0; }
RTPC_WEAK int marching_engine_update(void) { return 0; }
RTPC_WEAK int marching_input_event(void) { return 0; }
RTPC_WEAK int marching_orders_2_bg_map(void) { return 0; }
RTPC_WEAK int marching_orders_2_bg_map_floor(void) { return 0; }
RTPC_WEAK int marching_orders_2_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_2_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int marching_orders_2_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int marching_orders_2_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int marching_orders_2_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_2_obj(void) { return 0; }
RTPC_WEAK int marching_orders_2_prologue_bg_map(void) { return 0; }
RTPC_WEAK int marching_orders_2_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_2_prologue_obj(void) { return 0; }
RTPC_WEAK int marching_orders_bg_map(void) { return 0; }
RTPC_WEAK int marching_orders_bg_map_floor(void) { return 0; }
RTPC_WEAK int marching_orders_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int marching_orders_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int marching_orders_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int marching_orders_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int marching_orders_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_obj(void) { return 0; }
RTPC_WEAK int marching_orders_prologue_bg_map(void) { return 0; }
RTPC_WEAK int marching_orders_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_prologue_obj(void) { return 0; }
RTPC_WEAK int marching_orders_remix_7_bg_map(void) { return 0; }
RTPC_WEAK int marching_orders_remix_7_bg_map_floor(void) { return 0; }
RTPC_WEAK int marching_orders_remix_7_bg_tiles(void) { return 0; }
RTPC_WEAK int marching_orders_remix_7_obj(void) { return 0; }
RTPC_WEAK int math_sqrt_rom(void) { return 0; }
RTPC_WEAK int mechanical_horse_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_bg_map_ground(void) { return 0; }
RTPC_WEAK int mechanical_horse_bg_map_speedometer(void) { return 0; }
RTPC_WEAK int mechanical_horse_bg_tiles(void) { return 0; }
RTPC_WEAK int mechanical_horse_blur_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_blur_bg_tiles(void) { return 0; }
RTPC_WEAK int mechanical_horse_city_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_city_bg_tiles(void) { return 0; }
RTPC_WEAK int mechanical_horse_cue_spawn(void) { return 0; }
RTPC_WEAK int mechanical_horse_cue_update(void) { return 0; }
RTPC_WEAK int mechanical_horse_obj(void) { return 0; }
RTPC_WEAK int mechanical_horse_photo_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_photo_bg_tiles(void) { return 0; }
RTPC_WEAK int mechanical_horse_road_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_road_bg_tiles(void) { return 0; }
RTPC_WEAK int mechanical_horse_space_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_space_bg_tiles(void) { return 0; }
RTPC_WEAK int mechanical_horse_trees_bg_map(void) { return 0; }
RTPC_WEAK int mechanical_horse_trees_bg_tiles(void) { return 0; }
RTPC_WEAK int medal_corner_obj(void) { return 0; }
RTPC_WEAK int mem_heap_alloc_block_rom(void) { return 0; }
RTPC_WEAK int metronome_common_beat_animation(void) { return 0; }
RTPC_WEAK int metronome_common_display_text(void) { return 0; }
RTPC_WEAK int metronome_common_init_tutorial(void) { return 0; }
RTPC_WEAK int metronome_cue_barely(void) { return 0; }
RTPC_WEAK int metronome_cue_despawn(void) { return 0; }
RTPC_WEAK int metronome_cue_hit(void) { return 0; }
RTPC_WEAK int metronome_cue_miss(void) { return 0; }
RTPC_WEAK int metronome_cue_spawn(void) { return 0; }
RTPC_WEAK int metronome_cue_update(void) { return 0; }
RTPC_WEAK int metronome_engine_start(void) { return 0; }
RTPC_WEAK int metronome_engine_stop(void) { return 0; }
RTPC_WEAK int metronome_engine_update(void) { return 0; }
RTPC_WEAK int metronome_input_event(void) { return 0; }
RTPC_WEAK int metronome_obj(void) { return 0; }
RTPC_WEAK int midi_directsound_init(void) { return 0; }
RTPC_WEAK int mr_upbeat_common_beat_animation(void) { return 0; }
RTPC_WEAK int mr_upbeat_common_display_text(void) { return 0; }
RTPC_WEAK int mr_upbeat_common_init_tutorial(void) { return 0; }
RTPC_WEAK int mr_upbeat_cue_barely(void) { return 0; }
RTPC_WEAK int mr_upbeat_cue_despawn(void) { return 0; }
RTPC_WEAK int mr_upbeat_cue_hit(void) { return 0; }
RTPC_WEAK int mr_upbeat_cue_miss(void) { return 0; }
RTPC_WEAK int mr_upbeat_cue_spawn(void) { return 0; }
RTPC_WEAK int mr_upbeat_cue_update(void) { return 0; }
RTPC_WEAK int mr_upbeat_engine_event_stub(void) { return 0; }
RTPC_WEAK int mr_upbeat_engine_start(void) { return 0; }
RTPC_WEAK int mr_upbeat_engine_stop(void) { return 0; }
RTPC_WEAK int mr_upbeat_engine_update(void) { return 0; }
RTPC_WEAK int mr_upbeat_input_event(void) { return 0; }
RTPC_WEAK int night_walk_bg_map(void) { return 0; }
RTPC_WEAK int night_walk_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int night_walk_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int night_walk_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int night_walk_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int night_walk_obj(void) { return 0; }
RTPC_WEAK int night_walk_prologue_bg_map(void) { return 0; }
RTPC_WEAK int night_walk_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int night_walk_prologue_obj(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_bg_map_l(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_bg_map_r(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_common_beat_animation(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_common_display_text(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_cue_barely(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_cue_despawn(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_cue_hit(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_cue_miss(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_cue_spawn(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_cue_update(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_engine_event_stub(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_engine_start(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_engine_stop(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_engine_update(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_input_event(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_intro_bg_map(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_intro_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_obj(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_prologue_bg_map(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_bodyguard_prologue_obj(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_bg_map_l(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_bg_map_r(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_obj(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_prologue_bg_map(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int ninja_reincarnate_prologue_obj(void) { return 0; }
RTPC_WEAK int options_bg_map(void) { return 0; }
RTPC_WEAK int options_bg_tiles(void) { return 0; }
RTPC_WEAK int options_obj(void) { return 0; }
RTPC_WEAK int perfect_certificate_bg_map(void) { return 0; }
RTPC_WEAK int perfect_certificate_bg_tiles(void) { return 0; }
RTPC_WEAK int placeholder_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int placeholder_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int placeholder_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int placeholder_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int play_drumtech_note(void) { return 0; }
RTPC_WEAK int polyrhythm_bg_map(void) { return 0; }
RTPC_WEAK int polyrhythm_despawn_piston(void) { return 0; }
RTPC_WEAK int polyrhythm_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int polyrhythm_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int polyrhythm_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int polyrhythm_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int polyrhythm_event_play_applause(void) { return 0; }
RTPC_WEAK int polyrhythm_obj(void) { return 0; }
RTPC_WEAK int polyrhythm_prologue_bg_map(void) { return 0; }
RTPC_WEAK int polyrhythm_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int polyrhythm_prologue_obj(void) { return 0; }
RTPC_WEAK int polyrhythm_retract_pistons(void) { return 0; }
RTPC_WEAK int polyrhythm_spawn_piston(void) { return 0; }
RTPC_WEAK int power_calligraphy_bg_map(void) { return 0; }
RTPC_WEAK int power_calligraphy_bg_tiles(void) { return 0; }
RTPC_WEAK int power_calligraphy_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int power_calligraphy_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int power_calligraphy_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int power_calligraphy_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int power_calligraphy_obj(void) { return 0; }
RTPC_WEAK int power_calligraphy_obj_dancers(void) { return 0; }
RTPC_WEAK int power_calligraphy_prologue_bg_map(void) { return 0; }
RTPC_WEAK int power_calligraphy_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int power_calligraphy_prologue_obj(void) { return 0; }
RTPC_WEAK int quiz_show_bg_map(void) { return 0; }
RTPC_WEAK int quiz_show_bg_map_spotlight(void) { return 0; }
RTPC_WEAK int quiz_show_bg_map_stands(void) { return 0; }
RTPC_WEAK int quiz_show_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int quiz_show_bg_tiles(void) { return 0; }
RTPC_WEAK int quiz_show_common_beat_animation(void) { return 0; }
RTPC_WEAK int quiz_show_common_display_text(void) { return 0; }
RTPC_WEAK int quiz_show_common_init_tutorial(void) { return 0; }
RTPC_WEAK int quiz_show_cue_barely(void) { return 0; }
RTPC_WEAK int quiz_show_cue_despawn(void) { return 0; }
RTPC_WEAK int quiz_show_cue_hit(void) { return 0; }
RTPC_WEAK int quiz_show_cue_miss(void) { return 0; }
RTPC_WEAK int quiz_show_cue_spawn(void) { return 0; }
RTPC_WEAK int quiz_show_cue_update(void) { return 0; }
RTPC_WEAK int quiz_show_engine_event_stub(void) { return 0; }
RTPC_WEAK int quiz_show_engine_start(void) { return 0; }
RTPC_WEAK int quiz_show_engine_stop(void) { return 0; }
RTPC_WEAK int quiz_show_engine_update(void) { return 0; }
RTPC_WEAK int quiz_show_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int quiz_show_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int quiz_show_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int quiz_show_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int quiz_show_input_event(void) { return 0; }
RTPC_WEAK int quiz_show_obj(void) { return 0; }
RTPC_WEAK int quiz_show_prologue_bg_map(void) { return 0; }
RTPC_WEAK int quiz_show_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int quiz_show_prologue_obj(void) { return 0; }
RTPC_WEAK int rank_results_obj(void) { return 0; }
RTPC_WEAK int rap_machine_bg_map(void) { return 0; }
RTPC_WEAK int rap_machine_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_machine_obj(void) { return 0; }
RTPC_WEAK int rap_men_bg_map(void) { return 0; }
RTPC_WEAK int rap_men_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_men_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int rap_men_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int rap_men_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int rap_men_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_men_obj(void) { return 0; }
RTPC_WEAK int rap_men_prologue_bg_map(void) { return 0; }
RTPC_WEAK int rap_men_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_men_prologue_obj(void) { return 0; }
RTPC_WEAK int rap_women_bg_map(void) { return 0; }
RTPC_WEAK int rap_women_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_women_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int rap_women_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int rap_women_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int rap_women_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_women_obj(void) { return 0; }
RTPC_WEAK int rap_women_prologue_bg_map(void) { return 0; }
RTPC_WEAK int rap_women_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int rap_women_prologue_obj(void) { return 0; }
RTPC_WEAK int rat_race_bg_map_cat(void) { return 0; }
RTPC_WEAK int rat_race_bg_map_cheese(void) { return 0; }
RTPC_WEAK int rat_race_bg_map_far(void) { return 0; }
RTPC_WEAK int rat_race_bg_map_middle(void) { return 0; }
RTPC_WEAK int rat_race_bg_map_near(void) { return 0; }
RTPC_WEAK int rat_race_bg_tiles(void) { return 0; }
RTPC_WEAK int rat_race_common_beat_animation(void) { return 0; }
RTPC_WEAK int rat_race_common_display_text(void) { return 0; }
RTPC_WEAK int rat_race_common_init_tutorial(void) { return 0; }
RTPC_WEAK int rat_race_cue_barely(void) { return 0; }
RTPC_WEAK int rat_race_cue_despawn_dash(void) { return 0; }
RTPC_WEAK int rat_race_cue_despawn_stop(void) { return 0; }
RTPC_WEAK int rat_race_cue_hit_dash(void) { return 0; }
RTPC_WEAK int rat_race_cue_hit_stop(void) { return 0; }
RTPC_WEAK int rat_race_cue_miss(void) { return 0; }
RTPC_WEAK int rat_race_cue_spawn_dash(void) { return 0; }
RTPC_WEAK int rat_race_cue_spawn_stop(void) { return 0; }
RTPC_WEAK int rat_race_cue_update_dash(void) { return 0; }
RTPC_WEAK int rat_race_cue_update_stop(void) { return 0; }
RTPC_WEAK int rat_race_engine_event_stub(void) { return 0; }
RTPC_WEAK int rat_race_engine_start(void) { return 0; }
RTPC_WEAK int rat_race_engine_stop(void) { return 0; }
RTPC_WEAK int rat_race_engine_update(void) { return 0; }
RTPC_WEAK int rat_race_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int rat_race_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int rat_race_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int rat_race_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int rat_race_input_event(void) { return 0; }
RTPC_WEAK int rat_race_obj(void) { return 0; }
RTPC_WEAK int rat_race_prologue_bg_map(void) { return 0; }
RTPC_WEAK int rat_race_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int rat_race_prologue_obj(void) { return 0; }
RTPC_WEAK int read_sram_fast_code(void) { return 0; }
RTPC_WEAK int read_sram_fast_rom(void) { return 0; }
RTPC_WEAK int reading_obj(void) { return 0; }
RTPC_WEAK int reading_style_bulletin_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_bulletin_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_cherry_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_cherry_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_classroom_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_classroom_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_cooking_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_cooking_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_haiku_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_haiku_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_mail_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_mail_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_manzai_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_manzai_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_sea_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_sea_bg_tiles(void) { return 0; }
RTPC_WEAK int reading_style_train_bg_map(void) { return 0; }
RTPC_WEAK int reading_style_train_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_1_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_1_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_1_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_1_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_1_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_1_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_1_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_2_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_2_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_2_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_2_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_2_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_2_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_2_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_3_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_3_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_3_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_3_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_3_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_3_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_3_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_4_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_4_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_4_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_4_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_4_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_4_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_4_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_5_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_5_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_5_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_5_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_5_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_5_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_5_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_6_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_6_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_6_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_6_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_6_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_6_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_6_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_7_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_7_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_7_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_7_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_7_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_7_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_7_prologue_obj(void) { return 0; }
RTPC_WEAK int remix_8_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int remix_8_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int remix_8_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int remix_8_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_8_prologue_bg_map(void) { return 0; }
RTPC_WEAK int remix_8_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int remix_8_prologue_obj(void) { return 0; }
RTPC_WEAK int rhythm_test_bg_map(void) { return 0; }
RTPC_WEAK int rhythm_test_bg_map_chart(void) { return 0; }
RTPC_WEAK int rhythm_test_bg_map_foreground(void) { return 0; }
RTPC_WEAK int rhythm_test_bg_tiles(void) { return 0; }
RTPC_WEAK int rhythm_test_common_beat_animation(void) { return 0; }
RTPC_WEAK int rhythm_test_common_display_text(void) { return 0; }
RTPC_WEAK int rhythm_test_common_init_tutorial(void) { return 0; }
RTPC_WEAK int rhythm_test_cue_barely(void) { return 0; }
RTPC_WEAK int rhythm_test_cue_despawn(void) { return 0; }
RTPC_WEAK int rhythm_test_cue_hit(void) { return 0; }
RTPC_WEAK int rhythm_test_cue_miss(void) { return 0; }
RTPC_WEAK int rhythm_test_cue_spawn(void) { return 0; }
RTPC_WEAK int rhythm_test_cue_update(void) { return 0; }
RTPC_WEAK int rhythm_test_engine_event_stub(void) { return 0; }
RTPC_WEAK int rhythm_test_engine_start(void) { return 0; }
RTPC_WEAK int rhythm_test_engine_stop(void) { return 0; }
RTPC_WEAK int rhythm_test_engine_update(void) { return 0; }
RTPC_WEAK int rhythm_test_input_event(void) { return 0; }
RTPC_WEAK int rhythm_test_obj(void) { return 0; }
RTPC_WEAK int rhythm_toys_menu_bg_map(void) { return 0; }
RTPC_WEAK int rhythm_toys_menu_bg_tiles(void) { return 0; }
RTPC_WEAK int rhythm_toys_menu_obj(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_bg_map_onion(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_bg_map_potato(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_bg_map_turnip(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_bg_tiles(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_cue_update_long(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_no_peeking_sign_bg_map(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_no_peeking_sign_bg_tiles(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_obj(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_prologue_bg_map(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int rhythm_tweezers_prologue_obj(void) { return 0; }
s8 sMainMenuButton = 0;
u32 sRecCurrentKey = 0;
u32 sRecMaxKeys = 0;
u8 sSceneTextCurrentStringId = 0;
RTPC_WEAK int samurai_slice_bg_map(void) { return 0; }
RTPC_WEAK int samurai_slice_bg_map_fog_bottom(void) { return 0; }
RTPC_WEAK int samurai_slice_bg_map_fog_top(void) { return 0; }
RTPC_WEAK int samurai_slice_bg_tiles(void) { return 0; }
RTPC_WEAK int samurai_slice_common_beat_animation(void) { return 0; }
RTPC_WEAK int samurai_slice_common_display_text(void) { return 0; }
RTPC_WEAK int samurai_slice_cue_barely(void) { return 0; }
RTPC_WEAK int samurai_slice_cue_despawn(void) { return 0; }
RTPC_WEAK int samurai_slice_cue_hit(void) { return 0; }
RTPC_WEAK int samurai_slice_cue_miss(void) { return 0; }
RTPC_WEAK int samurai_slice_cue_spawn(void) { return 0; }
RTPC_WEAK int samurai_slice_cue_update(void) { return 0; }
RTPC_WEAK int samurai_slice_engine_event_stub(void) { return 0; }
RTPC_WEAK int samurai_slice_engine_start(void) { return 0; }
RTPC_WEAK int samurai_slice_engine_stop(void) { return 0; }
RTPC_WEAK int samurai_slice_engine_update(void) { return 0; }
RTPC_WEAK int samurai_slice_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int samurai_slice_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int samurai_slice_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int samurai_slice_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int samurai_slice_input_event(void) { return 0; }
RTPC_WEAK int samurai_slice_obj(void) { return 0; }
RTPC_WEAK int samurai_slice_prologue_bg_map(void) { return 0; }
RTPC_WEAK int samurai_slice_prologue_bg_map_slice(void) { return 0; }
RTPC_WEAK int samurai_slice_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int samurai_slice_prologue_obj(void) { return 0; }
RTPC_WEAK int scene_arrival(void) { return 0; }
RTPC_WEAK int scene_bon_dance(void) { return 0; }
RTPC_WEAK int scene_bon_odori(void) { return 0; }
RTPC_WEAK int scene_bouncy_road(void) { return 0; }
RTPC_WEAK int scene_bouncy_road_2(void) { return 0; }
RTPC_WEAK int scene_bunny_hop(void) { return 0; }
RTPC_WEAK int scene_cafe(void) { return 0; }
RTPC_WEAK int scene_cat_machine(void) { return 0; }
RTPC_WEAK int scene_clappy_trio(void) { return 0; }
RTPC_WEAK int scene_cosmic_dance(void) { return 0; }
RTPC_WEAK int scene_data_check(void) { return 0; }
RTPC_WEAK int scene_data_clear(void) { return 0; }
RTPC_WEAK int scene_data_room(void) { return 0; }
RTPC_WEAK int scene_drum_girls_live_unused(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_basic_1(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_basic_2(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_hi_tech_1(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_hi_tech_2(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_long_1(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_long_2(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_long_3(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_long_4(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_long_5(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_long_6(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_1(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_2(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_3(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_4(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_5(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_6(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_7(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_8(void) { return 0; }
RTPC_WEAK int scene_drum_lesson_short_9(void) { return 0; }
RTPC_WEAK int scene_drum_live(void) { return 0; }
/* scene_drum_samurai_demo_cutscene – defined as struct Scene in platform/game_globals.c */
/* scene_drum_samurai_opening_cutscene – defined as struct Scene in platform/game_globals.c */
RTPC_WEAK int scene_drum_studio_drumming(void) { return 0; }
RTPC_WEAK int scene_drum_studio_listening(void) { return 0; }
RTPC_WEAK int scene_drum_studio_ver0(void) { return 0; }
RTPC_WEAK int scene_endless_menu(void) { return 0; }
RTPC_WEAK int scene_epilogue(void) { return 0; }
RTPC_WEAK int scene_fireworks(void) { return 0; }
RTPC_WEAK int scene_flash_mem_test(void) { return 0; }
RTPC_WEAK int scene_game_select(void) { return 0; }
RTPC_WEAK int scene_karate_man(void) { return 0; }
RTPC_WEAK int scene_karate_man_2(void) { return 0; }
RTPC_WEAK int scene_lessons_menu(void) { return 0; }
RTPC_WEAK int scene_love_machine(void) { return 0; }
/* scene_main_menu – defined as struct Scene in platform/game_globals.c */
RTPC_WEAK int scene_mannequin_factory(void) { return 0; }
RTPC_WEAK int scene_marching_orders(void) { return 0; }
RTPC_WEAK int scene_marching_orders_2(void) { return 0; }
RTPC_WEAK int scene_mechanical_horse(void) { return 0; }
RTPC_WEAK int scene_metronome(void) { return 0; }
RTPC_WEAK int scene_mr_upbeat(void) { return 0; }
RTPC_WEAK int scene_night_walk(void) { return 0; }
RTPC_WEAK int scene_night_walk_2(void) { return 0; }
RTPC_WEAK int scene_ninja_bodyguard(void) { return 0; }
RTPC_WEAK int scene_ninja_reincarnate(void) { return 0; }
RTPC_WEAK int scene_options_menu(void) { return 0; }
RTPC_WEAK int scene_perfect(void) { return 0; }
RTPC_WEAK int scene_polyrhythm(void) { return 0; }
RTPC_WEAK int scene_polyrhythm_2(void) { return 0; }
RTPC_WEAK int scene_power_calligraphy(void) { return 0; }
RTPC_WEAK int scene_quiz_show(void) { return 0; }
RTPC_WEAK int scene_quiz_show_endless(void) { return 0; }
RTPC_WEAK int scene_rap_machine(void) { return 0; }
RTPC_WEAK int scene_rap_men(void) { return 0; }
RTPC_WEAK int scene_rap_women(void) { return 0; }
RTPC_WEAK int scene_rap_women_unused(void) { return 0; }
RTPC_WEAK int scene_rat_race(void) { return 0; }
RTPC_WEAK int scene_reading(void) { return 0; }
RTPC_WEAK int scene_remix_1(void) { return 0; }
RTPC_WEAK int scene_remix_1_unused(void) { return 0; }
RTPC_WEAK int scene_remix_2(void) { return 0; }
RTPC_WEAK int scene_remix_3(void) { return 0; }
RTPC_WEAK int scene_remix_4(void) { return 0; }
RTPC_WEAK int scene_remix_5(void) { return 0; }
RTPC_WEAK int scene_remix_6(void) { return 0; }
RTPC_WEAK int scene_remix_7(void) { return 0; }
RTPC_WEAK int scene_remix_8(void) { return 0; }
RTPC_WEAK int scene_results_ver_debug(void) { return 0; }
RTPC_WEAK int scene_results_ver_rank(void) { return 0; }
RTPC_WEAK int scene_results_ver_score(void) { return 0; }
RTPC_WEAK int scene_rhythm_test(void) { return 0; }
RTPC_WEAK int scene_rhythm_test_click(void) { return 0; }
RTPC_WEAK int scene_rhythm_test_cue(void) { return 0; }
RTPC_WEAK int scene_rhythm_test_opening(void) { return 0; }
RTPC_WEAK int scene_rhythm_test_trick(void) { return 0; }
RTPC_WEAK int scene_rhythm_tweezers(void) { return 0; }
RTPC_WEAK int scene_rhythm_tweezers_2(void) { return 0; }
RTPC_WEAK int scene_samurai_slice(void) { return 0; }
RTPC_WEAK int scene_showtime(void) { return 0; }
RTPC_WEAK int scene_sick_beats(void) { return 0; }
RTPC_WEAK int scene_sick_beats_endless(void) { return 0; }
RTPC_WEAK int scene_snappy_trio(void) { return 0; }
RTPC_WEAK int scene_sneaky_spirits(void) { return 0; }
RTPC_WEAK int scene_sneaky_spirits_2(void) { return 0; }
RTPC_WEAK int scene_space_dance(void) { return 0; }
RTPC_WEAK int scene_spaceball(void) { return 0; }
RTPC_WEAK int scene_spaceball_2(void) { return 0; }
RTPC_WEAK int scene_staff_credit(void) { return 0; }
RTPC_WEAK int scene_staff_credit_remix_6(void) { return 0; }
RTPC_WEAK int scene_tap_trial(void) { return 0; }
RTPC_WEAK int scene_tap_trial_2(void) { return 0; }
RTPC_WEAK int scene_title(void) { return 0; }
RTPC_WEAK int scene_toss_boys(void) { return 0; }
RTPC_WEAK int scene_toss_boys_2(void) { return 0; }
RTPC_WEAK int scene_toys_menu(void) { return 0; }
RTPC_WEAK int scene_tram_pauline(void) { return 0; }
RTPC_WEAK int scene_wizards_waltz(void) { return 0; }
RTPC_WEAK int score_results_obj(void) { return 0; }
RTPC_WEAK int script_studio_bon_dance(void) { return 0; }
RTPC_WEAK int script_studio_bon_odori(void) { return 0; }
RTPC_WEAK int script_studio_bouncy_road(void) { return 0; }
RTPC_WEAK int script_studio_bunny_hop(void) { return 0; }
RTPC_WEAK int script_studio_cafe(void) { return 0; }
RTPC_WEAK int script_studio_clappy_trio(void) { return 0; }
RTPC_WEAK int script_studio_cosmic_dance(void) { return 0; }
RTPC_WEAK int script_studio_data_room(void) { return 0; }
RTPC_WEAK int script_studio_fireworks(void) { return 0; }
RTPC_WEAK int script_studio_game_select_1(void) { return 0; }
RTPC_WEAK int script_studio_game_select_2(void) { return 0; }
RTPC_WEAK int script_studio_honey_sweet_angel(void) { return 0; }
RTPC_WEAK int script_studio_karate_man(void) { return 0; }
RTPC_WEAK int script_studio_main_menu(void) { return 0; }
RTPC_WEAK int script_studio_marching_orders(void) { return 0; }
RTPC_WEAK int script_studio_night_walk(void) { return 0; }
RTPC_WEAK int script_studio_ok(void) { return 0; }
RTPC_WEAK int script_studio_opening(void) { return 0; }
RTPC_WEAK int script_studio_perfect(void) { return 0; }
RTPC_WEAK int script_studio_polyrhythm(void) { return 0; }
RTPC_WEAK int script_studio_power_calligraphy(void) { return 0; }
RTPC_WEAK int script_studio_quiz_show(void) { return 0; }
RTPC_WEAK int script_studio_rat_race(void) { return 0; }
RTPC_WEAK int script_studio_remix6(void) { return 0; }
RTPC_WEAK int script_studio_remix7(void) { return 0; }
RTPC_WEAK int script_studio_remix8(void) { return 0; }
RTPC_WEAK int script_studio_rhythm_tweezers(void) { return 0; }
RTPC_WEAK int script_studio_samurai_slice(void) { return 0; }
RTPC_WEAK int script_studio_showtime(void) { return 0; }
RTPC_WEAK int script_studio_sick_beats(void) { return 0; }
RTPC_WEAK int script_studio_silence(void) { return 0; }
RTPC_WEAK int script_studio_snappy_trio(void) { return 0; }
RTPC_WEAK int script_studio_sneaky_spirits(void) { return 0; }
RTPC_WEAK int script_studio_space_dance(void) { return 0; }
RTPC_WEAK int script_studio_spaceball(void) { return 0; }
RTPC_WEAK int script_studio_staff_credit(void) { return 0; }
RTPC_WEAK int script_studio_superb(void) { return 0; }
RTPC_WEAK int script_studio_tap_trial(void) { return 0; }
RTPC_WEAK int script_studio_tap_trial_2(void) { return 0; }
RTPC_WEAK int script_studio_title(void) { return 0; }
RTPC_WEAK int script_studio_toss_boys(void) { return 0; }
RTPC_WEAK int script_studio_tram_pauline(void) { return 0; }
RTPC_WEAK int script_studio_try_again(void) { return 0; }
RTPC_WEAK int script_studio_wish(void) { return 0; }
RTPC_WEAK int script_studio_wizards_waltz(void) { return 0; }
RTPC_WEAK int set_sram_fast_func(void) { return 0; }
RTPC_WEAK int showtime_bg_map(void) { return 0; }
RTPC_WEAK int showtime_bg_map_water(void) { return 0; }
RTPC_WEAK int showtime_bg_tiles(void) { return 0; }
RTPC_WEAK int showtime_common_beat_animation(void) { return 0; }
RTPC_WEAK int showtime_common_display_text(void) { return 0; }
RTPC_WEAK int showtime_common_init_tutorial(void) { return 0; }
RTPC_WEAK int showtime_cue_barely(void) { return 0; }
RTPC_WEAK int showtime_cue_miss(void) { return 0; }
RTPC_WEAK int showtime_cue_spawn_black(void) { return 0; }
RTPC_WEAK int showtime_cue_spawn_white_fast(void) { return 0; }
RTPC_WEAK int showtime_cue_spawn_white_fast_swing(void) { return 0; }
RTPC_WEAK int showtime_cue_update_white_fast(void) { return 0; }
RTPC_WEAK int showtime_engine_update(void) { return 0; }
RTPC_WEAK int showtime_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int showtime_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int showtime_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int showtime_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int showtime_obj(void) { return 0; }
RTPC_WEAK int showtime_prologue_bg_map(void) { return 0; }
RTPC_WEAK int showtime_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int showtime_prologue_obj(void) { return 0; }
RTPC_WEAK int showtime_remix_3_bg_map(void) { return 0; }
RTPC_WEAK int showtime_remix_3_bg_map_water(void) { return 0; }
RTPC_WEAK int showtime_remix_3_bg_tiles(void) { return 0; }
RTPC_WEAK int sick_beats_bg_map(void) { return 0; }
RTPC_WEAK int sick_beats_bg_map_foreground(void) { return 0; }
RTPC_WEAK int sick_beats_bg_tiles(void) { return 0; }
RTPC_WEAK int sick_beats_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int sick_beats_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int sick_beats_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int sick_beats_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int sick_beats_obj(void) { return 0; }
RTPC_WEAK int sick_beats_prologue_bg_map(void) { return 0; }
RTPC_WEAK int sick_beats_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int sick_beats_prologue_obj(void) { return 0; }
RTPC_WEAK int snappy_trio_bg_map(void) { return 0; }
RTPC_WEAK int snappy_trio_bg_tiles(void) { return 0; }
RTPC_WEAK int snappy_trio_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int snappy_trio_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int snappy_trio_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int snappy_trio_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int snappy_trio_obj(void) { return 0; }
RTPC_WEAK int snappy_trio_prologue_bg_map(void) { return 0; }
RTPC_WEAK int snappy_trio_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int snappy_trio_prologue_obj(void) { return 0; }
RTPC_WEAK int sneaky_spirits_bg_map(void) { return 0; }
RTPC_WEAK int sneaky_spirits_bg_map_foreground(void) { return 0; }
RTPC_WEAK int sneaky_spirits_bg_tiles(void) { return 0; }
RTPC_WEAK int sneaky_spirits_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int sneaky_spirits_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int sneaky_spirits_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int sneaky_spirits_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int sneaky_spirits_obj(void) { return 0; }
RTPC_WEAK int sneaky_spirits_prologue_bg_map(void) { return 0; }
RTPC_WEAK int sneaky_spirits_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int sneaky_spirits_prologue_obj(void) { return 0; }
RTPC_WEAK int space_dance_bg_map(void) { return 0; }
RTPC_WEAK int space_dance_bg_tiles(void) { return 0; }
RTPC_WEAK int space_dance_common_beat_animation(void) { return 0; }
RTPC_WEAK int space_dance_common_display_text(void) { return 0; }
RTPC_WEAK int space_dance_common_init_tutorial(void) { return 0; }
RTPC_WEAK int space_dance_cue_barely(void) { return 0; }
RTPC_WEAK int space_dance_cue_despawn(void) { return 0; }
RTPC_WEAK int space_dance_cue_hit(void) { return 0; }
RTPC_WEAK int space_dance_cue_miss(void) { return 0; }
RTPC_WEAK int space_dance_cue_spawn(void) { return 0; }
RTPC_WEAK int space_dance_cue_update(void) { return 0; }
RTPC_WEAK int space_dance_engine_event_stub(void) { return 0; }
RTPC_WEAK int space_dance_engine_start(void) { return 0; }
RTPC_WEAK int space_dance_engine_stop(void) { return 0; }
RTPC_WEAK int space_dance_engine_update(void) { return 0; }
RTPC_WEAK int space_dance_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int space_dance_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int space_dance_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int space_dance_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int space_dance_input_event(void) { return 0; }
RTPC_WEAK int space_dance_obj(void) { return 0; }
RTPC_WEAK int space_dance_prologue_bg_map(void) { return 0; }
RTPC_WEAK int space_dance_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int space_dance_prologue_obj(void) { return 0; }
RTPC_WEAK int space_dance_remix_3_bg_map(void) { return 0; }
RTPC_WEAK int space_dance_remix_3_bg_tiles(void) { return 0; }
RTPC_WEAK int spaceball_bg_map(void) { return 0; }
RTPC_WEAK int spaceball_bg_tiles(void) { return 0; }
RTPC_WEAK int spaceball_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int spaceball_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int spaceball_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int spaceball_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int spaceball_obj(void) { return 0; }
RTPC_WEAK int spaceball_prologue_bg_map(void) { return 0; }
RTPC_WEAK int spaceball_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int spaceball_prologue_obj(void) { return 0; }
RTPC_WEAK int staff_credit_bon_odori_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_bon_odori_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_clappy_trio_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_clappy_trio_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_drums_2_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_drums_2_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_drums_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_drums_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_karate_man_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_karate_man_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_spaceball_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_spaceball_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_tap_trial_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_tap_trial_bg_tiles(void) { return 0; }
RTPC_WEAK int staff_credit_toss_boys_bg_map(void) { return 0; }
RTPC_WEAK int staff_credit_toss_boys_bg_tiles(void) { return 0; }
RTPC_WEAK int start_new_texture_loader(void) { return 0; }
RTPC_WEAK int studio_bg_map(void) { return 0; }
RTPC_WEAK int studio_bg_map_warning(void) { return 0; }
RTPC_WEAK int studio_bg_tiles(void) { return 0; }
RTPC_WEAK int studio_memory_usage_graph_bg_map(void) { return 0; }
RTPC_WEAK int studio_obj(void) { return 0; }
RTPC_WEAK int tanuki_and_monkey_bg_map(void) { return 0; }
RTPC_WEAK int tanuki_and_monkey_bg_map_blank(void) { return 0; }
RTPC_WEAK int tanuki_and_monkey_bg_tiles(void) { return 0; }
RTPC_WEAK int tanuki_and_monkey_obj(void) { return 0; }
RTPC_WEAK int tap_trial_2_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_2_bg_map_2(void) { return 0; }
RTPC_WEAK int tap_trial_2_bg_map_stage(void) { return 0; }
RTPC_WEAK int tap_trial_2_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int tap_trial_2_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_2_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int tap_trial_2_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int tap_trial_2_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int tap_trial_2_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_2_obj(void) { return 0; }
RTPC_WEAK int tap_trial_2_prologue_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_2_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_2_prologue_obj(void) { return 0; }
RTPC_WEAK int tap_trial_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int tap_trial_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_common_beat_animation(void) { return 0; }
RTPC_WEAK int tap_trial_common_display_text(void) { return 0; }
RTPC_WEAK int tap_trial_cue_barely(void) { return 0; }
RTPC_WEAK int tap_trial_cue_despawn(void) { return 0; }
RTPC_WEAK int tap_trial_cue_hit(void) { return 0; }
RTPC_WEAK int tap_trial_cue_miss(void) { return 0; }
RTPC_WEAK int tap_trial_cue_spawn(void) { return 0; }
RTPC_WEAK int tap_trial_cue_update(void) { return 0; }
RTPC_WEAK int tap_trial_engine_event_stub(void) { return 0; }
RTPC_WEAK int tap_trial_engine_start(void) { return 0; }
RTPC_WEAK int tap_trial_engine_stop(void) { return 0; }
RTPC_WEAK int tap_trial_engine_update(void) { return 0; }
RTPC_WEAK int tap_trial_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int tap_trial_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int tap_trial_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int tap_trial_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_input_event(void) { return 0; }
RTPC_WEAK int tap_trial_obj(void) { return 0; }
RTPC_WEAK int tap_trial_play_monkey_action(void) { return 0; }
RTPC_WEAK int tap_trial_prologue_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_prologue_obj(void) { return 0; }
RTPC_WEAK int tap_trial_remix_5_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_remix_5_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_remix_5_obj(void) { return 0; }
RTPC_WEAK int tap_trial_remix_7_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_remix_7_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int tap_trial_remix_7_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_remix_7_obj(void) { return 0; }
RTPC_WEAK int tap_trial_remix_8_bg_map(void) { return 0; }
RTPC_WEAK int tap_trial_remix_8_bg_map_text_bubble(void) { return 0; }
RTPC_WEAK int tap_trial_remix_8_bg_tiles(void) { return 0; }
RTPC_WEAK int tap_trial_remix_8_obj(void) { return 0; }
RTPC_WEAK int text_print_glyph_to_vram_rom(void) { return 0; }
RTPC_WEAK int title_bg_map(void) { return 0; }
RTPC_WEAK int title_bg_tiles(void) { return 0; }
RTPC_WEAK int title_obj(void) { return 0; }
RTPC_WEAK int toss_boys_2_action_lines_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_2_action_lines_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_2_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_2_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_2_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int toss_boys_2_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int toss_boys_2_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int toss_boys_2_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_2_obj(void) { return 0; }
RTPC_WEAK int toss_boys_2_prologue_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_2_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_2_prologue_obj(void) { return 0; }
RTPC_WEAK int toss_boys_action_lines_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_action_lines_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_common_beat_animation(void) { return 0; }
RTPC_WEAK int toss_boys_common_display_text(void) { return 0; }
RTPC_WEAK int toss_boys_common_init_tutorial(void) { return 0; }
RTPC_WEAK int toss_boys_cue_barely(void) { return 0; }
RTPC_WEAK int toss_boys_cue_despawn(void) { return 0; }
RTPC_WEAK int toss_boys_cue_hit(void) { return 0; }
RTPC_WEAK int toss_boys_cue_miss(void) { return 0; }
RTPC_WEAK int toss_boys_cue_spawn(void) { return 0; }
RTPC_WEAK int toss_boys_cue_update(void) { return 0; }
RTPC_WEAK int toss_boys_engine_event_stub(void) { return 0; }
RTPC_WEAK int toss_boys_engine_start(void) { return 0; }
RTPC_WEAK int toss_boys_engine_stop(void) { return 0; }
RTPC_WEAK int toss_boys_engine_update(void) { return 0; }
RTPC_WEAK int toss_boys_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int toss_boys_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int toss_boys_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int toss_boys_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_input_event(void) { return 0; }
RTPC_WEAK int toss_boys_obj(void) { return 0; }
RTPC_WEAK int toss_boys_prologue_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_prologue_obj(void) { return 0; }
RTPC_WEAK int toss_boys_remix_5_bg_map(void) { return 0; }
RTPC_WEAK int toss_boys_remix_5_bg_tiles(void) { return 0; }
RTPC_WEAK int toss_boys_remix_5_obj(void) { return 0; }
RTPC_WEAK int tram_pauline_bg_map(void) { return 0; }
RTPC_WEAK int tram_pauline_bg_map_curtain(void) { return 0; }
RTPC_WEAK int tram_pauline_bg_tiles(void) { return 0; }
RTPC_WEAK int tram_pauline_common_beat_animation(void) { return 0; }
RTPC_WEAK int tram_pauline_common_display_text(void) { return 0; }
RTPC_WEAK int tram_pauline_common_init_tutorial(void) { return 0; }
RTPC_WEAK int tram_pauline_cue_barely(void) { return 0; }
RTPC_WEAK int tram_pauline_cue_despawn(void) { return 0; }
RTPC_WEAK int tram_pauline_cue_hit(void) { return 0; }
RTPC_WEAK int tram_pauline_cue_miss(void) { return 0; }
RTPC_WEAK int tram_pauline_cue_spawn(void) { return 0; }
RTPC_WEAK int tram_pauline_cue_update(void) { return 0; }
RTPC_WEAK int tram_pauline_engine_start(void) { return 0; }
RTPC_WEAK int tram_pauline_engine_stop(void) { return 0; }
RTPC_WEAK int tram_pauline_engine_update(void) { return 0; }
RTPC_WEAK int tram_pauline_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int tram_pauline_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int tram_pauline_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int tram_pauline_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int tram_pauline_input_event(void) { return 0; }
RTPC_WEAK int tram_pauline_obj(void) { return 0; }
RTPC_WEAK int tram_pauline_prologue_bg_map(void) { return 0; }
RTPC_WEAK int tram_pauline_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int tram_pauline_prologue_obj(void) { return 0; }
RTPC_WEAK int tram_pauline_remix_3_bg_map(void) { return 0; }
RTPC_WEAK int tram_pauline_remix_3_bg_tiles(void) { return 0; }
RTPC_WEAK int tram_pauline_remix_3_obj(void) { return 0; }
RTPC_WEAK int update_texture_loader_task(void) { return 0; }
RTPC_WEAK int verify_sram_fast_code(void) { return 0; }
RTPC_WEAK int verify_sram_fast_rom(void) { return 0; }
RTPC_WEAK int warning_bg_map(void) { return 0; }
RTPC_WEAK int warning_bg_tiles(void) { return 0; }
RTPC_WEAK int wizards_waltz_bg_map(void) { return 0; }
RTPC_WEAK int wizards_waltz_bg_tiles(void) { return 0; }
RTPC_WEAK int wizards_waltz_epilogue_bg_map_ok(void) { return 0; }
RTPC_WEAK int wizards_waltz_epilogue_bg_map_superb(void) { return 0; }
RTPC_WEAK int wizards_waltz_epilogue_bg_map_try_again(void) { return 0; }
RTPC_WEAK int wizards_waltz_epilogue_bg_tiles(void) { return 0; }
RTPC_WEAK int wizards_waltz_obj(void) { return 0; }
RTPC_WEAK int wizards_waltz_prologue_bg_map(void) { return 0; }
RTPC_WEAK int wizards_waltz_prologue_bg_tiles(void) { return 0; }
RTPC_WEAK int wizards_waltz_prologue_obj(void) { return 0; }
RTPC_WEAK int write_int_sram_fast_code(void) { return 0; }
RTPC_WEAK int write_int_sram_fast_rom(void) { return 0; }
#endif
