/* Generated by tools/bs2c.py from games/drum_studio/drum_lesson_long_5.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "games/drum_studio/drum_lessons_text.h"
#include "include/engines/drum_studio.h"
#include "include/sequence_data.h"
#include "src/code_08047e50.h"
#include "src/scenes/riq_main_scene.h"

extern char drum_lessons_sub_08a7d7a0[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern const struct Beatscript script_drum_lesson_long_5_entry[];
extern const struct SubScene sub_scene_drum_lesson_long_5;
extern struct Scene scene_drum_lesson_long_5;
extern const char D_08063e10[];
extern const struct Beatscript D_08063e68[];
extern const struct Beatscript D_08064084[];
extern const char D_080640d8[];
extern const struct Beatscript D_08064114[];
extern const struct Beatscript D_0806433c[];
extern const char D_0806439c[];
extern const struct Beatscript D_080643d4[];
extern const char D_080645fc[];
extern const struct Beatscript D_08064640[];
extern const void *D_08a431e0[];
extern const void *D_08a431f0[];
extern const void *D_08a43200[];
extern const void *D_08a43210[];
extern const struct Beatscript script_drum_lesson_long_5_main[];

const struct Beatscript script_drum_lesson_long_5_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 4, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_lesson_long_5_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_lesson_long_5 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_lesson_long_5_entry,
};

struct Scene scene_drum_lesson_long_5 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_lesson_long_5),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const char D_08063e10[] = "\202\346\202\255\202\253\202\242\202\304\203}\203l\202\265\202\304\202\313\201B\n\215D\202\253\202\310\203^\203C\203~\203\223\203O\202\305\202\307\202\244\202\274\201B\n\211\211\221t\202\360\216~\202\337\202\351\202\306\201A\n\202\250\216\350\226{\202\252\202\253\202\257\202\351\203\210\201I";

const struct Beatscript D_08063e68[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript D_08064084[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_080640d8[] = "\n\203X\203l\203A\202\306\203V\203\223\203o\203\213\202\305\n\202\253\202\301\202\277\202\350\201A\202\334\202\306\202\337\202\346\202\244\201I\n\202\252\202\361\202\316\202\301\202\304\201I\n";

const struct Beatscript D_08064114[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript D_0806433c[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0806439c[] = "\n\202P\203\225\217\212\202\276\202\257\201A\203X\203l\203A\202\360\n\203^\203\200\202\311\202\251\202\246\202\304\202\335\202\351\203\210\201B\n\202\355\202\251\202\351\202\251\202\310\201H";

const struct Beatscript D_080643d4[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x05)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_080645fc[] = "\n\202\263\202\242\202\262\202\311\203X\203l\203A\202\360\202\340\202\244\202P\202\302\201I\n\216\350\217\207\202\360\202\346\202\255\215l\202\246\202\304\202\335\202\304\203l\201B\n\202\252\202\361\202\316\202\352\201`\201I";

const struct Beatscript D_08064640[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x05)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const void *D_08a431e0[] = {
    (const void *)(D_08064084),
    (const void *)(D_08063e68),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_08063e10),
};

const void *D_08a431f0[] = {
    (const void *)(D_0806433c),
    (const void *)(D_08064114),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_080640d8),
};

const void *D_08a43200[] = {
    (const void *)(D_0806433c),
    (const void *)(D_080643d4),
    (const void *)(&s_warai_little_seqData),
    (const void *)(D_0806439c),
};

const void *D_08a43210[] = {
    (const void *)(D_0806433c),
    (const void *)(D_08064640),
    (const void *)(&s_warai_seqData),
    (const void *)(D_080645fc),
};

const struct Beatscript script_drum_lesson_long_5_main[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(110) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(4) },
    { 0x04, (0x08), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, (0x09), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x02), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a431e0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a431f0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a43200) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a43210) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x10), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)((4)) },
    { 0x04, (0x12), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x14), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
