/* Generated by tools/bs2c.py from games/drum_studio/drum_studio.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/engines/drum_studio.h"
#include "src/scenes/riq_main_scene.h"

extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x0F[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x12[];   /* undeclared in any header */
extern char x15[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern char xB0[];   /* undeclared in any header */
extern char xB1[];   /* undeclared in any header */
extern const struct Beatscript script_drum_studio_ver0_entry[];
extern const struct SubScene sub_scene_drum_studio_ver0;
extern struct Scene scene_drum_studio_ver0;
extern const struct Beatscript script_drum_studio_drumming_entry[];
extern const struct SubScene sub_scene_drum_studio_drumming;
extern struct Scene scene_drum_studio_drumming;
extern const struct Beatscript script_drum_studio_ver2_entry[];
extern const struct SubScene sub_scene_drum_studio_ver2;
extern struct Scene scene_drum_studio_ver2;
extern const struct Beatscript script_drum_studio_listening_entry[];
extern const struct SubScene sub_scene_drum_studio_listening;
extern struct Scene scene_drum_studio_listening;
extern const struct Beatscript script_drum_studio_main[];
extern const struct Beatscript script_drum_studio_ver0_main[];
extern const struct Beatscript script_drum_studio_drumming_main[];
extern const struct Beatscript script_drum_studio_ver2_main[];
extern const struct Beatscript script_drum_studio_listening_main[];

const struct Beatscript script_drum_studio_ver0_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_studio_ver0_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_studio_ver0 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_studio_ver0_entry,
};

struct Scene scene_drum_studio_ver0 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_studio_ver0),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_drum_studio_drumming_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_studio_drumming_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_studio_drumming = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_studio_drumming_entry,
};

struct Scene scene_drum_studio_drumming = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_studio_drumming),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_drum_studio_ver2_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 2, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_studio_ver2_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_studio_ver2 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_studio_ver2_entry,
};

struct Scene scene_drum_studio_ver2 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_studio_ver2),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_drum_studio_listening_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 3, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_studio_listening_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_studio_listening = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_studio_listening_entry,
};

struct Scene scene_drum_studio_listening = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_studio_listening),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_drum_studio_main[] = {
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(140) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0xB1, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, GET_NEXT_SCRIPT, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0xB0, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, STOP_BG_MONITOR, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x12, INT8, (const void *)(GLOBAL_VARIABLE), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(beatscript_disable_loops), (uintptr_t)(0) },
    { 0x15, 0, NULL, (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, SHOW_SAVE_OPTIONS, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(140) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_drum_studio_ver0_main[] = {
    { 0x0F, 0, (const void *)(script_drum_studio_main), (uintptr_t)(0) },
};

const struct Beatscript script_drum_studio_drumming_main[] = {
    { 0x0F, 0, (const void *)(script_drum_studio_main), (uintptr_t)(0) },
};

const struct Beatscript script_drum_studio_ver2_main[] = {
    { 0x0F, 0, (const void *)(script_drum_studio_main), (uintptr_t)(0) },
};

const struct Beatscript script_drum_studio_listening_main[] = {
    { 0x0F, 0, (const void *)(script_drum_studio_main), (uintptr_t)(0) },
};
