/* Generated by tools/bs2c.py from games/drum_studio/drum_lesson_hi_tech_2.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "games/drum_studio/drum_lessons_text.h"
#include "include/engines/drum_studio.h"
#include "include/sequence_data.h"
#include "src/code_08047e50.h"
#include "src/scenes/riq_main_scene.h"

extern char drum_lessons_sub_08a7d7a0[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern const struct Beatscript script_drum_lesson_hi_tech_2_entry[];
extern const struct SubScene sub_scene_drum_lesson_hi_tech_2;
extern struct Scene scene_drum_lesson_hi_tech_2;
extern const char D_08065f9c[];
extern const struct Beatscript D_08065fc4[];
extern const struct Beatscript D_080661ec[];
extern const char D_08066258[];
extern const struct Beatscript D_08066294[];
extern const char D_08066480[];
extern const struct Beatscript D_080664b0[];
extern const char D_080666c0[];
extern const struct Beatscript D_080666f0[];
extern const char D_08066918[];
extern const struct Beatscript D_08066964[];
extern const char D_08066ba4[];
extern const struct Beatscript D_08066bd4[];
extern const char D_08066e20[];
extern const struct Beatscript D_08066e6c[];
extern const char D_080670c4[];
extern const struct Beatscript D_0806710c[];
extern const char D_08067370[];
extern const struct Beatscript D_080673c8[];
extern const char D_08067638[];
extern const char D_08067668[];
extern const char D_0806769c[];
extern const void *D_08a437b4[];
extern const void *D_08a437c4[];
extern const void *D_08a437d4[];
extern const void *D_08a437e4[];
extern const void *D_08a437f4[];
extern const void *D_08a43804[];
extern const void *D_08a43814[];
extern const void *D_08a43824[];
extern const void *D_08a43834[];
extern const struct Beatscript script_drum_lesson_hi_tech_2_main[];

const struct Beatscript script_drum_lesson_hi_tech_2_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 4, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_lesson_hi_tech_2_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_lesson_hi_tech_2 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_lesson_hi_tech_2_entry,
};

struct Scene scene_drum_lesson_hi_tech_2 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_lesson_hi_tech_2),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const char D_08065f9c[] = "\n\202\334\202\270\202\315\201A\202\250\202\263\202\347\202\242\202\305\202\267\201B\n\202\252\202\361\202\316\202\301\202\304\203l\201I";

const struct Beatscript D_08065fc4[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript D_080661ec[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08066258[] = "\n\202\261\202\261\202\251\202\347\202\252\217\237\225\211\202\305\202\267\201I\n\202\346\201`\202\255\202\253\202\242\202\304\201A\n\202\277\202\341\202\361\202\306\203}\203l\202\265\202\304\203l\201I\n";

const struct Beatscript D_08066294[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08066480[] = "\n\203o\203X\202\306\203X\203l\203A\202\360\n\202\277\202\345\202\301\202\306\201@\202\275\202\267\203\210\201I\n\202\305\202\253\202\351\202\251\202\310\201H";

const struct Beatscript D_080664b0[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_080666c0[] = "\n\203o\203X\203h\203\211\203\200\202\360\202P\202\302\n\202\323\202\342\202\265\202\304\202\335\202\351\203\210\201B\n\202\252\202\361\202\316\202\301\202\304\201I";

const struct Beatscript D_080666f0[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08066918[] = "\202\263\202\347\202\311\201A\202\334\202\275\202\334\202\275\n\203o\203X\202\306\203X\203l\203A\202\360\222\307\211\301\201I\201I\n\203L\203~\202\310\202\347\202\305\202\253\202\351\201I\n\202\252\202\361\202\316\202\352\201`\201I\201I\n";

const struct Beatscript D_08066964[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08066ba4[] = "\n\203o\203X\203h\203\211\203\200\202\360\202P\202\302\n\202\323\202\342\202\265\202\304\202\335\202\351\203\210\201B\n\203L\203\201\202\304\203l\201I\201I";

const struct Beatscript D_08066bd4[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08066e20[] = "\202\263\202\301\202\253\202\314\203o\203X\203h\203\211\202\311\n\203V\203\223\203o\203\213\202\360\202\251\202\263\202\313\202\351\203\210\201I\n\202\261\202\352\202\315\201A\203\200\203Y\203C\201I\201I\n\203t\203@\203C\203g\201[\201I\201I";

const struct Beatscript D_08066e6c[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x06)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_080670c4[] = "\n\202\261\202\352\202\334\202\275\203\200\203Y\203C\202\306\202\261\202\353\202\311\n\203X\203l\203A\202\360\202P\202\302\222\307\211\301\201I\201I\n\202\340\202\244\201A\202\242\202\255\202\265\202\251\202\310\202\242\201I\201I\201I";

const struct Beatscript D_0806710c[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x06)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08067370[] = "\202\261\202\352\202\305\201@\202\263\202\242\202\262\201I\n\203^\203\200\202\360\202P\202\302\222\307\211\301\202\267\202\351\203\210\201I\n\227\254\202\352\202\351\202\346\202\244\202\310\203C\203J\202\265\202\275\n\203v\203\214\203C\202\360\202\346\202\353\202\265\202\255\202\305\202\267\201I\201I";

const struct Beatscript D_080673c8[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x07)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x00)) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x06)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x05)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x03)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08067638[] = "\n\215\241\211\361\202\315\201A\n\202P\202\302\221O\202\314\203\214\203b\203X\203\223\202\360\n\211\236\227p\202\265\202\304\202\335\202\334\202\267\201B";

const char D_08067668[] = "\n\202P\202\302\221O\202\314\203\214\203b\203X\203\223\202\360\n\203N\203\212\203A\202\265\202\304\202\251\202\347\201A\n\222\247\220\355\202\265\202\304\203l\201I";

const char D_0806769c[] = "\n\202\305\202\315\201A\202\315\202\266\202\337\202\334\201[\202\267\201I";

const void *D_08a437b4[] = {
    (const void *)(D_080661ec),
    (const void *)(D_08065fc4),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_08065f9c),
};

const void *D_08a437c4[] = {
    (const void *)(D_080661ec),
    (const void *)(D_08066294),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_08066258),
};

const void *D_08a437d4[] = {
    (const void *)(D_080661ec),
    (const void *)(D_080664b0),
    (const void *)(&s_warai_little_seqData),
    (const void *)(D_08066480),
};

const void *D_08a437e4[] = {
    (const void *)(D_080661ec),
    (const void *)(D_080666f0),
    (const void *)(&s_warai_seqData),
    (const void *)(D_080666c0),
};

const void *D_08a437f4[] = {
    (const void *)(D_080661ec),
    (const void *)(D_08066964),
    (const void *)(&s_kansei_solo_seqData),
    (const void *)(D_08066918),
};

const void *D_08a43804[] = {
    (const void *)(D_080661ec),
    (const void *)(D_08066bd4),
    (const void *)(&s_kansei_seqData),
    (const void *)(D_08066ba4),
};

const void *D_08a43814[] = {
    (const void *)(D_080661ec),
    (const void *)(D_08066e6c),
    (const void *)(&s_kansei_seqData),
    (const void *)(D_08066e20),
};

const void *D_08a43824[] = {
    (const void *)(D_080661ec),
    (const void *)(D_0806710c),
    (const void *)(&s_kansei_seqData),
    (const void *)(D_080670c4),
};

const void *D_08a43834[] = {
    (const void *)(D_080661ec),
    (const void *)(D_080673c8),
    (const void *)(&s_kansei_seqData),
    (const void *)(D_08067370),
};

const struct Beatscript script_drum_lesson_hi_tech_2_main[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(110) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(4) },
    { 0x04, (0x08), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, (0x09), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x02), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_08067638) },
    { 0x04, (0x0D), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x15), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x16), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_08067668) },
    { 0x04, (0x0D), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x15), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x16), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0806769c) },
    { 0x04, (0x0D), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x15), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x16), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a437b4) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a437c4) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a437d4) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a437e4) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a437f4) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a43804) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a43814) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a43824) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a43834) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x10), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)((4)) },
    { 0x04, (0x12), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x14), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
