/* Generated by tools/bs2c.py from games/drum_studio/drum_lesson_short_4.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "games/drum_studio/drum_lessons_text.h"
#include "include/engines/drum_studio.h"
#include "include/sequence_data.h"
#include "src/code_08047e50.h"
#include "src/scenes/riq_main_scene.h"

extern char drum_lessons_sub_08a7d7a0[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern const struct Beatscript script_drum_lesson_short_4_entry[];
extern const struct SubScene sub_scene_drum_lesson_short_4;
extern struct Scene scene_drum_lesson_short_4;
extern const char D_0805f560[];
extern const struct Beatscript D_0805f5b8[];
extern const struct Beatscript D_0805f624[];
extern const char D_0805f648[];
extern const struct Beatscript D_0805f670[];
extern const char D_0805f6ac[];
extern const struct Beatscript D_0805f6ec[];
extern const char D_0805f740[];
extern const struct Beatscript D_0805f770[];
extern const char D_0805f7f4[];
extern const struct Beatscript D_0805f840[];
extern const char D_0805f8dc[];
extern const struct Beatscript D_0805f918[];
extern const char D_0805f9cc[];
extern const char D_0805fa10[];
extern const char D_0805fa60[];
extern const void *D_08a41230[];
extern const void *D_08a41240[];
extern const void *D_08a41250[];
extern const void *D_08a41260[];
extern const void *D_08a41270[];
extern const void *D_08a41280[];
extern const struct Beatscript script_drum_lesson_short_4_main[];

const struct Beatscript script_drum_lesson_short_4_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 4, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_lesson_short_4_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_lesson_short_4 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_lesson_short_4_entry,
};

struct Scene scene_drum_lesson_short_4 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_lesson_short_4),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const char D_0805f560[] = "\202\346\202\255\202\253\202\242\202\304\203}\203l\202\265\202\304\202\313\201B\n\215D\202\253\202\310\203^\203C\203~\203\223\203O\202\305\202\307\202\244\202\274\201B\n\211\211\221t\202\360\216~\202\337\202\351\202\306\201A\n\202\250\216\350\226{\202\252\202\253\202\257\202\351\203\210\201I";

const struct Beatscript D_0805f5b8[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript D_0805f624[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(21) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0805f648[] = "\n\202P\203J\217\212\201A\211\271\202\252\202\323\202\246\202\351\203\210\201I\n\202\355\202\251\202\351\202\251\202\310\201H\n";

const struct Beatscript D_0805f670[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(18) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0805f6ac[] = "\202\263\202\347\202\311\202P\202\302\201A\n\211\271\202\252\202\323\202\246\202\351\203\210\201I\n\202\355\202\251\202\351\202\251\202\310\201H\n\203q\203\223\203g\201F\217\\\216\232\203{\203^\203\223\217\343";

const struct Beatscript D_0805f6ec[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x04)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0805f740[] = "\n\202\334\202\275\202\334\202\275\202P\203J\217\212\201A\n\211\271\202\252\202\323\202\246\202\351\203\210\201I\n\202\355\202\251\202\351\202\251\202\310\201H\n";

const struct Beatscript D_0805f770[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0805f7f4[] = "\202\273\202\265\202\304\202\334\202\275\202\310\202\361\202\306\201I\n\202P\203J\217\212\201A\211\271\202\252\202\323\202\246\202\351\203\210\201I\n\202\355\202\251\202\351\202\251\202\310\201H\n\203q\203\223\203g\201F\217\\\216\232\203{\203^\203\223\211E";

const struct Beatscript D_0805f840[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x05)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0805f8dc[] = "\n\202\261\202\352\202\334\202\275\202\310\202\361\202\306\201I\201I\n\202P\203J\217\212\201A\211\271\202\252\202\323\202\246\202\351\203\210\201I\n\202\355\202\251\202\351\202\251\202\310\201H\n";

const struct Beatscript D_0805f918[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x01)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x02)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)((0x05)) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0805f9cc[] = "\217\\\216\232\203{\203^\203\223\202\314\217\343\202\305\n\202\275\202\275\202\242\202\275\203p\201[\203c\202\315\n\203n\203C\203n\203b\203g\202\301\202\304\202\242\202\244\n\203V\203\223\203o\203\213\202\305\202\267\201B";

const char D_0805fa10[] = "\203h\203\211\203\200\203Z\203b\203g\202\311\202\346\202\301\202\304\n\217\\\216\232\203{\203^\203\223\202\314\217\343\202\315\n\203n\203C\203n\203b\203g\202\276\202\301\202\275\202\350\n\203\215\201[\203\213\202\276\202\301\202\275\202\350\202\265\202\334\202\267\201B";

const char D_0805fa60[] = "\n\202\305\202\315\201A\202\302\202\254\215s\202\253\202\334\201[\202\267\201I";

const void *D_08a41230[] = {
    (const void *)(D_0805f624),
    (const void *)(D_0805f5b8),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_0805f560),
};

const void *D_08a41240[] = {
    (const void *)(D_0805f670),
    (const void *)(D_0805f5b8),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_0805f648),
};

const void *D_08a41250[] = {
    (const void *)(D_0805f6ec),
    (const void *)(D_0805f5b8),
    (const void *)(&s_warai_little_seqData),
    (const void *)(D_0805f6ac),
};

const void *D_08a41260[] = {
    (const void *)(D_0805f6ec),
    (const void *)(D_0805f770),
    (const void *)(&s_warai_seqData),
    (const void *)(D_0805f740),
};

const void *D_08a41270[] = {
    (const void *)(D_0805f6ec),
    (const void *)(D_0805f840),
    (const void *)(&s_kansei_solo_seqData),
    (const void *)(D_0805f7f4),
};

const void *D_08a41280[] = {
    (const void *)(D_0805f6ec),
    (const void *)(D_0805f918),
    (const void *)(&s_kansei_seqData),
    (const void *)(D_0805f8dc),
};

const struct Beatscript script_drum_lesson_short_4_main[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(116) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(4) },
    { 0x04, (0x08), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, (0x09), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x02), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a41230) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a41240) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a41250) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x10), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805f9cc) },
    { 0x04, (0x0D), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x15), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x16), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805fa10) },
    { 0x04, (0x0D), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x15), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x16), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805fa60) },
    { 0x04, (0x0D), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x15), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x16), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a41260) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a41270) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a41280) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, (0x10), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)((4)) },
    { 0x04, (0x12), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, (0x14), (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
