/* Generated by tools/bs2c.py from games/drum_studio/drum_lesson_long_3.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "games/drum_studio/drum_lessons_text.h"
#include "include/engines/drum_studio.h"
#include "include/sequence_data.h"
#include "src/code_08047e50.h"
#include "src/scenes/riq_main_scene.h"

extern char drum_lessons_sub_08a7d7a0[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern const struct Beatscript script_drum_lesson_long_3_entry[];
extern const struct SubScene sub_scene_drum_lesson_long_3;
extern struct Scene scene_drum_lesson_long_3;
extern const char D_08063308[];
extern const struct Beatscript D_08063360[];
extern const struct Beatscript D_08063414[];
extern const char D_08063438[];
extern const struct Beatscript D_08063468[];
extern const char D_0806354c[];
extern const struct Beatscript D_0806358c[];
extern const char D_080635bc[];
extern const struct Beatscript D_08063600[];
extern const char D_08063708[];
extern const struct Beatscript D_08063744[];
extern const char D_08063870[];
extern const struct Beatscript D_080638a8[];
extern const struct Beatscript script_drum_lesson_long_3_main[];

const struct Beatscript script_drum_lesson_long_3_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 4, (const void *)(gameplay_set_current_engine), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_lesson_long_3_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_lesson_long_3 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_lesson_long_3_entry,
};

struct Scene scene_drum_lesson_long_3 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_lesson_long_3),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const char D_08063308[] = "\202\346\202\255\202\253\202\242\202\304\203}\203l\202\265\202\304\202\313\201B\n\215D\202\253\202\310\203^\203C\203~\203\223\203O\202\305\202\307\202\244\202\274\201B\n\211\211\221t\202\360\216~\202\337\202\351\202\306\201A\n\202\250\216\350\226{\202\252\202\253\202\257\202\351\203\210\201I";

const struct Beatscript D_08063360[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript D_08063414[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(21) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08063438[] = "\n\203X\203l\203A\203h\203\211\203\200\202\360\n\202\251\202\263\202\313\202\304\202\335\202\351\203l\201I\n\203m\203\212\203m\203\212\202\276\203\210\201I";

const struct Beatscript D_08063468[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_0806354c[] = "\n\203V\203\223\203o\203\213\202\305\203L\203b\203`\203\212\202\306\n\202\334\202\306\202\337\202\304\202\250\202\261\202\244\203l\201I\n\202\261\202\352\202\315\201A\202\305\202\253\202\351\202\346\203l\201H\n";

const struct Beatscript D_0806358c[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_CRASH) },
    { 0x00, 0, NULL, (uintptr_t)(21) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_080635bc[] = "\203X\203l\203A\202\314\203p\203^\201[\203\223\202\360\n\202\277\202\345\202\301\202\306\202\251\202\246\202\351\203l\201B\n\202\305\202\253\202\351\202\306\212y\202\265\202\242\203\210\201I\n\202\253\202\301\202\306\201B\n";

const struct Beatscript D_08063600[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08063708[] = "\n\202P\202\302\202\276\202\257\201A\211\271\202\252\202\323\202\246\202\351\203\210\201B\n\202\242\202\252\202\242\202\306\203\200\203Y\202\242\201I\201I\n\202\252\202\361\202\316\202\301\202\304\203l\201I";

const struct Beatscript D_08063744[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const char D_08063870[] = "\n\202\334\202\275\202\334\202\275\202P\202\302\201A\n\211\271\202\252\202\323\202\246\202\351\203\210\201I\n\202\305\202\253\202\275\202\347\203J\203b\203R\202\346\202\267\202\254\201I";

const struct Beatscript D_080638a8[] = {
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_KICK_R) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_SNARE_L) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const void *D_08a42ea0[] = {
    (const void *)(D_08063414),
    (const void *)(D_08063360),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_08063308),
};

const void *D_08a42eb0[] = {
    (const void *)(D_08063414),
    (const void *)(D_08063468),
    (const void *)(&s_hakushu_solo_seqData),
    (const void *)(D_08063438),
};

const void *D_08a42ec0[] = {
    (const void *)(D_0806358c),
    (const void *)(D_08063468),
    (const void *)(&s_warai_little_seqData),
    (const void *)(D_0806354c),
};

const void *D_08a42ed0[] = {
    (const void *)(D_0806358c),
    (const void *)(D_08063600),
    (const void *)(&s_warai_seqData),
    (const void *)(D_080635bc),
};

const void *D_08a42ee0[] = {
    (const void *)(D_0806358c),
    (const void *)(D_08063744),
    (const void *)(&s_kansei_solo_seqData),
    (const void *)(D_08063708),
};

const void *D_08a42ef0[] = {
    (const void *)(D_0806358c),
    (const void *)(D_080638a8),
    (const void *)(&s_kansei_seqData),
    (const void *)(D_08063870),
};

const struct Beatscript script_drum_lesson_long_3_main[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(4) },
    { 0x04, EVENT_08, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_09, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a42ea0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a42eb0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a42ec0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a42ed0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a42ee0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(drum_lesson_script_import_pattern), (uintptr_t)(D_08a42ef0) },
    { 0x0D, 0, (const void *)(drum_lessons_sub_08a7d7a0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, SHOW_DIALOGUE, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TEACHER_EXP_GIVE_RANK) },
    { 0x04, SET_TEACHER_EMOTE, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, GET_LESSON_SCORE, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
