/* Generated by tools/bs2c.py from games/drum_studio/subroutines.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/engines/drum_studio.h"
#include "include/sequence_data.h"
#include "src/code_08047e50.h"

extern char x00[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char xB0[];   /* undeclared in any header */
extern const struct Beatscript drum_lessons_sub_08a7d7a0[];

const struct Beatscript drum_lessons_sub_08a7d7a0[] = {
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_0F, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0xB0, 0, NULL, (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_drum_lesson_bgm_seqData) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_17, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_07, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_0A, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_0B, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_18, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_0F, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0xB0, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_18, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_0F, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0xB0, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_0C, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(scene_stop_music), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(drum_lesson_script_end_pattern), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(NULL) },
    { 0x04, SET_DIALOGUE_TEXT, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_07, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_13, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TEACHER_EXP_POSITIVE) },
    { 0x04, SET_TEACHER_EMOTE, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_17, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_13, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TEACHER_EXP_DRUM) },
    { 0x04, SET_TEACHER_EMOTE, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_11, (const void *)(gameplay_run_engine_event), (uintptr_t)(&drum_studio_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
