/* Generated by tools/bs2c.py from data/scenes/cafe/script.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/sequence_data.h"
#include "src/code_080068f8.h"
#include "src/scenes/cafe.h"
#include "src/scenes/riq_main_scene.h"

extern char cafe_bg_map[];   /* undeclared in any header */
extern char cafe_bg_map_cheer_1[];   /* undeclared in any header */
extern char cafe_bg_map_cheer_2[];   /* undeclared in any header */
extern char cafe_bg_map_clap_1[];   /* undeclared in any header */
extern char cafe_bg_map_clap_2[];   /* undeclared in any header */
extern char cafe_bg_map_helping_1[];   /* undeclared in any header */
extern char cafe_bg_map_helping_2[];   /* undeclared in any header */
extern char cafe_bg_map_helping_3[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x09[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x1A[];   /* undeclared in any header */
extern char x1B[];   /* undeclared in any header */
extern char x1C[];   /* undeclared in any header */
extern char x1D[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x29[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x4F[];   /* undeclared in any header */
extern char x828[];   /* undeclared in any header */
extern const struct Beatscript script_scene_cafe[];
extern const struct SubScene sub_scene_cafe;
extern struct Scene scene_cafe;

const struct Beatscript script_scene_cafe[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(118) },
    { 0x03, 0, (const void *)(set_pause_beatscript_scene), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_counseling_bgm_seqData) },
    { 0x03, 0, (const void *)(func_08007324), (uintptr_t)(TRUE) },
    { 0x4A, 0, (const void *)(32), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x09, INT8, NULL, (uintptr_t)(TRUE) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(cafe_print_dialogue), (uintptr_t)(0) },
    { 0x1A, FUNC, NULL, (uintptr_t)(cafe_get_dialogue_hold_time) },
    { 0x1C, 0, NULL, (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_start_dialogue_inputs), (uintptr_t)(0) },
    { 0x1D, 0, NULL, (uintptr_t)(0) },
    { 0x1C, 0, NULL, (uintptr_t)(8) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(7) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(5) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(4) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(3) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(2) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1C, 0, NULL, (uintptr_t)(1) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x1D, 0, NULL, (uintptr_t)(0) },
    { 0x1B, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(cafe_clear_dialogue), (uintptr_t)(0) },
    { 0x1A, FUNC, NULL, (uintptr_t)(cafe_get_bg_event) },
    { 0x1C, 0, NULL, (uintptr_t)(1) },
    { 0x29, 0, NULL, (uintptr_t)(&s_hakushu_solo_seqData) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_clap_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x1D, 0, NULL, (uintptr_t)(0) },
    { 0x1C, 0, NULL, (uintptr_t)(2) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_helping_1) },
    { 0x00, 0, NULL, (uintptr_t)(72) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_helping_2) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x29, 0, NULL, (uintptr_t)(&s_toss_red_red_seqData) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_helping_3) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_helping_1) },
    { 0x00, 0, NULL, (uintptr_t)(72) },
    { 0x1D, 0, NULL, (uintptr_t)(0) },
    { 0x1C, 0, NULL, (uintptr_t)(3) },
    { 0x29, 0, NULL, (uintptr_t)(&s_kansei_seqData) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map_cheer_2) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x1D, 0, NULL, (uintptr_t)(0) },
    { 0x4F, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(cafe_load_bg_event_map), (uintptr_t)(cafe_bg_map) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x1B, 0, NULL, (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x09, INT8, NULL, (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(scene_hide_bg_layer), (uintptr_t)(TRUE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_cafe = {
    /* start  */ (void (*)())cafe_scene_start, 0,
    /* paused */ (void (*)())cafe_scene_paused, 0,
    /* update */ (void (*)())cafe_scene_update, 0,
    /* stop   */ (void (*)())cafe_scene_stop, 0,
    /* script */ script_scene_cafe,
};

struct Scene scene_cafe = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_cafe),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(0),
    /* end    */ (void (*)())NULL, (void *)(0),
    /* memory */ 0x828,
};
