/* Generated by tools/bs2c.py from games/marching_orders/marching_orders_2.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/prologues/marching_orders_2.h"
#include "include/sequence_data.h"
#include "src/code_080068f8.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805c8f4[];   /* undeclared in any header */
extern char D_0805c910[];   /* undeclared in any header */
extern char D_0805c92c[];   /* undeclared in any header */
extern char D_0805c948[];   /* undeclared in any header */
extern char D_0805c964[];   /* undeclared in any header */
extern char D_0805c984[];   /* undeclared in any header */
extern char D_0805c9a0[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char marching_orders_2_prologue_engine[];   /* undeclared in any header */
extern char marching_orders_2_sub_08a83cc8[];   /* undeclared in any header */
extern char marching_orders_2_sub_08a83ea8[];   /* undeclared in any header */
extern char marching_orders_2_sub_08a84088[];   /* undeclared in any header */
extern char marching_orders_2_sub_08a84268[];   /* undeclared in any header */
extern char marching_orders_2_sub_08a84610[];   /* undeclared in any header */
extern char marching_orders_2_sub_08a847d8[];   /* undeclared in any header */
extern char marching_orders_engine[];   /* undeclared in any header */
extern char marching_orders_sub_08a83758[];   /* undeclared in any header */
extern char marching_orders_sub_08a83848[];   /* undeclared in any header */
extern char marching_orders_sub_08a8386c[];   /* undeclared in any header */
extern char marching_orders_sub_08a83998[];   /* undeclared in any header */
extern char marching_orders_sub_08a83b24[];   /* undeclared in any header */
extern char marching_orders_sub_08a83bfc[];   /* undeclared in any header */
extern char marching_orders_sub_08a84448[];   /* undeclared in any header */
extern char marching_orders_sub_08a8452c[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x29[];   /* undeclared in any header */
extern char x33[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x4C[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern char x80[];   /* undeclared in any header */
extern char x99[];   /* undeclared in any header */
extern const struct Beatscript script_marching_orders_2_entry[];
extern const struct SubScene sub_scene_marching_orders_2;
extern struct Scene scene_marching_orders_2;
extern const struct Beatscript script_marching_orders_2_prologue[];
extern const struct MarkingCriteria marching_orders_2_marking_criteria_0;
extern const struct MarkingCriteria marching_orders_2_marking_criteria_1;
extern const struct MarkingCriteria marching_orders_2_marking_criteria_2;
extern const struct MarkingCriteria *marching_orders_2_marking_criteria[];
extern const struct Beatscript script_marching_orders_2_main[];

const struct Beatscript script_marching_orders_2_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(script_marching_orders_2_prologue), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x04, 3, (const void *)(gameplay_set_current_engine), (uintptr_t)(marching_orders_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_marching_orders_2_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_marching_orders_2 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_marching_orders_2_entry,
};

struct Scene scene_marching_orders_2 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_marching_orders_2),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_marching_orders_2_prologue[] = {
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(8) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(marching_orders_2_prologue_engine) },
    { 0x03, 0, (const void *)(stop_all_soundplayers), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x29, 0, NULL, (uintptr_t)(&s_jingle_march_seqData) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(1) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(2) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(3) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(4) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(5) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08046408), (uintptr_t)(7) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08006d80), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct MarkingCriteria marching_orders_2_marking_criteria_0 = {
    /* positive */ D_0805c910,
    /* negative */ D_0805c8f4,
    /* flags    */ (CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x80,
    /* minHitsBeforeFail   */ 0x33,
    /* maxMissesBeforeFail */ 0x4C,
};

const struct MarkingCriteria marching_orders_2_marking_criteria_1 = {
    /* positive */ D_0805c948,
    /* negative */ D_0805c92c,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x80,
    /* minHitsBeforeFail   */ 0x33,
    /* maxMissesBeforeFail */ 0x99,
};

const struct MarkingCriteria marching_orders_2_marking_criteria_2 = {
    /* positive */ D_0805c984,
    /* negative */ D_0805c964,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x80,
    /* minHitsBeforeFail   */ 0x33,
    /* maxMissesBeforeFail */ 0x80,
};

const struct MarkingCriteria *marching_orders_2_marking_criteria[] = {
    (const struct MarkingCriteria *)(&marching_orders_2_marking_criteria_0),
    (const struct MarkingCriteria *)(&marching_orders_2_marking_criteria_1),
    (const struct MarkingCriteria *)(&marching_orders_2_marking_criteria_2),
    (const struct MarkingCriteria *)(NULL),
};

const struct Beatscript script_marching_orders_2_main[] = {
    { 0x03, 0, (const void *)(results_set_header), (uintptr_t)(D_0805c9a0) },
    { 0x03, 0, (const void *)(results_import_marking_criteria), (uintptr_t)(marching_orders_2_marking_criteria) },
    { 0x03, 0, (const void *)(gameplay_set_mercy_count), (uintptr_t)(1) },
    { 0x03, 0, (const void *)(gameplay_start_perfect_campaign), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(135) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_guntai2_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83998), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83998), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a84448), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83998), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8452c), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83998), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8452c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84610), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83998), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a84448), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84610), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8452c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84610), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83758), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84610), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a83cc8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a83ea8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84088), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84268), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a83cc8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84088), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83b24), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83bfc), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a84448), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a847d8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(marching_orders_2_sub_08a84610), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a83848), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(marching_orders_sub_08a8386c), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x29, 0, NULL, (uintptr_t)(&s_guntai_foot1_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_check_for_perfect), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(7) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x29, 0, NULL, (uintptr_t)(&s_guntai_foot2_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x29, 0, NULL, (uintptr_t)(&s_guntai_foot1_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(7) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x29, 0, NULL, (uintptr_t)(&s_guntai_foot2_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(marching_orders_engine) },
    { 0x29, 0, NULL, (uintptr_t)(&s_guntai_foot1_seqData) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
