/* Generated by tools/bs2c.py from games/metronome/metronome.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805ccc8[];   /* undeclared in any header */
extern char D_0805cce4[];   /* undeclared in any header */
extern char D_0805cd04[];   /* undeclared in any header */
extern char D_0805cd24[];   /* undeclared in any header */
extern char D_0805cd44[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char metronome_engine[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x50[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern const struct Beatscript script_metronome_entry[];
extern const struct SubScene sub_scene_metronome;
extern struct Scene scene_metronome;
extern const struct Beatscript metronome_sub_08a19850[];
extern const struct Beatscript metronome_sub_08a19904[];
extern const struct Beatscript metronome_sub_08a199b8[];
extern const struct Beatscript script_metronome_main[];

const struct Beatscript script_metronome_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_metronome_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_metronome = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_metronome_entry,
};

struct Scene scene_metronome = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_metronome),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript metronome_sub_08a19850[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript metronome_sub_08a19904[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript metronome_sub_08a199b8[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const u16 metronome_grade_thresholds[] = { 990, 960, 880, 700 };

const void *metronome_grade_comments[] = {
    (const void *)(D_0805cd44),
    (const void *)(D_0805cd24),
    (const void *)(D_0805cd04),
    (const void *)(D_0805cce4),
    (const void *)(D_0805ccc8),
};

const struct Beatscript script_metronome_main[] = {
    { 0x03, 0, (const void *)(score_results_set_grade_thresholds), (uintptr_t)(metronome_grade_thresholds) },
    { 0x03, 0, (const void *)(score_results_set_grade_comments), (uintptr_t)(metronome_grade_comments) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_assess_irrelevant_inputs), (uintptr_t)(FALSE) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(1) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(gameplay_assess_irrelevant_inputs), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x50, 0, NULL, (uintptr_t)(192) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19904), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19904), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19904), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19904), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19904), (uintptr_t)(0) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a199b8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(metronome_engine) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_assess_irrelevant_inputs), (uintptr_t)(FALSE) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(-1) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(metronome_sub_08a19850), (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
