/* Generated by tools/bs2c.py from games/bouncy_road/bouncy_road.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/prologues/bouncy_road.h"
#include "include/sequence_data.h"
#include "src/code_080068f8.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805b784[];   /* undeclared in any header */
extern char D_0805b7a0[];   /* undeclared in any header */
extern char D_0805b7a4[];   /* undeclared in any header */
extern char D_0805b7cc[];   /* undeclared in any header */
extern char D_0805b7f8[];   /* undeclared in any header */
extern char D_0805b810[];   /* undeclared in any header */
extern char bouncy_road_engine[];   /* undeclared in any header */
extern char bouncy_road_prologue_engine[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x0F[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x100[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x29[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x4C[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern char x66[];   /* undeclared in any header */
extern char x80[];   /* undeclared in any header */
extern char xB3[];   /* undeclared in any header */
extern const struct Beatscript script_bouncy_road_entry[];
extern const struct SubScene sub_scene_bouncy_road;
extern struct Scene scene_bouncy_road;
extern const struct Beatscript script_bouncy_road_skipped_practice_entry[];
extern const struct SubScene sub_scene_bouncy_road_skipped_practice;
extern struct Scene scene_bouncy_road_skipped_practice;
extern const struct Beatscript script_bouncy_road_prologue[];
extern const struct MarkingCriteria bouncy_road_marking_criteria_0;
extern const struct MarkingCriteria bouncy_road_marking_criteria_1;
extern const struct MarkingCriteria bouncy_road_marking_criteria_2;
extern const struct MarkingCriteria *bouncy_road_marking_criteria[];
extern const struct Beatscript script_bouncy_road_main[];
extern const struct Beatscript script_bouncy_road_practice[];
extern const struct Beatscript script_bouncy_road_skipped_practice[];

const struct Beatscript script_bouncy_road_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(script_bouncy_road_prologue), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_bouncy_road_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_bouncy_road = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_bouncy_road_entry,
};

struct Scene scene_bouncy_road = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_bouncy_road),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_bouncy_road_skipped_practice_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_bouncy_road_skipped_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_bouncy_road_skipped_practice = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_bouncy_road_skipped_practice_entry,
};

struct Scene scene_bouncy_road_skipped_practice = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_bouncy_road_skipped_practice),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_bouncy_road_prologue[] = {
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(8) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(bouncy_road_prologue_engine) },
    { 0x03, 0, (const void *)(stop_all_soundplayers), (uintptr_t)(0) },
    { 0x29, 0, NULL, (uintptr_t)(&s_jingle_poli_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(func_08045b94), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(func_08045b94), (uintptr_t)(1) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(func_08006d80), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct MarkingCriteria bouncy_road_marking_criteria_0 = {
    /* positive */ D_0805b7a0,
    /* negative */ D_0805b784,
    /* flags    */ (CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x00,
    /* minHitsBeforeFail   */ 0xB3,
    /* maxMissesBeforeFail */ 0x4C,
};

const struct MarkingCriteria bouncy_road_marking_criteria_1 = {
    /* positive */ D_0805b7cc,
    /* negative */ D_0805b7a4,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x80,
    /* minHitsBeforeFail   */ 0x00,
    /* maxMissesBeforeFail */ 0x66,
};

const struct MarkingCriteria bouncy_road_marking_criteria_2 = {
    /* positive */ D_0805b7f8,
    /* negative */ D_0805b7a0,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x66,
    /* minHitsBeforeFail   */ 0x00,
    /* maxMissesBeforeFail */ 0x100,
};

const struct MarkingCriteria *bouncy_road_marking_criteria[] = {
    (const struct MarkingCriteria *)(&bouncy_road_marking_criteria_0),
    (const struct MarkingCriteria *)(&bouncy_road_marking_criteria_1),
    (const struct MarkingCriteria *)(&bouncy_road_marking_criteria_2),
    (const struct MarkingCriteria *)(NULL),
};

const struct Beatscript script_bouncy_road_main[] = {
    { 0x03, 0, (const void *)(results_set_header), (uintptr_t)(D_0805b810) },
    { 0x03, 0, (const void *)(results_import_marking_criteria), (uintptr_t)(bouncy_road_marking_criteria) },
    { 0x03, 0, (const void *)(gameplay_set_mercy_count), (uintptr_t)(1) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(155) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_emanikanto_bgm_seqData) },
    { 0x03, 0, (const void *)(gameplay_start_perfect_campaign), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((8 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((8 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((8 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((8 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, PLAY_DISTANT_BOUNCE_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(256) },
    { 0x00, 0, NULL, (uintptr_t)(64) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, PLAY_DISTANT_BOUNCE_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(256) },
    { 0x00, 0, NULL, (uintptr_t)(64) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(24) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((6 * 24)) },
    { 0x00, 0, NULL, (uintptr_t)((7 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((7 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((6 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((7 * 24)) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(189) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_check_for_perfect), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_bouncy_road_practice[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(160) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(&scene_bouncy_road_skipped_practice) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_f_even_road_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_reset_loop_counter), (uintptr_t)(0) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(beatscript_disable_loops), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(24) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((12 * 24)) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_f_even_road_seqData) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x03, 0, (const void *)(gameplay_increment_loop_counter), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_reset_loop_counter), (uintptr_t)(0) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(beatscript_disable_loops), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(24) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(24) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((12 * 24)) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_f_even_road_seqData) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x03, 0, (const void *)(gameplay_increment_loop_counter), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_reset_loop_counter), (uintptr_t)(0) },
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(beatscript_disable_loops), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((8 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_f_even_road_seqData) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x03, 0, (const void *)(gameplay_increment_loop_counter), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(NULL) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_bouncy_road_main), (uintptr_t)(0) },
};

const struct Beatscript script_bouncy_road_skipped_practice[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(160) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_bouncy_road_main), (uintptr_t)(0) },
};
