/* Generated by tools/bs2c.py from games/bouncy_road/bouncy_road_unused_2.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/sequence_data.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805b778[];   /* undeclared in any header */
extern char bouncy_road_engine[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern const struct Beatscript script_bouncy_road_unused_2_entry[];
extern const struct SubScene sub_scene_bouncy_road_unused_2;
extern struct Scene scene_bouncy_road_unused_2;
extern const struct Beatscript script_bouncy_road_unused_2_wait4[];
extern const struct Beatscript script_bouncy_road_unused_2_main[];

const struct Beatscript script_bouncy_road_unused_2_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_bouncy_road_unused_2 = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_bouncy_road_unused_2_entry,
};

struct Scene scene_bouncy_road_unused_2 = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_bouncy_road_unused_2),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_bouncy_road_unused_2_wait4[] = {
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_bouncy_road_unused_2_main[] = {
    { 0x03, 0, (const void *)(results_set_header), (uintptr_t)(D_0805b778) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_f_even_road_seqData) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_wait4), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(24) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_wait4), (uintptr_t)(0) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_f_even_road_seqData) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_wait4), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(16) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_wait4), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(24) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_wait4), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(script_bouncy_road_unused_2_wait4), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(6) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, ENABLE_BALL_GOAL_SFX, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(6) },
    { 0x04, DEPLOY_BALL, (const void *)(gameplay_run_engine_event), (uintptr_t)(bouncy_road_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
