/* Generated by tools/bs2c.py from games/drum_intro/drum_intro_unused.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/scenes.h"
#include "include/sequence_data.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805d438[];   /* undeclared in any header */
extern char D_0805d458[];   /* undeclared in any header */
extern char D_0805d4b4[];   /* undeclared in any header */
extern char D_0805d508[];   /* undeclared in any header */
extern char D_0805d554[];   /* undeclared in any header */
extern char D_0805d568[];   /* undeclared in any header */
extern char D_0805d57c[];   /* undeclared in any header */
extern char D_0805d5a4[];   /* undeclared in any header */
extern char D_0805d5ec[];   /* undeclared in any header */
extern char drum_intro_engine[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x29[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x50[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern const struct Beatscript script_drum_intro_unused_entry[];
extern const struct SubScene sub_scene_drum_intro_unused;
extern struct Scene scene_drum_intro_unused;
extern const struct Beatscript drum_intro_unused_sub_08a21294[];
extern const struct Beatscript drum_intro_unused_sub_08a21390[];
extern const struct Beatscript drum_intro_unused_sub_08a213d8[];
extern const struct Beatscript drum_intro_unused_sub_08a213fc[];
extern const struct Beatscript drum_intro_unused_sub_08a214ec[];
extern const struct Beatscript drum_intro_unused_sub_08a21600[];
extern const struct Beatscript script_drum_intro_unused_main[];

const struct Beatscript script_drum_intro_unused_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_drum_intro_unused_main), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_drum_intro_unused = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_drum_intro_unused_entry,
};

struct Scene scene_drum_intro_unused = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_drum_intro_unused),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript drum_intro_unused_sub_08a21294[] = {
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_one_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_two_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_a_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_one_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_two_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(23) },
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_three_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(1) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(20) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript drum_intro_unused_sub_08a21390[] = {
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a21294), (uintptr_t)(0) },
    { 0x29, 0, NULL, (uintptr_t)(&s_intro_four_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(4) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript drum_intro_unused_sub_08a213d8[] = {
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a21294), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(28) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript drum_intro_unused_sub_08a213fc[] = {
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript drum_intro_unused_sub_08a214ec[] = {
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(65) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript drum_intro_unused_sub_08a21600[] = {
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(258) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(64) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(544) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(544) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(5) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(3) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(128) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(4) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(32) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(16) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(258) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_drum_intro_unused_main[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(0) },
    { 0x50, 0, (const void *)(256), (uintptr_t)(192) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d438) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d458) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d4b4) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d508) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x50, 0, NULL, (uintptr_t)(96) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d554) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(130) },
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a21390), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a213fc), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a213fc), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a214ec), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a21600), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(8) },
    { 0x04, 1, (const void *)(gameplay_set_current_engine), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(TRUE) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d568) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(NULL) },
    { 0x00, 0, NULL, (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(drum_intro_unused_sub_08a213d8), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(FALSE) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)((4 * 24)) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d57c) },
    { 0x00, 0, NULL, (uintptr_t)((5 * 24)) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(NULL) },
    { 0x00, 0, NULL, (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(8) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x50, 0, (const void *)(256), (uintptr_t)(192) },
    { 0x00, 0, NULL, (uintptr_t)(48) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d5a4) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x03, 0, (const void *)(gameplay_display_text), (uintptr_t)(D_0805d5ec) },
    { 0x03, 0, (const void *)(gameplay_display_text_and_wait), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(drum_intro_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(set_next_scene), (uintptr_t)(&scene_game_select) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};
