/* Generated by tools/bs2c.py from the .inc files — do not edit.
 * The .bs sources use assembler .set constants; the PC build needs them as C. */
#pragma once

#ifndef GLOBAL_VARIABLE
#define GLOBAL_VARIABLE (((uintptr_t)&D_030053c0 + 0x24))
#endif
#ifndef A_BUTTON
#define A_BUTTON ((1 << 0))
#endif
#ifndef B_BUTTON
#define B_BUTTON ((1 << 1))
#endif
#ifndef SELECT_BUTTON
#define SELECT_BUTTON ((1 << 2))
#endif
#ifndef START_BUTTON
#define START_BUTTON ((1 << 3))
#endif
#ifndef DPAD_RIGHT
#define DPAD_RIGHT ((1 << 4))
#endif
#ifndef DPAD_LEFT
#define DPAD_LEFT ((1 << 5))
#endif
#ifndef DPAD_UP
#define DPAD_UP ((1 << 6))
#endif
#ifndef DPAD_DOWN
#define DPAD_DOWN ((1 << 7))
#endif
#ifndef RIGHT_SHOULDER_BUTTON
#define RIGHT_SHOULDER_BUTTON ((1 << 8))
#endif
#ifndef LEFT_SHOULDER_BUTTON
#define LEFT_SHOULDER_BUTTON ((1 << 9))
#endif
#ifndef DPAD_ALL
#define DPAD_ALL ((DPAD_RIGHT | DPAD_LEFT | DPAD_UP | DPAD_DOWN))
#endif
#ifndef DPAD_ANY
#define DPAD_ANY ((DPAD_ALL))
#endif
#ifndef INT8
#define INT8 (0)
#endif
#ifndef INT16
#define INT16 (1)
#endif
#ifndef INT32
#define INT32 (2)
#endif
#ifndef FUNC
#define FUNC (3)
#endif
#ifndef CHECK_AVERAGE_MISSES
#define CHECK_AVERAGE_MISSES (0x100)
#endif
#ifndef OVERRIDE_COMMENTS
#define OVERRIDE_COMMENTS (0x80)
#endif
#ifndef CHECK_AVERAGE_HITS
#define CHECK_AVERAGE_HITS (0x1)
#endif
#ifndef END_OF_CRITERIA
#define END_OF_CRITERIA (NULL)
#endif
#ifndef MUSIC_PLAYER_0
#define MUSIC_PLAYER_0 (0)
#endif
#ifndef MUSIC_PLAYER_1
#define MUSIC_PLAYER_1 (1)
#endif
#ifndef MUSIC_PLAYER_2
#define MUSIC_PLAYER_2 (2)
#endif
#ifndef SFX_PLAYER_0
#define SFX_PLAYER_0 (3)
#endif
#ifndef SFX_PLAYER_1
#define SFX_PLAYER_1 (4)
#endif
#ifndef SFX_PLAYER_2
#define SFX_PLAYER_2 (5)
#endif
#ifndef SFX_PLAYER_3
#define SFX_PLAYER_3 (6)
#endif
#ifndef SFX_PLAYER_4
#define SFX_PLAYER_4 (7)
#endif
#ifndef SFX_PLAYER_5
#define SFX_PLAYER_5 (8)
#endif
#ifndef SFX_PLAYER_6
#define SFX_PLAYER_6 (9)
#endif
#ifndef SFX_PLAYER_7
#define SFX_PLAYER_7 (10)
#endif
#ifndef SFX_PLAYER_8
#define SFX_PLAYER_8 (11)
#endif
#ifndef SFX_PLAYER_9
#define SFX_PLAYER_9 (12)
#endif
#ifndef DEFAULT_SOUND_PLAYER
#define DEFAULT_SOUND_PLAYER (255)
#endif
#ifndef MIDI_TRACK_0
#define MIDI_TRACK_0 ((1 << 0))
#endif
#ifndef MIDI_TRACK_1
#define MIDI_TRACK_1 ((1 << 1))
#endif
#ifndef MIDI_TRACK_2
#define MIDI_TRACK_2 ((1 << 2))
#endif
#ifndef MIDI_TRACK_3
#define MIDI_TRACK_3 ((1 << 3))
#endif
#ifndef MIDI_TRACK_4
#define MIDI_TRACK_4 ((1 << 4))
#endif
#ifndef MIDI_TRACK_5
#define MIDI_TRACK_5 ((1 << 5))
#endif
#ifndef MIDI_TRACK_6
#define MIDI_TRACK_6 ((1 << 6))
#endif
#ifndef MIDI_TRACK_7
#define MIDI_TRACK_7 ((1 << 7))
#endif
#ifndef MIDI_TRACK_8
#define MIDI_TRACK_8 ((1 << 8))
#endif
#ifndef MIDI_TRACK_9
#define MIDI_TRACK_9 ((1 << 9))
#endif
#ifndef MIDI_TRACK_10
#define MIDI_TRACK_10 ((1 << 10))
#endif
#ifndef MIDI_TRACK_11
#define MIDI_TRACK_11 ((1 << 11))
#endif
#ifndef MIDI_TRACK_12
#define MIDI_TRACK_12 ((1 << 12))
#endif
#ifndef MIDI_TRACK_13
#define MIDI_TRACK_13 ((1 << 13))
#endif
#ifndef MIDI_TRACK_14
#define MIDI_TRACK_14 ((1 << 14))
#endif
#ifndef MIDI_TRACK_15
#define MIDI_TRACK_15 ((1 << 15))
#endif
#ifndef BLACK
#define BLACK (0x0000)
#endif
#ifndef WHITE
#define WHITE (0x7FFF)
#endif
#ifndef GBA_HEADER
#define GBA_HEADER (0)
#endif
#ifndef BIOSROMBase
#define BIOSROMBase (0x00000000)
#endif
#ifndef ExternWorkRAMBase
#define ExternWorkRAMBase (0x02000000)
#endif
#ifndef InternWorkRAMBase
#define InternWorkRAMBase (0x03000000)
#endif
#ifndef IORAMBase
#define IORAMBase (0x04000000)
#endif
#ifndef PaletteRAMBase
#define PaletteRAMBase (0x05000000)
#endif
#ifndef VRAMBase
#define VRAMBase (0x06000000)
#endif
#ifndef OAMBase
#define OAMBase (0x07000000)
#endif
#ifndef GameROMBase
#define GameROMBase (0x08000000)
#endif
#ifndef GameROMImage1Base
#define GameROMImage1Base (0x0A000000)
#endif
#ifndef GameROMImage2Base
#define GameROMImage2Base (0x0C000000)
#endif
#ifndef CartRAMBase
#define CartRAMBase (0x0E000000)
#endif
#ifndef D_03007F00
#define D_03007F00 (InternWorkRAMBase + 0x7F00)
#endif
#ifndef D_03007FA0
#define D_03007FA0 (InternWorkRAMBase + 0x7FA0)
#endif
#ifndef REG_INTERRUPT
#define REG_INTERRUPT (InternWorkRAMBase + 0x7FFC)
#endif
#ifndef REG_SOUNDCNT_X
#define REG_SOUNDCNT_X (IORAMBase + 0x84)
#endif
#ifndef REG_DMA3SAD
#define REG_DMA3SAD (IORAMBase + 0xD4)
#endif
#ifndef INTERRUPT_VBLANK
#define INTERRUPT_VBLANK ((1 << 0))
#endif
#ifndef INTERRUPT_HBLANK
#define INTERRUPT_HBLANK ((1 << 1))
#endif
#ifndef INTERRUPT_VCOUNT
#define INTERRUPT_VCOUNT ((1 << 2))
#endif
#ifndef INTERRUPT_TIMER0
#define INTERRUPT_TIMER0 ((1 << 3))
#endif
#ifndef INTERRUPT_TIMER1
#define INTERRUPT_TIMER1 ((1 << 4))
#endif
#ifndef INTERRUPT_TIMER2
#define INTERRUPT_TIMER2 ((1 << 5))
#endif
#ifndef INTERRUPT_TIMER3
#define INTERRUPT_TIMER3 ((1 << 6))
#endif
#ifndef INTERRUPT_COMM
#define INTERRUPT_COMM ((1 << 7))
#endif
#ifndef INTERRUPT_DMA0
#define INTERRUPT_DMA0 ((1 << 8))
#endif
#ifndef INTERRUPT_DMA1
#define INTERRUPT_DMA1 ((1 << 9))
#endif
#ifndef INTERRUPT_DMA2
#define INTERRUPT_DMA2 ((1 << 10))
#endif
#ifndef INTERRUPT_DMA3
#define INTERRUPT_DMA3 ((1 << 11))
#endif
#ifndef INTERRUPT_BUTTON
#define INTERRUPT_BUTTON ((1 << 12))
#endif
#ifndef INTERRUPT_CART
#define INTERRUPT_CART ((1 << 13))
#endif
#ifndef REG_IE
#define REG_IE (IORAMBase + 0x200)
#endif
#ifndef REG_IMC
#define REG_IMC (IORAMBase + 0x800)
#endif
#ifndef REG_SCD0
#define REG_SCD0 (IORAMBase + 0x120)
#endif
#ifndef REG_SCD1
#define REG_SCD1 (IORAMBase + 0x122)
#endif
#ifndef REG_SCD2
#define REG_SCD2 (IORAMBase + 0x124)
#endif
#ifndef REG_SCD3
#define REG_SCD3 (IORAMBase + 0x126)
#endif
#ifndef REG_SCCNT
#define REG_SCCNT (IORAMBase + 0x128)
#endif
#ifndef REG_SCCNT_L
#define REG_SCCNT_L (IORAMBase + 0x128)
#endif
#ifndef REG_SCCNT_H
#define REG_SCCNT_H (IORAMBase + 0x12A)
#endif
#ifndef SOUNDCNT1_SWEEP_NUM_SHIFTS_MASK
#define SOUNDCNT1_SWEEP_NUM_SHIFTS_MASK ((0x7 << 0))
#endif
#ifndef SOUNDCNT1_SWEEP_DECREASE
#define SOUNDCNT1_SWEEP_DECREASE ((1 << 3))
#endif
#ifndef SOUNDCNT1_SWEEP_DELAY_MASK
#define SOUNDCNT1_SWEEP_DELAY_MASK ((0x7 << 4))
#endif
#ifndef SOUNDCNTX_WAVE_DUTY_12_5_PERCENT
#define SOUNDCNTX_WAVE_DUTY_12_5_PERCENT (0)
#endif
#ifndef SOUNDCNTX_WAVE_DUTY_25_PERCENT
#define SOUNDCNTX_WAVE_DUTY_25_PERCENT (1)
#endif
#ifndef SOUNDCNTX_WAVE_DUTY_50_PERCENT
#define SOUNDCNTX_WAVE_DUTY_50_PERCENT (2)
#endif
#ifndef SOUNDCNTX_WAVE_DUTY_75_PERCENT
#define SOUNDCNTX_WAVE_DUTY_75_PERCENT (3)
#endif
#ifndef SOUNDCNTX_SOUND_LENGTH_MASK
#define SOUNDCNTX_SOUND_LENGTH_MASK ((0x3F << 0))
#endif
#ifndef SOUNDCNTX_WAVE_DUTY_MASK
#define SOUNDCNTX_WAVE_DUTY_MASK ((0x3 << 6))
#endif
#ifndef SOUNDCNTX_ENV_STEP_TIME_MASK
#define SOUNDCNTX_ENV_STEP_TIME_MASK ((0x7 << 8))
#endif
#ifndef SOUNDCNTX_ENV_MODE_INCREASE
#define SOUNDCNTX_ENV_MODE_INCREASE ((1 << 11))
#endif
#ifndef SOUNDCNTX_ENV_VALUE_MASK
#define SOUNDCNTX_ENV_VALUE_MASK ((0xF << 12))
#endif
#ifndef SOUNDCNTX_TIMED_SOUND
#define SOUNDCNTX_TIMED_SOUND ((1 << 14))
#endif
#ifndef SOUNDCNTX_SOUND_RESET
#define SOUNDCNTX_SOUND_RESET ((1 << 15))
#endif
#ifndef SOUNDCNTX_FREQUENCY_MASK
#define SOUNDCNTX_FREQUENCY_MASK ((0x7FF << 0))
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_2
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_2 (0)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1 (1)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_2
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_2 (2)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_3
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_3 (3)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_4
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_4 (4)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_5
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_5 (5)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_6
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_6 (6)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_7
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_1_7 (7)
#endif
#ifndef SOUNDCNT4_CLOCK_DIVIDE_FREQ_MASK
#define SOUNDCNT4_CLOCK_DIVIDE_FREQ_MASK ((0x7 << 0))
#endif
#ifndef SOUNDCNT4_COUNTER_STAGES
#define SOUNDCNT4_COUNTER_STAGES ((1 << 3))
#endif
#ifndef SOUNDCNT4_PRESTEPPER_FREQ_MASK
#define SOUNDCNT4_PRESTEPPER_FREQ_MASK ((0xF << 4))
#endif
#ifndef SOUNDCNT3_BANK_MODE
#define SOUNDCNT3_BANK_MODE ((1 << 5))
#endif
#ifndef SOUNDCNT3_BANK_SELECT
#define SOUNDCNT3_BANK_SELECT ((1 << 6))
#endif
#ifndef SOUNDCNT3_OUTPUT_ENABLE
#define SOUNDCNT3_OUTPUT_ENABLE ((1 << 7))
#endif
#ifndef SOUNDCNT3_VOLUME_MUTE
#define SOUNDCNT3_VOLUME_MUTE (0)
#endif
#ifndef SOUNDCNT3_VOLUME_100
#define SOUNDCNT3_VOLUME_100 (1)
#endif
#ifndef SOUNDCNT3_VOLUME_50
#define SOUNDCNT3_VOLUME_50 (2)
#endif
#ifndef SOUNDCNT3_VOLUME_25
#define SOUNDCNT3_VOLUME_25 (3)
#endif
#ifndef SOUNDCNT3_VOLUME_75
#define SOUNDCNT3_VOLUME_75 (4)
#endif
#ifndef SOUNDCNT3_SOUND_LENGTH_MASK
#define SOUNDCNT3_SOUND_LENGTH_MASK ((0xFF << 0))
#endif
#ifndef SOUNDCNT3_OUTPUT_VOLUME_MASK
#define SOUNDCNT3_OUTPUT_VOLUME_MASK ((0x7 << 13))
#endif
#ifndef REG_SOUND1CNT
#define REG_SOUND1CNT (IORAMBase + 0x60)
#endif
#ifndef REG_SOUND1CNT_L
#define REG_SOUND1CNT_L (IORAMBase + 0x60)
#endif
#ifndef REG_SOUND1CNT_H
#define REG_SOUND1CNT_H (IORAMBase + 0x62)
#endif
#ifndef REG_SOUND1CNT_X
#define REG_SOUND1CNT_X (IORAMBase + 0x64)
#endif
#ifndef REG_SOUND2CNT_L
#define REG_SOUND2CNT_L (IORAMBase + 0x68)
#endif
#ifndef REG_SOUND2CNT_H
#define REG_SOUND2CNT_H (IORAMBase + 0x6C)
#endif
#ifndef REG_SOUND3CNT
#define REG_SOUND3CNT (IORAMBase + 0x70)
#endif
#ifndef REG_SOUND3CNT_L
#define REG_SOUND3CNT_L (IORAMBase + 0x70)
#endif
#ifndef REG_SOUND3CNT_H
#define REG_SOUND3CNT_H (IORAMBase + 0x72)
#endif
#ifndef REG_SOUND3CNT_X
#define REG_SOUND3CNT_X (IORAMBase + 0x74)
#endif
#ifndef REG_SOUND4CNT_L
#define REG_SOUND4CNT_L (IORAMBase + 0x78)
#endif
#ifndef REG_SOUND4CNT_H
#define REG_SOUND4CNT_H (IORAMBase + 0x7C)
#endif
#ifndef SOUNDCNT_DMG_LEFT_VOLUME_MASK
#define SOUNDCNT_DMG_LEFT_VOLUME_MASK ((0x7 << 0))
#endif
#ifndef SOUNDCNT_VIN_LEFT_ENABLE
#define SOUNDCNT_VIN_LEFT_ENABLE ((1 << 3))
#endif
#ifndef SOUNDCNT_DMG_RIGHT_VOLUME_MASK
#define SOUNDCNT_DMG_RIGHT_VOLUME_MASK ((0x7 << 4))
#endif
#ifndef SOUNDCNT_VIN_RIGHT_ENABLE
#define SOUNDCNT_VIN_RIGHT_ENABLE ((1 << 7))
#endif
#ifndef SOUNDCNT_DMG_SOUND1_LEFT_ENABLE
#define SOUNDCNT_DMG_SOUND1_LEFT_ENABLE ((1 << 8))
#endif
#ifndef SOUNDCNT_DMG_SOUND2_LEFT_ENABLE
#define SOUNDCNT_DMG_SOUND2_LEFT_ENABLE ((1 << 9))
#endif
#ifndef SOUNDCNT_DMG_SOUND3_LEFT_ENABLE
#define SOUNDCNT_DMG_SOUND3_LEFT_ENABLE ((1 << 10))
#endif
#ifndef SOUNDCNT_DMG_SOUND4_LEFT_ENABLE
#define SOUNDCNT_DMG_SOUND4_LEFT_ENABLE ((1 << 11))
#endif
#ifndef SOUNDCNT_DMG_SOUND1_RIGHT_ENABLE
#define SOUNDCNT_DMG_SOUND1_RIGHT_ENABLE ((1 << 12))
#endif
#ifndef SOUNDCNT_DMG_SOUND2_RIGHT_ENABLE
#define SOUNDCNT_DMG_SOUND2_RIGHT_ENABLE ((1 << 13))
#endif
#ifndef SOUNDCNT_DMG_SOUND3_RIGHT_ENABLE
#define SOUNDCNT_DMG_SOUND3_RIGHT_ENABLE ((1 << 14))
#endif
#ifndef SOUNDCNT_DMG_SOUND4_RIGHT_ENABLE
#define SOUNDCNT_DMG_SOUND4_RIGHT_ENABLE ((1 << 15))
#endif
#ifndef REG_SOUNDCNT
#define REG_SOUNDCNT (IORAMBase + 0x80)
#endif
#ifndef REG_SOUNDCNT_L
#define REG_SOUNDCNT_L (IORAMBase + 0x80)
#endif
#ifndef SOUNDCNT_OUTPUT_RATIO_25
#define SOUNDCNT_OUTPUT_RATIO_25 (0)
#endif
#ifndef SOUNDCNT_OUTPUT_RATIO_50
#define SOUNDCNT_OUTPUT_RATIO_50 (1)
#endif
#ifndef SOUNDCNT_OUTPUT_RATIO_100
#define SOUNDCNT_OUTPUT_RATIO_100 (2)
#endif
#ifndef SOUNDCNT_OUTPUT_RATIO_MASK
#define SOUNDCNT_OUTPUT_RATIO_MASK ((0x3 << 0))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_A_OUTPUT_RATIO
#define SOUNDCNT_DIRECT_SOUND_A_OUTPUT_RATIO ((1 << 2))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_B_OUTPUT_RATIO
#define SOUNDCNT_DIRECT_SOUND_B_OUTPUT_RATIO ((1 << 3))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_A_RIGHT_ENABLE
#define SOUNDCNT_DIRECT_SOUND_A_RIGHT_ENABLE ((1 << 8))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_A_LEFT_ENABLE
#define SOUNDCNT_DIRECT_SOUND_A_LEFT_ENABLE ((1 << 9))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_A_SAMPLING_TIMER
#define SOUNDCNT_DIRECT_SOUND_A_SAMPLING_TIMER ((1 << 10))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_A_FIFO_RESET
#define SOUNDCNT_DIRECT_SOUND_A_FIFO_RESET ((1 << 11))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_B_RIGHT_ENABLE
#define SOUNDCNT_DIRECT_SOUND_B_RIGHT_ENABLE ((1 << 12))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_B_LEFT_ENABLE
#define SOUNDCNT_DIRECT_SOUND_B_LEFT_ENABLE ((1 << 13))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_B_SAMPLING_TIMER
#define SOUNDCNT_DIRECT_SOUND_B_SAMPLING_TIMER ((1 << 14))
#endif
#ifndef SOUNDCNT_DIRECT_SOUND_B_FIFO_RESET
#define SOUNDCNT_DIRECT_SOUND_B_FIFO_RESET ((1 << 15))
#endif
#ifndef REG_SOUNDCNT_H
#define REG_SOUNDCNT_H (IORAMBase + 0x82)
#endif
#ifndef SOUNDCNT_DMG_SOUND1_PLAYING
#define SOUNDCNT_DMG_SOUND1_PLAYING ((1 << 0))
#endif
#ifndef SOUNDCNT_DMG_SOUND2_PLAYING
#define SOUNDCNT_DMG_SOUND2_PLAYING ((1 << 1))
#endif
#ifndef SOUNDCNT_DMG_SOUND3_PLAYING
#define SOUNDCNT_DMG_SOUND3_PLAYING ((1 << 2))
#endif
#ifndef SOUNDCNT_DMG_SOUND4_PLAYING
#define SOUNDCNT_DMG_SOUND4_PLAYING ((1 << 3))
#endif
#ifndef SOUNDCNT_SOUND_CIRCUIT_ENABLE
#define SOUNDCNT_SOUND_CIRCUIT_ENABLE ((1 << 7))
#endif
#ifndef AMP_RESOLUTION_9BIT_32KHZ
#define AMP_RESOLUTION_9BIT_32KHZ (0)
#endif
#ifndef AMP_RESOLUTION_8BIT_65KHZ
#define AMP_RESOLUTION_8BIT_65KHZ (1)
#endif
#ifndef AMP_RESOLUTION_7BIT_131KHZ
#define AMP_RESOLUTION_7BIT_131KHZ (2)
#endif
#ifndef AMP_RESOLUTION_6BIT_262KHZ
#define AMP_RESOLUTION_6BIT_262KHZ (3)
#endif
#ifndef SOUNDBIAS_PWN_BIAS_MASK
#define SOUNDBIAS_PWN_BIAS_MASK ((0x1FF << 1))
#endif
#ifndef SOUNDBIAS_AMP_RESOLUTION_MASK
#define SOUNDBIAS_AMP_RESOLUTION_MASK ((0x3 << 14))
#endif
#ifndef REG_SOUNDBIAS
#define REG_SOUNDBIAS (IORAMBase + 0x88)
#endif
#ifndef REG_SGWR0
#define REG_SGWR0 (IORAMBase + 0x90)
#endif
#ifndef REG_SGWR0_L
#define REG_SGWR0_L (IORAMBase + 0x90)
#endif
#ifndef REG_SGWR0_H
#define REG_SGWR0_H (IORAMBase + 0x92)
#endif
#ifndef REG_SGWR1
#define REG_SGWR1 (IORAMBase + 0x94)
#endif
#ifndef REG_SGWR1_L
#define REG_SGWR1_L (IORAMBase + 0x94)
#endif
#ifndef REG_SGWR1_H
#define REG_SGWR1_H (IORAMBase + 0x96)
#endif
#ifndef REG_SGWR2
#define REG_SGWR2 (IORAMBase + 0x98)
#endif
#ifndef REG_SGWR2_L
#define REG_SGWR2_L (IORAMBase + 0x98)
#endif
#ifndef REG_SGWR2_H
#define REG_SGWR2_H (IORAMBase + 0x9A)
#endif
#ifndef REG_SGWR3
#define REG_SGWR3 (IORAMBase + 0x9C)
#endif
#ifndef REG_SGWR3_L
#define REG_SGWR3_L (IORAMBase + 0x9C)
#endif
#ifndef REG_SGWR3_H
#define REG_SGWR3_H (IORAMBase + 0x9E)
#endif
#ifndef REG_SGFIFOA
#define REG_SGFIFOA (IORAMBase + 0xA0)
#endif
#ifndef REG_SGFIFOA_L
#define REG_SGFIFOA_L (IORAMBase + 0xA0)
#endif
#ifndef REG_SGFIFOA_H
#define REG_SGFIFOA_H (IORAMBase + 0xA2)
#endif
#ifndef REG_SGFIFOB
#define REG_SGFIFOB (IORAMBase + 0xA4)
#endif
#ifndef REG_SGFIFOB_L
#define REG_SGFIFOB_L (IORAMBase + 0xA4)
#endif
#ifndef REG_SGFIFOB_H
#define REG_SGFIFOB_H (IORAMBase + 0xA6)
#endif
#ifndef TIMER_FREQUENCY_1_PULSE
#define TIMER_FREQUENCY_1_PULSE (0)
#endif
#ifndef TIMER_FREQUENCY_64_PULSES
#define TIMER_FREQUENCY_64_PULSES (1)
#endif
#ifndef TIMER_FREQUENCY_256_PULSES
#define TIMER_FREQUENCY_256_PULSES (2)
#endif
#ifndef TIMER_FREQUENCY_1024_PULSES
#define TIMER_FREQUENCY_1024_PULSES (3)
#endif
#ifndef TIMER_FREQUENCY_MASK
#define TIMER_FREQUENCY_MASK ((0x3 << 0))
#endif
#ifndef TIMER_CASCADE
#define TIMER_CASCADE ((1 << 2))
#endif
#ifndef TIMER_IRQ
#define TIMER_IRQ ((1 << 6))
#endif
#ifndef TIMER_ENABLE
#define TIMER_ENABLE ((1 << 7))
#endif
#ifndef REG_TM0D
#define REG_TM0D (IORAMBase + 0x100)
#endif
#ifndef REG_TM0CNT
#define REG_TM0CNT (IORAMBase + 0x102)
#endif
#ifndef REG_TM1D
#define REG_TM1D (IORAMBase + 0x104)
#endif
#ifndef REG_TM1CNT
#define REG_TM1CNT (IORAMBase + 0x106)
#endif
#ifndef REG_TM2D
#define REG_TM2D (IORAMBase + 0x108)
#endif
#ifndef REG_TM2CNT
#define REG_TM2CNT (IORAMBase + 0x10A)
#endif
#ifndef REG_TM3D
#define REG_TM3D (IORAMBase + 0x10C)
#endif
#ifndef REG_TM3CNT
#define REG_TM3CNT (IORAMBase + 0x10E)
#endif
#ifndef REG_RCNT
#define REG_RCNT (IORAMBase + 0x134)
#endif
#ifndef REG_JOYCNT
#define REG_JOYCNT (IORAMBase + 0x140)
#endif
#ifndef REG_JOYRE
#define REG_JOYRE (IORAMBase + 0x150)
#endif
#ifndef REG_JOYRE_L
#define REG_JOYRE_L (IORAMBase + 0x150)
#endif
#ifndef REG_JOYRE_H
#define REG_JOYRE_H (IORAMBase + 0x152)
#endif
#ifndef REG_JOYTR
#define REG_JOYTR (IORAMBase + 0x154)
#endif
#ifndef REG_JOYTR_L
#define REG_JOYTR_L (IORAMBase + 0x154)
#endif
#ifndef REG_JOYTR_H
#define REG_JOYTR_H (IORAMBase + 0x156)
#endif
#ifndef REG_JSTAT
#define REG_JSTAT (IORAMBase + 0x158)
#endif
#ifndef REG_JSTAT_L
#define REG_JSTAT_L (IORAMBase + 0x158)
#endif
#ifndef REG_JSTAT_H
#define REG_JSTAT_H (IORAMBase + 0x15A)
#endif
#ifndef LYRICS_SET_CURR_LINE
#define LYRICS_SET_CURR_LINE (0x00)
#endif
#ifndef LYRICS_CURR_LINE_PRINT_CENTER
#define LYRICS_CURR_LINE_PRINT_CENTER (0x01)
#endif
#ifndef LYRICS_CURR_LINE_PRINT_LEFT
#define LYRICS_CURR_LINE_PRINT_LEFT (0x02)
#endif
#ifndef LYRICS_CURR_LINE_PRINT_RIGHT
#define LYRICS_CURR_LINE_PRINT_RIGHT (0x03)
#endif
#ifndef LYRICS_SET_Y_OFFSET
#define LYRICS_SET_Y_OFFSET (0x04)
#endif
#ifndef LYRICS_CURR_LINE_START_HIGHLIGHT
#define LYRICS_CURR_LINE_START_HIGHLIGHT (0x05)
#endif
#ifndef LIGHTEN_SCREEN
#define LIGHTEN_SCREEN (0x06)
#endif
#ifndef DARKEN_SCREEN
#define DARKEN_SCREEN (0x07)
#endif
#ifndef SET_SCREEN_TO_BLACK
#define SET_SCREEN_TO_BLACK (0x08)
#endif
#ifndef SET_SCREEN_TO_LIGHT
#define SET_SCREEN_TO_LIGHT (0x09)
#endif
#ifndef SET_SCREEN_TO_DARK
#define SET_SCREEN_TO_DARK (0x0A)
#endif
#ifndef ANIMATE_NPC
#define ANIMATE_NPC (0x0B)
#endif
#ifndef ANIMATE_PLAYER
#define ANIMATE_PLAYER (0x0C)
#endif
#ifndef ANIMATE_ALL
#define ANIMATE_ALL (0x0D)
#endif
#ifndef SET_NPC_ANIM_TIME
#define SET_NPC_ANIM_TIME (0x0E)
#endif
#ifndef START_INPUT_CHECK
#define START_INPUT_CHECK (0x0F)
#endif
#ifndef STOP_INPUT_CHECK
#define STOP_INPUT_CHECK (0x10)
#endif
#ifndef CUE_FORWARD_CLAP
#define CUE_FORWARD_CLAP (0x00)
#endif
#ifndef CUE_SIDE_CLAP
#define CUE_SIDE_CLAP (0x01)
#endif
#ifndef ANIM_BEAT
#define ANIM_BEAT (0)
#endif
#ifndef ANIM_CLAP_S
#define ANIM_CLAP_S (1)
#endif
#ifndef ANIM_CLAP_F
#define ANIM_CLAP_F (2)
#endif
#ifndef ANIM_BOW
#define ANIM_BOW (3)
#endif
#ifndef ANIM_GLARE
#define ANIM_GLARE (4)
#endif
#ifndef ANIM_HAPPY_1
#define ANIM_HAPPY_1 (5)
#endif
#ifndef ANIM_HAPPY_2
#define ANIM_HAPPY_2 (6)
#endif
#ifndef ANIM_SPIN
#define ANIM_SPIN (7)
#endif
#ifndef DEPLOY_BALL
#define DEPLOY_BALL (0x00)
#endif
#ifndef BOUNCE_BALL
#define BOUNCE_BALL (0x01)
#endif
#ifndef ENABLE_BALL_GOAL_SFX
#define ENABLE_BALL_GOAL_SFX (0x02)
#endif
#ifndef PLAY_DISTANT_BOUNCE_SFX
#define PLAY_DISTANT_BOUNCE_SFX (0x03)
#endif
#ifndef SET_BALL_PALETTE
#define SET_BALL_PALETTE (0x04)
#endif
#ifndef SET_BOUNCE_HEIGHT
#define SET_BOUNCE_HEIGHT (0x05)
#endif
#ifndef CUE_DEFAULT
#define CUE_DEFAULT (0x00)
#endif
#ifndef STUB_EVENT
#define STUB_EVENT (0x00)
#endif
#ifndef EVENT_01
#define EVENT_01 (0x01)
#endif
#ifndef EVENT_02
#define EVENT_02 (0x02)
#endif
#ifndef EVENT_03
#define EVENT_03 (0x03)
#endif
#ifndef EVENT_04
#define EVENT_04 (0x04)
#endif
#ifndef EVENT_05
#define EVENT_05 (0x05)
#endif
#ifndef EVENT_06
#define EVENT_06 (0x06)
#endif
#ifndef EVENT_07
#define EVENT_07 (0x07)
#endif
#ifndef EVENT_08
#define EVENT_08 (0x08)
#endif
#ifndef EVENT_09
#define EVENT_09 (0x09)
#endif
#ifndef CUE_BUNNY_00
#define CUE_BUNNY_00 (0x00)
#endif
#ifndef CUE_BUNNY_01
#define CUE_BUNNY_01 (0x01)
#endif
#ifndef CUE_BUNNY_02
#define CUE_BUNNY_02 (0x02)
#endif
#ifndef CUE_BUNNY_03
#define CUE_BUNNY_03 (0x03)
#endif
#ifndef CUE_BUNNY_04
#define CUE_BUNNY_04 (0x04)
#endif
#ifndef CUE_BUNNY_05
#define CUE_BUNNY_05 (0x05)
#endif
#ifndef CUE_BUNNY_06
#define CUE_BUNNY_06 (0x06)
#endif
#ifndef CUE_BUNNY_07
#define CUE_BUNNY_07 (0x07)
#endif
#ifndef CUE_BUNNY_08
#define CUE_BUNNY_08 (0x08)
#endif
#ifndef CUE_BUNNY_09
#define CUE_BUNNY_09 (0x09)
#endif
#ifndef CUE_BUNNY_0A
#define CUE_BUNNY_0A (0x0A)
#endif
#ifndef LIONS_CROUCH
#define LIONS_CROUCH (0x00)
#endif
#ifndef LIONS_CROUCH_SMIRK
#define LIONS_CROUCH_SMIRK (0x01)
#endif
#ifndef LION_CLAP
#define LION_CLAP (0x02)
#endif
#ifndef GRAYSCALE_ON_NEXT_HIT
#define GRAYSCALE_ON_NEXT_HIT (0x03)
#endif
#ifndef SET_LION_CLAP_VOLUME
#define SET_LION_CLAP_VOLUME (0x04)
#endif
#ifndef TEXTBOX_SHOWN
#define TEXTBOX_SHOWN (0x05)
#endif
#ifndef CUE_FULL_BEAT
#define CUE_FULL_BEAT (0x00)
#endif
#ifndef CUE_HALF_BEAT
#define CUE_HALF_BEAT (0x01)
#endif
#ifndef CUE_FULL_BEAT_W_SMILE
#define CUE_FULL_BEAT_W_SMILE (0x04)
#endif
#ifndef CUE_HALF_BEAT_W_SMILE
#define CUE_HALF_BEAT_W_SMILE (0x05)
#endif
#ifndef EVENT_00
#define EVENT_00 (0x00)
#endif
#ifndef EVENT_0A
#define EVENT_0A (0x0A)
#endif
#ifndef EVENT_0B
#define EVENT_0B (0x0B)
#endif
#ifndef EVENT_0C
#define EVENT_0C (0x0C)
#endif
#ifndef EVENT_0D
#define EVENT_0D (0x0D)
#endif
#ifndef EVENT_0E
#define EVENT_0E (0x0E)
#endif
#ifndef EVENT_0F
#define EVENT_0F (0x0F)
#endif
#ifndef CUE_KICK
#define CUE_KICK (0x00)
#endif
#ifndef CUE_SNARE
#define CUE_SNARE (0x01)
#endif
#ifndef CUE_CYMBAL
#define CUE_CYMBAL (0x02)
#endif
#ifndef CUE_TOM
#define CUE_TOM (0x03)
#endif
#ifndef CUE_HIHAT
#define CUE_HIHAT (0x04)
#endif
#ifndef CUE_ROLL
#define CUE_ROLL (0x04)
#endif
#ifndef CUE_AUTO
#define CUE_AUTO (0x05)
#endif
#ifndef SET_GUITARIST_NEXT_STATE
#define SET_GUITARIST_NEXT_STATE (0x00)
#endif
#ifndef CLEAR_INPUT_DEF
#define CLEAR_INPUT_DEF (0x02)
#endif
#ifndef DEFINE_COOL_INPUTS
#define DEFINE_COOL_INPUTS (0x03)
#endif
#ifndef DEFINE_LAME_INPUTS
#define DEFINE_LAME_INPUTS (0x04)
#endif
#ifndef SET_ENABLE_BOREDOM
#define SET_ENABLE_BOREDOM (0x08)
#endif
#ifndef SET_DISABLE_EXCITEMENT
#define SET_DISABLE_EXCITEMENT (0x09)
#endif
#ifndef CUE_LIVE_00
#define CUE_LIVE_00 (0x00)
#endif
#ifndef CUE_LIVE_01
#define CUE_LIVE_01 (0x01)
#endif
#ifndef CUE_LIVE_02
#define CUE_LIVE_02 (0x02)
#endif
#ifndef CUE_LIVE_03
#define CUE_LIVE_03 (0x03)
#endif
#ifndef CUE_LIVE_04
#define CUE_LIVE_04 (0x04)
#endif
#ifndef CUE_LIVE_05
#define CUE_LIVE_05 (0x05)
#endif
#ifndef ENGINE_VER_DRUM_GIRLS_LIVE
#define ENGINE_VER_DRUM_GIRLS_LIVE (0)
#endif
#ifndef ENGINE_VER_DRUM_BOYS_LIVE
#define ENGINE_VER_DRUM_BOYS_LIVE (1)
#endif
#ifndef ENGINE_VER_DRUM_BAND_LIVE
#define ENGINE_VER_DRUM_BAND_LIVE (2)
#endif
#ifndef FREEZE_SCENE
#define FREEZE_SCENE (0x00)
#endif
#ifndef GET_NEXT_SCRIPT
#define GET_NEXT_SCRIPT (0x00)
#endif
#ifndef START_BG_MONITOR
#define START_BG_MONITOR (0x03)
#endif
#ifndef STOP_BG_MONITOR
#define STOP_BG_MONITOR (0x04)
#endif
#ifndef SHOW_SAVE_OPTIONS
#define SHOW_SAVE_OPTIONS (0x05)
#endif
#ifndef SET_DIALOGUE_TEXT
#define SET_DIALOGUE_TEXT (0x0D)
#endif
#ifndef SHOW_DIALOGUE
#define SHOW_DIALOGUE (0x10)
#endif
#ifndef EVENT_11
#define EVENT_11 (0x11)
#endif
#ifndef SET_TEACHER_EMOTE
#define SET_TEACHER_EMOTE (0x12)
#endif
#ifndef EVENT_13
#define EVENT_13 (0x13)
#endif
#ifndef GET_LESSON_SCORE
#define GET_LESSON_SCORE (0x14)
#endif
#ifndef EVENT_15
#define EVENT_15 (0x15)
#endif
#ifndef EVENT_16
#define EVENT_16 (0x16)
#endif
#ifndef EVENT_17
#define EVENT_17 (0x17)
#endif
#ifndef EVENT_18
#define EVENT_18 (0x18)
#endif
#ifndef EVENT_19
#define EVENT_19 (0x19)
#endif
#ifndef CUE_KICK_L
#define CUE_KICK_L (0x00)
#endif
#ifndef CUE_KICK_R
#define CUE_KICK_R (0x01)
#endif
#ifndef CUE_SNARE_L
#define CUE_SNARE_L (0x02)
#endif
#ifndef CUE_SNARE_R
#define CUE_SNARE_R (0x03)
#endif
#ifndef CUE_SPLASH
#define CUE_SPLASH (0x06)
#endif
#ifndef CUE_CRASH
#define CUE_CRASH (0x07)
#endif
#ifndef TEACHER_EXP_DRUM
#define TEACHER_EXP_DRUM (0)
#endif
#ifndef TEACHER_EXP_LISTEN
#define TEACHER_EXP_LISTEN (1)
#endif
#ifndef TEACHER_EXP_POSITIVE
#define TEACHER_EXP_POSITIVE (2)
#endif
#ifndef TEACHER_EXP_SHRUG
#define TEACHER_EXP_SHRUG (3)
#endif
#ifndef TEACHER_EXP_GIVE_RANK
#define TEACHER_EXP_GIVE_RANK (4)
#endif
#ifndef SET_PATTERN_MODE
#define SET_PATTERN_MODE (0x00)
#endif
#ifndef PLAY_SOUND
#define PLAY_SOUND (0x01)
#endif
#ifndef SET_DEFAULT_PATTERN
#define SET_DEFAULT_PATTERN (0x02)
#endif
#ifndef CUE_SPIRIT_SPARKLER
#define CUE_SPIRIT_SPARKLER (0x00)
#endif
#ifndef CUE_NORMAL_FIREWORK
#define CUE_NORMAL_FIREWORK (0x01)
#endif
#ifndef CUE_TAIKO_BOMBER
#define CUE_TAIKO_BOMBER (0x04)
#endif
#ifndef PATTERN_MODE_0
#define PATTERN_MODE_0 (0)
#endif
#ifndef PATTERN_MODE_1
#define PATTERN_MODE_1 (1)
#endif
#ifndef PATTERN_MODE_TAIKO_BOMBER
#define PATTERN_MODE_TAIKO_BOMBER (2)
#endif
#ifndef PATTERN_MODE_USE_TABLE
#define PATTERN_MODE_USE_TABLE (3)
#endif
#ifndef PATTERN_MODE_USE_DEFAULT
#define PATTERN_MODE_USE_DEFAULT (99)
#endif
#ifndef SFX_COME_ON
#define SFX_COME_ON (0)
#endif
#ifndef SFX_ONE
#define SFX_ONE (1)
#endif
#ifndef SFX_TWO
#define SFX_TWO (2)
#endif
#ifndef SFX_THREE
#define SFX_THREE (3)
#endif
#ifndef SFX_NUEI
#define SFX_NUEI (4)
#endif
#ifndef PATTERN_3L
#define PATTERN_3L (0)
#endif
#ifndef PATTERN_3C
#define PATTERN_3C (1)
#endif
#ifndef PATTERN_3R
#define PATTERN_3R (2)
#endif
#ifndef PATTERN_2LL
#define PATTERN_2LL (3)
#endif
#ifndef PATTERN_2CL
#define PATTERN_2CL (4)
#endif
#ifndef PATTERN_2CR
#define PATTERN_2CR (5)
#endif
#ifndef PATTERN_2RR
#define PATTERN_2RR (6)
#endif
#ifndef PATTERN_3L_BARELY
#define PATTERN_3L_BARELY (7)
#endif
#ifndef PATTERN_3C_BARELY
#define PATTERN_3C_BARELY (8)
#endif
#ifndef PATTERN_3R_BARELY
#define PATTERN_3R_BARELY (9)
#endif
#ifndef PATTERN_2LL_BARELY
#define PATTERN_2LL_BARELY (10)
#endif
#ifndef PATTERN_2CL_BARELY
#define PATTERN_2CL_BARELY (11)
#endif
#ifndef PATTERN_2CR_BARELY
#define PATTERN_2CR_BARELY (12)
#endif
#ifndef PATTERN_2RR_BARELY
#define PATTERN_2RR_BARELY (13)
#endif
#ifndef PATTERN_SP_STAR
#define PATTERN_SP_STAR (14)
#endif
#ifndef PATTERN_SP_CIRCLE
#define PATTERN_SP_CIRCLE (15)
#endif
#ifndef PATTERN_SP_SPIRAL
#define PATTERN_SP_SPIRAL (16)
#endif
#ifndef PATTERN_SP_SMILE
#define PATTERN_SP_SMILE (17)
#endif
#ifndef PATTERN_SP_TSUNKU
#define PATTERN_SP_TSUNKU (18)
#endif
#ifndef PATTERN_TAIKO_BOMBER
#define PATTERN_TAIKO_BOMBER (19)
#endif
#ifndef RESET_BG_FACE
#define RESET_BG_FACE (0x00)
#endif
#ifndef START_SERIOUS_NEXT_HIT
#define START_SERIOUS_NEXT_HIT (0x01)
#endif
#ifndef STOP_SERIOUS_NEXT_HIT
#define STOP_SERIOUS_NEXT_HIT (0x02)
#endif
#ifndef PRINT_TEXTBOX
#define PRINT_TEXTBOX (0x03)
#endif
#ifndef WAIT_AT_TEXTBOX
#define WAIT_AT_TEXTBOX (0x04)
#endif
#ifndef ENABLE_FLOW_METER
#define ENABLE_FLOW_METER (0x05)
#endif
#ifndef START_TUTORIAL_LOOP
#define START_TUTORIAL_LOOP (0x06)
#endif
#ifndef EXIT_LOOP_IF_ALL_HIT
#define EXIT_LOOP_IF_ALL_HIT (0x07)
#endif
#ifndef USE_THE_FACE
#define USE_THE_FACE (0x08)
#endif
#ifndef CUE_POT
#define CUE_POT (0x00)
#endif
#ifndef CUE_SOCCER_BALL
#define CUE_SOCCER_BALL (0x01)
#endif
#ifndef CUE_POT_STRICT
#define CUE_POT_STRICT (0x02)
#endif
#ifndef CUE_ROCK
#define CUE_ROCK (0x04)
#endif
#ifndef CUE_BOMB
#define CUE_BOMB (0x05)
#endif
#ifndef CUE_LIGHT_BULB
#define CUE_LIGHT_BULB (0x08)
#endif
#ifndef CUE_MANNEQUIN_00
#define CUE_MANNEQUIN_00 (0x00)
#endif
#ifndef CUE_MANNEQUIN_01
#define CUE_MANNEQUIN_01 (0x01)
#endif
#ifndef CUE_MANNEQUIN_02
#define CUE_MANNEQUIN_02 (0x02)
#endif
#ifndef CUE_MANNEQUIN_03
#define CUE_MANNEQUIN_03 (0x03)
#endif
#ifndef CUE_MANNEQUIN_04
#define CUE_MANNEQUIN_04 (0x04)
#endif
#ifndef CUE_MANNEQUIN_05
#define CUE_MANNEQUIN_05 (0x05)
#endif
#ifndef PLAY_VOICE_SFX
#define PLAY_VOICE_SFX (0x05)
#endif
#ifndef CUE_STEP
#define CUE_STEP (0x00)
#endif
#ifndef CUE_TURN_LEFT
#define CUE_TURN_LEFT (0x01)
#endif
#ifndef CUE_TURN_RIGHT
#define CUE_TURN_RIGHT (0x02)
#endif
#ifndef CUE_HALT
#define CUE_HALT (0x03)
#endif
#ifndef SHOUT_START
#define SHOUT_START (0)
#endif
#ifndef SHOUT_STOP
#define SHOUT_STOP (1)
#endif
#ifndef SHOUT_TURN
#define SHOUT_TURN (2)
#endif
#ifndef VOICE_ATTENTION
#define VOICE_ATTENTION (3)
#endif
#ifndef VOICE_MARCH
#define VOICE_MARCH (4)
#endif
#ifndef VOICE_HALT
#define VOICE_HALT (5)
#endif
#ifndef VOICE_RIGHT_FACE
#define VOICE_RIGHT_FACE (6)
#endif
#ifndef VOICE_RIGHT_FACE_F
#define VOICE_RIGHT_FACE_F (7)
#endif
#ifndef VOICE_TURN_RIGHT
#define VOICE_TURN_RIGHT (8)
#endif
#ifndef VOICE_LEFT_FACE
#define VOICE_LEFT_FACE (9)
#endif
#ifndef VOICE_LEFT_FACE_F
#define VOICE_LEFT_FACE_F (10)
#endif
#ifndef VOICE_TURN_LEFT
#define VOICE_TURN_LEFT (11)
#endif
#ifndef CUE_WALK
#define CUE_WALK (0x00)
#endif
#ifndef CUE_TROT
#define CUE_TROT (0x01)
#endif
#ifndef CUE_CANTER
#define CUE_CANTER (0x02)
#endif
#ifndef CUE_GALLOP
#define CUE_GALLOP (0x03)
#endif
#ifndef CUE_H_BEAT_REALTIME
#define CUE_H_BEAT_REALTIME (0x00)
#endif
#ifndef CUE_1_BEAT_TO_TEMPO
#define CUE_1_BEAT_TO_TEMPO (0x01)
#endif
#ifndef CUE_H_BEAT_TO_TEMPO
#define CUE_H_BEAT_TO_TEMPO (0x08)
#endif
#ifndef PLAY_DRUMTECH_NOTE
#define PLAY_DRUMTECH_NOTE (0x00)
#endif
#ifndef INIT_BALLOONS
#define INIT_BALLOONS (0x01)
#endif
#ifndef POP_BALLOON
#define POP_BALLOON (0x02)
#endif
#ifndef SET_END_SCRIPT
#define SET_END_SCRIPT (0x03)
#endif
#ifndef SET_PLATFORM
#define SET_PLATFORM (0x04)
#endif
#ifndef SET_MARKING_CRITERIA
#define SET_MARKING_CRITERIA (0x05)
#endif
#ifndef SET_CUE_EARLINESS
#define SET_CUE_EARLINESS (0x06)
#endif
#ifndef ENABLE_SWING
#define ENABLE_SWING (0x07)
#endif
#ifndef SET_DRUM_VOLUME
#define SET_DRUM_VOLUME (0x08)
#endif
#ifndef EXPAND_STARS
#define EXPAND_STARS (0x09)
#endif
#ifndef CUE_STAR_WAND
#define CUE_STAR_WAND (0x04)
#endif
#ifndef PLATFORM_BRIDGE
#define PLATFORM_BRIDGE (0)
#endif
#ifndef PLATFORM_GAP
#define PLATFORM_GAP (1)
#endif
#ifndef PLATFORM_RANDOM
#define PLATFORM_RANDOM (2)
#endif
#ifndef PLATFORM_FISH
#define PLATFORM_FISH (3)
#endif
#ifndef EVENT_10
#define EVENT_10 (0x10)
#endif
#ifndef SPAWN_BLOCK
#define SPAWN_BLOCK (0x00)
#endif
#ifndef DESPAWN_BLOCKS
#define DESPAWN_BLOCKS (0x01)
#endif
#ifndef RETRACT_PISTONS
#define RETRACT_PISTONS (0x02)
#endif
#ifndef SPAWN_ROD
#define SPAWN_ROD (0x03)
#endif
#ifndef PLAY_APPLAUSE_SFX
#define PLAY_APPLAUSE_SFX (0x04)
#endif
#ifndef CUE_H_UPSIDE
#define CUE_H_UPSIDE (0x00)
#endif
#ifndef CUE_H_DOWNSIDE
#define CUE_H_DOWNSIDE (0x01)
#endif
#ifndef CUE_4_UPSIDE
#define CUE_4_UPSIDE (0x04)
#endif
#ifndef CUE_4_DOWNSIDE
#define CUE_4_DOWNSIDE (0x05)
#endif
#ifndef CUE_8_UPSIDE
#define CUE_8_UPSIDE (0x08)
#endif
#ifndef CUE_8_DOWNSIDE
#define CUE_8_DOWNSIDE (0x09)
#endif
#ifndef UPSIDE
#define UPSIDE (0)
#endif
#ifndef DOWNSIDE
#define DOWNSIDE (1)
#endif
#ifndef PLATFORM
#define PLATFORM (0)
#endif
#ifndef PISTON_UPSIDE
#define PISTON_UPSIDE (1)
#endif
#ifndef PISTON_DOWNSIDE
#define PISTON_DOWNSIDE (2)
#endif
#ifndef SET_KANA
#define SET_KANA (0x00)
#endif
#ifndef SET_KANA_ANIM_CEL
#define SET_KANA_ANIM_CEL (0x01)
#endif
#ifndef OFFSET_PAPER
#define OFFSET_PAPER (0x02)
#endif
#ifndef REMOVE_PAPER
#define REMOVE_PAPER (0x03)
#endif
#ifndef SET_INPUT_STROKE
#define SET_INPUT_STROKE (0x04)
#endif
#ifndef FINISH_KOKORO2
#define FINISH_KOKORO2 (0x05)
#endif
#ifndef SET_BRUSH
#define SET_BRUSH (0x06)
#endif
#ifndef CHARGE_BRUSH
#define CHARGE_BRUSH (0x07)
#endif
#ifndef CHARGE_EFFECT
#define CHARGE_EFFECT (0x08)
#endif
#ifndef RAISE_BRUSH
#define RAISE_BRUSH (0x09)
#endif
#ifndef START_INK_ORBIT
#define START_INK_ORBIT (0x0A)
#endif
#ifndef SET_PEOPLE_STATE
#define SET_PEOPLE_STATE (0x0B)
#endif
#ifndef SET_PEOPLE_POS
#define SET_PEOPLE_POS (0x0C)
#endif
#ifndef KANA_ONORE
#define KANA_ONORE (0)
#endif
#ifndef KANA_CHIKARA
#define KANA_CHIKARA (1)
#endif
#ifndef KANA_SUN
#define KANA_SUN (2)
#endif
#ifndef KANA_KOKORO
#define KANA_KOKORO (3)
#endif
#ifndef KANA_RE
#define KANA_RE (4)
#endif
#ifndef KANA_COMMA
#define KANA_COMMA (5)
#endif
#ifndef KANA_FACE
#define KANA_FACE (6)
#endif
#ifndef KANA_END_KANJI
#define KANA_END_KANJI (7)
#endif
#ifndef KANA_INPUT_ONORE1
#define KANA_INPUT_ONORE1 (0)
#endif
#ifndef KANA_INPUT_CHIKARA1
#define KANA_INPUT_CHIKARA1 (1)
#endif
#ifndef KANA_INPUT_CHIKARA2
#define KANA_INPUT_CHIKARA2 (2)
#endif
#ifndef KANA_INPUT_SUN1
#define KANA_INPUT_SUN1 (3)
#endif
#ifndef KANA_INPUT_SUN2
#define KANA_INPUT_SUN2 (4)
#endif
#ifndef KANA_INPUT_KOKORO1
#define KANA_INPUT_KOKORO1 (5)
#endif
#ifndef KANA_INPUT_KOKORO2
#define KANA_INPUT_KOKORO2 (6)
#endif
#ifndef KANA_INPUT_KOKORO3
#define KANA_INPUT_KOKORO3 (7)
#endif
#ifndef KANA_INPUT_RE1
#define KANA_INPUT_RE1 (8)
#endif
#ifndef KANA_INPUT_COMMA1
#define KANA_INPUT_COMMA1 (9)
#endif
#ifndef KANA_INPUT_FACE1
#define KANA_INPUT_FACE1 (10)
#endif
#ifndef BRUSH_RAISED
#define BRUSH_RAISED (0)
#endif
#ifndef BRUSH_DOWN
#define BRUSH_DOWN (1)
#endif
#ifndef CHARGE_STROKE
#define CHARGE_STROKE (0)
#endif
#ifndef CHARGE_COMMA
#define CHARGE_COMMA (1)
#endif
#ifndef LITTLE_PEOPLE_NULL
#define LITTLE_PEOPLE_NULL (0)
#endif
#ifndef LITTLE_PEOPLE_DANCE
#define LITTLE_PEOPLE_DANCE (1)
#endif
#ifndef LITTLE_PEOPLE_STUMBLE
#define LITTLE_PEOPLE_STUMBLE (2)
#endif
#ifndef LITTLE_PEOPLE_BOW
#define LITTLE_PEOPLE_BOW (3)
#endif
#ifndef LITTLE_PEOPLE_END_BOW
#define LITTLE_PEOPLE_END_BOW (4)
#endif
#ifndef HOST_BUTTON_R
#define HOST_BUTTON_R (0)
#endif
#ifndef HOST_BUTTON_L
#define HOST_BUTTON_L (1)
#endif
#ifndef ANIMATE_RAPPER
#define ANIMATE_RAPPER (0x00)
#endif
#ifndef ENABLE_TUTORIAL
#define ENABLE_TUTORIAL (0x01)
#endif
#ifndef CUE_UN
#define CUE_UN (0x00)
#endif
#ifndef CUE_UUN
#define CUE_UUN (0x01)
#endif
#ifndef ANIM_DESUKA
#define ANIM_DESUKA (0)
#endif
#ifndef ANIM_KAMONE
#define ANIM_KAMONE (1)
#endif
#ifndef ANIM_SAIKO
#define ANIM_SAIKO (2)
#endif
#ifndef ANIM_RECOIL
#define ANIM_RECOIL (3)
#endif
#ifndef ANIM_HONTO
#define ANIM_HONTO (4)
#endif
#ifndef EVENT_12
#define EVENT_12 (0x12)
#endif
#ifndef CUE_STOP4
#define CUE_STOP4 (0x00)
#endif
#ifndef CUE_STOP2
#define CUE_STOP2 (0x01)
#endif
#ifndef CUE_DASH
#define CUE_DASH (0x03)
#endif
#ifndef CUE_TEST_00
#define CUE_TEST_00 (0x00)
#endif
#ifndef CUE_TEST_01
#define CUE_TEST_01 (0x01)
#endif
#ifndef SPAWN_TWEEZERS
#define SPAWN_TWEEZERS (0x00)
#endif
#ifndef START_HAIR_CYCLE
#define START_HAIR_CYCLE (0x01)
#endif
#ifndef SCROLL_VEG
#define SCROLL_VEG (0x02)
#endif
#ifndef SET_NEXT_VEG
#define SET_NEXT_VEG (0x03)
#endif
#ifndef PLAY_REGISTER_SFX
#define PLAY_REGISTER_SFX (0x04)
#endif
#ifndef HIDE_TUTORIAL_TEXT
#define HIDE_TUTORIAL_TEXT (0x05)
#endif
#ifndef REMOVED_EVENT
#define REMOVED_EVENT (0x06)
#endif
#ifndef SHOW_MASK
#define SHOW_MASK (0x07)
#endif
#ifndef HIDE_MASK
#define HIDE_MASK (0x08)
#endif
#ifndef CUE_SHORT
#define CUE_SHORT (0x00)
#endif
#ifndef CUE_LONG
#define CUE_LONG (0x01)
#endif
#ifndef CUE_FAST
#define CUE_FAST (0x02)
#endif
#ifndef CUE_8_SHORT
#define CUE_8_SHORT (0x04)
#endif
#ifndef CUE_8_LONG
#define CUE_8_LONG (0x05)
#endif
#ifndef CUE_8_FAST
#define CUE_8_FAST (0x06)
#endif
#ifndef VEG_ONION
#define VEG_ONION (0)
#endif
#ifndef VEG_TURNIP
#define VEG_TURNIP (1)
#endif
#ifndef VEG_POTATO
#define VEG_POTATO (2)
#endif
#ifndef CUE_FIRST
#define CUE_FIRST (0x00)
#endif
#ifndef CUE_SECOND
#define CUE_SECOND (0x01)
#endif
#ifndef CUE_GRAY
#define CUE_GRAY (0x00)
#endif
#ifndef CUE_BLACK
#define CUE_BLACK (0x01)
#endif
#ifndef CUE_WHITE_FAST
#define CUE_WHITE_FAST (0x02)
#endif
#ifndef CUE_WHITE_FAST_S
#define CUE_WHITE_FAST_S (0x03)
#endif
#ifndef CUE_WHITE
#define CUE_WHITE (0x04)
#endif
#ifndef SPAWN_VIRUS
#define SPAWN_VIRUS (0x01)
#endif
#ifndef SET_HITS_NEEDED
#define SET_HITS_NEEDED (0x02)
#endif
#ifndef SET_VIRUS_PALETTE
#define SET_VIRUS_PALETTE (0x03)
#endif
#ifndef CUE_SICK_BEATS_00
#define CUE_SICK_BEATS_00 (0x00)
#endif
#ifndef CUE_SICK_BEATS_04
#define CUE_SICK_BEATS_04 (0x04)
#endif
#ifndef CUE_SICK_BEATS_08
#define CUE_SICK_BEATS_08 (0x08)
#endif
#ifndef SHOW_GHOST
#define SHOW_GHOST (0x00)
#endif
#ifndef SET_GHOST_HEIGHT
#define SET_GHOST_HEIGHT (0x01)
#endif
#ifndef SPAWN_BOW
#define SPAWN_BOW (0x02)
#endif
#ifndef DRAW_BOW
#define DRAW_BOW (0x03)
#endif
#ifndef ENABLE_WIND_SFX
#define ENABLE_WIND_SFX (0x04)
#endif
#ifndef PRINT_TEXT
#define PRINT_TEXT (0x05)
#endif
#ifndef SET_RAIN_SPEED
#define SET_RAIN_SPEED (0x06)
#endif
#ifndef FREEZE_SLOW_RAIN
#define FREEZE_SLOW_RAIN (0x07)
#endif
#ifndef SHOW_TUTORIAL_GHOST
#define SHOW_TUTORIAL_GHOST (0x08)
#endif
#ifndef SET_TUTORIAL_GHOST_FRAME
#define SET_TUTORIAL_GHOST_FRAME (0x09)
#endif
#ifndef CUE_STRICT
#define CUE_STRICT (0x00)
#endif
#ifndef CUE_NORMAL
#define CUE_NORMAL (0x01)
#endif
#ifndef CUE_LENIENT
#define CUE_LENIENT (0x02)
#endif
#ifndef CUE_TUTORIAL
#define CUE_TUTORIAL (0x03)
#endif
#ifndef NORMAL_SPEED
#define NORMAL_SPEED (0)
#endif
#ifndef SLOW_MOTION
#define SLOW_MOTION (1)
#endif
#ifndef CUE_SIT_DOWN
#define CUE_SIT_DOWN (0x01)
#endif
#ifndef CUE_PUNCH
#define CUE_PUNCH (0x02)
#endif
#ifndef CUE_PUNCH_S
#define CUE_PUNCH_S (0x03)
#endif
#ifndef ANIM_HIT_RIGHT
#define ANIM_HIT_RIGHT (0)
#endif
#ifndef ANIM_HIT_PUNCH
#define ANIM_HIT_PUNCH (1)
#endif
#ifndef ANIM_HIT_DOWN
#define ANIM_HIT_DOWN (2)
#endif
#ifndef ANIM_CUE_RIGHT
#define ANIM_CUE_RIGHT (3)
#endif
#ifndef ANIM_CUE_PUNCH1
#define ANIM_CUE_PUNCH1 (4)
#endif
#ifndef ANIM_CUE_PUNCH2
#define ANIM_CUE_PUNCH2 (5)
#endif
#ifndef ANIM_CUE_DOWN
#define ANIM_CUE_DOWN (6)
#endif
#ifndef ANIM_SPEAK
#define ANIM_SPEAK (7)
#endif
#ifndef ANIM_BLINK
#define ANIM_BLINK (8)
#endif
#ifndef PREPARE_PITCHER
#define PREPARE_PITCHER (0x00)
#endif
#ifndef EXIT_LOOP_IF_NO_MISS
#define EXIT_LOOP_IF_NO_MISS (0x01)
#endif
#ifndef ZOOM_CAMERA
#define ZOOM_CAMERA (0x02)
#endif
#ifndef SET_BATTER_SPRITE
#define SET_BATTER_SPRITE (0x03)
#endif
#ifndef SET_UFO_ANIM
#define SET_UFO_ANIM (0x04)
#endif
#ifndef SET_BALL_SPRITE
#define SET_BALL_SPRITE (0x05)
#endif
#ifndef CUE_LOW_F
#define CUE_LOW_F (0x00)
#endif
#ifndef CUE_LOW
#define CUE_LOW (0x01)
#endif
#ifndef CUE_HIGH
#define CUE_HIGH (0x02)
#endif
#ifndef CUE_HIGH_F
#define CUE_HIGH_F (0x03)
#endif
#ifndef BATTER_GREEN
#define BATTER_GREEN (0)
#endif
#ifndef BATTER_RED
#define BATTER_RED (1)
#endif
#ifndef BATTER_PINK
#define BATTER_PINK (2)
#endif
#ifndef UFO_OPEN
#define UFO_OPEN (0)
#endif
#ifndef UFO_SWAY
#define UFO_SWAY (1)
#endif
#ifndef BASEBALL
#define BASEBALL (0)
#endif
#ifndef RICE_BALL
#define RICE_BALL (1)
#endif
#ifndef STAR_BALL
#define STAR_BALL (2)
#endif
#ifndef SET_TEXT_ALIGNMENT
#define SET_TEXT_ALIGNMENT (0x01)
#endif
#ifndef TOGGLE_TEXT_SCROLL
#define TOGGLE_TEXT_SCROLL (0x02)
#endif
#ifndef SET_BACKGROUND
#define SET_BACKGROUND (0x03)
#endif
#ifndef ALIGNMENT_LEFT
#define ALIGNMENT_LEFT (0x00)
#endif
#ifndef ALIGNMENT_RIGHT
#define ALIGNMENT_RIGHT (0x01)
#endif
#ifndef ALIGNMENT_CENTER
#define ALIGNMENT_CENTER (0x02)
#endif
#ifndef CUE_TOSS_R
#define CUE_TOSS_R (0x00)
#endif
#ifndef CUE_TOSS_B
#define CUE_TOSS_B (0x01)
#endif
#ifndef CUE_TOSS_Y
#define CUE_TOSS_Y (0x02)
#endif
#ifndef CUE_CATCH_R
#define CUE_CATCH_R (0x04)
#endif
#ifndef CUE_CATCH_B
#define CUE_CATCH_B (0x05)
#endif
#ifndef CUE_CATCH_Y
#define CUE_CATCH_Y (0x06)
#endif
#ifndef CUE_POP_R
#define CUE_POP_R (0x08)
#endif
#ifndef CUE_POP_B
#define CUE_POP_B (0x09)
#endif
#ifndef CUE_POP_Y
#define CUE_POP_Y (0x0A)
#endif
#ifndef AKA_CHAN
#define AKA_CHAN (0)
#endif
#ifndef AO_KUN
#define AO_KUN (1)
#endif
#ifndef KII_YAN
#define KII_YAN (2)
#endif
#ifndef ACTION_TOSS
#define ACTION_TOSS (0)
#endif
#ifndef ACTION_SUPER_TOSS
#define ACTION_SUPER_TOSS (1)
#endif
#ifndef ACTION_CATCH
#define ACTION_CATCH (2)
#endif
#ifndef ACTION_POP
#define ACTION_POP (3)
#endif
#ifndef CUE_TRAM
#define CUE_TRAM (0x00)
#endif
#ifndef CUE_PAULINE
#define CUE_PAULINE (0x01)
#endif
#ifndef SET_CYCLE_TIME
#define SET_CYCLE_TIME (0x00)
#endif
#ifndef CUE_WIZARD_00
#define CUE_WIZARD_00 (0x00)
#endif
#ifndef CUE_WIZARD_01
#define CUE_WIZARD_01 (0x01)
#endif
#ifndef CUE_WIZARD_02
#define CUE_WIZARD_02 (0x02)
#endif
