#!/usr/bin/env python3
"""Emit a binary file as an assembly listing, like devkitPro's bin2s.

Having our own removes devkitPro from the build's requirements, which matters
for CI runners and for anyone who only wants the PC port.  Output matches what
the toolchain expects on each platform:

  --apple-llvm   Mach-O: .const_data, symbols prefixed with an underscore
  (default)      ELF/PE: .section .rodata.<name>, bare symbol names
"""
import argparse, os, sys


def emit(path, apple, out):
    name = os.path.basename(path).replace('.', '_').replace('-', '_')
    data = open(path, 'rb').read()
    sym = ('_' + name) if apple else name

    out.write("/* Generated by tools/bin2s.py - do not edit */\n")
    if apple:
        out.write("\t.const_data\n")
    else:
        out.write('\t.section .rodata.%s, "a"\n' % name)
    out.write("\t.balign 4\n")
    out.write("\t.global %s\n%s:\n" % (sym, sym))

    for i in range(0, len(data), 16):
        out.write("\t.byte " + ",".join("%3d" % b for b in data[i:i + 16]) + "\n")

    # bin2s also publishes <sym>_end and a 4-byte <sym>_size; some sources
    # reference them, so emit them in the same shape.
    out.write("\n\t.global %s_end\n%s_end:\n" % (sym, sym))
    out.write("\n\t.global %s_size\n\t.balign 4\n%s_size: .int %d\n"
              % (sym, sym, len(data)))
    if not apple:
        out.write('\n#if defined(__linux__) && defined(__ELF__)\n'
                  '.section .note.GNU-stack,"",%progbits\n#endif\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apple-llvm", action="store_true", dest="apple")
    ap.add_argument("-a", "--alignment", default=None)   # accepted, unused
    ap.add_argument("files", nargs="+")
    a = ap.parse_args()
    for f in a.files:
        emit(f, a.apple, sys.stdout)


if __name__ == "__main__":
    main()
