#!/usr/bin/env python3
# Generate platform/pal_overread.c: the ROM bytes each palette load really
# copies.
#
# Most graphics tables copy a fixed 0x140 or 0x200 bytes of palette, while the
# palette itself defines fewer banks. On the GBA the rest comes from whatever
# follows in ROM (often cel data), and some games show it: Wizard's Waltz's
# title text uses OBJ bank 4 colour 15 of its prologue palette, which only
# defines 3 banks, so the ROM's title is brown (0x81d4 from the following
# bytes) where the PC read a host pointer and drew it black. On PC such a
# copy also reads past the end of a C array.
#
# For every palette that some GraphicsTable entry copies past its end, this
# emits the ROM bytes for the largest copy, after checking that the defined
# part matches the ROM; src/graphics_table.c substitutes them on PC.
#
#   tools/gen_pal_overread.py [BASEROM]
import glob, os, re, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROM_PATH = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    '~/Downloads/2462 - Rhythm Tengoku (J)(WRG).gba')
OUT = os.path.join(ROOT, 'platform', 'pal_overread.c')

rom = open(ROM_PATH, 'rb').read()
files = sorted(f for f in glob.glob(ROOT + '/**/*.c', recursive=True)
               if not os.path.relpath(f, ROOT).startswith(('build', 'dist'))
               and f != OUT)


def rgb555(v):
    return ((v >> 16 & 0xFF) >> 3) | ((v >> 8 & 0xFF) >> 3) << 5 | ((v & 0xFF) >> 3) << 10


# name -> (rom address, [u16 values], file)
pals = {}
for f in files:
    s = open(f, encoding='latin-1').read()
    for m in re.finditer(r'(//[^\n]*\n)?[ \t]*(?:const\s+)?Palette\s+(\w+)\[\]\s*=\s*\{', s):
        a = re.search(r'\[(?:D_)?(?:0x)?(0?8[0-9a-fA-F]{6,7})\]', m.group(1) or '')
        start = m.end(); depth = 1; i = start
        while depth:
            depth += {'{': 1, '}': -1}.get(s[i], 0)
            i += 1
        body = re.sub(r'/\*.*?\*/', '', s[start:i - 1], flags=re.S)
        vals = [rgb555(int(x, 16)) for x in re.findall(r'TO_RGB555\((0x[0-9A-Fa-f]+)\)', body)]
        if not vals:
            vals = [int(x, 16) for x in re.findall(r'0x[0-9A-Fa-f]+', body)]
        pals[m.group(2)] = (int(a.group(1), 16) if a else None, vals, f)

# name -> largest copy size
sizes = {}
for f in files:
    s = open(f, encoding='latin-1').read()
    for m in re.finditer(r'/\*\s*Src\.\s*\*/\s*&?(\w+),\s*/\*\s*Dest\.\s*\*/\s*[^,]*PALETTE[^,]*,'
                         r'\s*/\*\s*Size\s*\*/\s*(0x[0-9A-Fa-f]+|\d+)', s):
        name, size = m.group(1), int(m.group(2), 0)
        if name in pals and size > 2 * len(pals[name][1]):
            sizes[name] = max(size, sizes.get(name, 0))

out = []
for name in sorted(sizes):
    addr, vals, f = pals[name]
    if addr is None:
        sys.exit('%s (%s): no ROM address comment' % (name, f))
    off = addr - 0x08000000
    words = list(struct.unpack('<%dH' % (sizes[name] // 2), rom[off:off + sizes[name]]))
    if words[:len(vals)] != vals:
        sys.exit('%s: defined colours do not match the ROM at %08x' % (name, addr))
    out.append((name, addr, len(vals) * 2, words))

with open(OUT, 'w') as g:
    g.write('// Generated by tools/gen_pal_overread.py from the base ROM -- do not edit.\n')
    g.write('// The bytes each palette load copies on the GBA, including the part past\n')
    g.write('// the palette\'s own banks; see the script for why.\n')
    g.write('#include "global.h"\n#include "graphics.h"\n#include "pal_overread.h"\n\n')
    for name, addr, defined, words in out:
        g.write('extern Palette %s[];\n' % name)
    g.write('\n')
    for name, addr, defined, words in out:
        g.write('// [%08x] %s: 0x%x bytes defined, 0x%x copied\n' % (addr, name, defined, len(words) * 2))
        g.write('static const u16 rom_%s[] = {\n' % name)
        for i in range(0, len(words), 16):
            g.write('    ' + ', '.join('0x%04x' % w for w in words[i:i + 16]) + ',\n')
        g.write('};\n\n')
    g.write('const struct PcPalOverread gPcPalOverreads[] = {\n')
    for name, addr, defined, words in out:
        g.write('    { %s, rom_%s, 0x%x },\n' % (name, name, len(words) * 2))
    g.write('};\n\n')
    g.write('const u32 gPcPalOverreadCount = ARRAY_COUNT(gPcPalOverreads);\n')
print('%d palettes, %d bytes of ROM data' % (len(out), sum(len(w) * 2 for _, _, _, w in out)))
