#!/usr/bin/env python3
"""Emit a name -> &scene table for every Scene the build defines.

Lets RTPC_SCENE jump straight to a scene instead of navigating menus, which is
what makes it practical to check all of the game engines rather than only the
one that happens to be reachable.
"""
import re, os, sys

roots = ("games", "data", "platform", "src")
pat_def  = re.compile(r'^\s*(?:const\s+)?struct\s+Scene\s+(scene_\w+)\s*=', re.M)
pat_stub = re.compile(r'^\s*PC_GAME_STUB\((scene_\w+)\);', re.M)

names = set()
for r in roots:
    for dp, _, fs in os.walk(r):
        for fn in fs:
            if not fn.endswith(".c"):
                continue
            try:
                t = open(os.path.join(dp, fn), errors="replace").read()
            except OSError:
                continue
            names |= set(pat_def.findall(t)) | set(pat_stub.findall(t))

names = sorted(names)
out = ["/* Generated by tools/gen_scene_table.py - do not edit. */",
       "#ifdef PLATFORM_PC", '#include "global.h"', '#include "src/main.h"', ""]
for n in names:
    out.append(f"extern struct Scene {n};")
out += ["", "const struct { const char *name; struct Scene *scene; } gPcSceneTable[] = {"]
for n in names:
    out.append(f'    {{ "{n[6:]}", &{n} }},')
out += ["};", f"const int gPcSceneTableCount = {len(names)};", "", "#endif"]
open("platform/scene_table.c", "w").write("\n".join(out) + "\n")
print(f"{len(names)} scenes")
