#!/usr/bin/env python3
"""
Generate a C file containing all audio sample PCM data and SampleData structs.
Used by the PC build instead of the ARM assembly approach.

Usage: python3 tools/gen_sample_c.py audio/sample_table.json platform/sample_data.c
"""
import sys, json, os, wave, subprocess, struct

pitches = ("C","C#","D","D#","E","F","F#","G","G#","A","A#","B")

def get_pitch_num(pitch):
    length = 2 if "#" in pitch else 1
    octave = int(pitch[length:])
    return pitches.index(pitch[:length]) + octave * 12

def wav_to_pcm_bytes(wav_path):
    """Convert WAV to signed 8-bit mono PCM bytes using ffmpeg."""
    result = subprocess.run(
        ['ffmpeg', '-y', '-loglevel', 'quiet', '-i', wav_path, '-f', 's8', '-ac', '1', 'pipe:1'],
        capture_output=True
    )
    return result.stdout

def main():
    input_json = sys.argv[1]
    output_c   = sys.argv[2]
    json_dir   = os.path.dirname(os.path.abspath(input_json))
    
    with open(input_json) as f:
        data = json.load(f)
    
    samples = data["samples"]
    
    lines = []
    lines.append('/* Auto-generated by tools/gen_sample_c.py — do not edit */')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append('typedef uint8_t  u8;')
    lines.append('typedef uint32_t u32;')
    lines.append('typedef int8_t   s8;')
    lines.append('')
    # Match the struct definition from include/sound.h
    lines.append('struct SampleData {')
    lines.append('    u32 length;')
    lines.append('    u32 sampleRate;')
    lines.append('    u32 pitch;')
    lines.append('    u32 loopStart;')
    lines.append('    u32 loopEnd;')
    lines.append('    const u32 *waveform;')
    lines.append('};')
    lines.append('')
    
    for entry in samples:
        name = entry["sample"].split(".")[0]
        wav_path = os.path.join(json_dir, "samples", entry["sample"])
        
        # Get WAV metadata
        try:
            with wave.open(wav_path) as wf:
                nframes    = wf.getnframes()
                frame_rate = wf.getframerate()
        except Exception as e:
            print(f"Warning: could not read {wav_path}: {e}", file=sys.stderr)
            nframes = 1
            frame_rate = 13379
        
        pitch_num  = get_pitch_num(entry["pitch"])
        loop_start = entry.get("loop", [0, 0])[0]
        loop_end   = entry.get("loop", [0, 0])[1]
        
        # Convert WAV to PCM bytes
        try:
            pcm_bytes = wav_to_pcm_bytes(wav_path)
        except Exception as e:
            print(f"Warning: could not convert {wav_path}: {e}", file=sys.stderr)
            pcm_bytes = bytes([0, 0, 0, 0])
        
        # Pad to 4-byte boundary
        while len(pcm_bytes) % 4 != 0:
            pcm_bytes += b'\x00'
        
        length_bytes = len(pcm_bytes)
        
        # Write PCM data as u32 array (matching waveform pointer type)
        u32_vals = struct.unpack(f'<{length_bytes // 4}I', pcm_bytes)
        lines.append(f'static const u32 {name}_pcm[] = {{')
        row = []
        for v in u32_vals:
            row.append(f'0x{v:08X}')
            if len(row) == 8:
                lines.append('    ' + ', '.join(row) + ',')
                row = []
        if row:
            lines.append('    ' + ', '.join(row))
        lines.append('};')
        lines.append('')
        
        # Write SampleData struct — field names from include/sound.h
        lines.append(f'struct SampleData {name}_data = {{')
        lines.append(f'    {nframes - 1},   /* length */')
        lines.append(f'    {frame_rate},    /* sampleRate */')
        lines.append(f'    {pitch_num},     /* pitch */')
        lines.append(f'    {loop_start},    /* loopStart */')
        lines.append(f'    {loop_end},      /* loopEnd */')
        lines.append(f'    {name}_pcm       /* waveform */')
        lines.append('};')
        lines.append('')
    
    with open(output_c, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    
    print(f"Generated {len(samples)} samples → {output_c}")

if __name__ == "__main__":
    main()
