/* Generated by tools/bs2c.py from games/tap_trial/tap_trial.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/prologues/tap_trial.h"
#include "include/sequence_data.h"
#include "src/code_080068f8.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805c248[];   /* undeclared in any header */
extern char D_0805c264[];   /* undeclared in any header */
extern char D_0805c274[];   /* undeclared in any header */
extern char D_0805c290[];   /* undeclared in any header */
extern char D_0805c2a8[];   /* undeclared in any header */
extern char D_0805c2bc[];   /* undeclared in any header */
extern char D_0805c2d4[];   /* undeclared in any header */
extern char D_0805c2e8[];   /* undeclared in any header */
extern char D_0805c2ec[];   /* undeclared in any header */
extern char D_0805c300[];   /* undeclared in any header */
extern char D_0805c318[];   /* undeclared in any header */
extern char D_0805c334[];   /* undeclared in any header */
extern char D_0805c348[];   /* undeclared in any header */
extern char D_0805c35c[];   /* undeclared in any header */
extern char D_0805c374[];   /* undeclared in any header */
extern char D_0805c384[];   /* undeclared in any header */
extern char D_0805c39c[];   /* undeclared in any header */
extern char D_0805c3b4[];   /* undeclared in any header */
extern char D_0805c3cc[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char tap_trial_engine[];   /* undeclared in any header */
extern char tap_trial_prologue_engine[];   /* undeclared in any header */
extern char tap_trial_sub_08a85c78[];   /* undeclared in any header */
extern char tap_trial_sub_08a85cf0[];   /* undeclared in any header */
extern char tap_trial_sub_08a85de0[];   /* undeclared in any header */
extern char tap_trial_sub_08a85e10[];   /* undeclared in any header */
extern char tap_trial_sub_08a85e88[];   /* undeclared in any header */
extern char tap_trial_sub_08a85f00[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x0F[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x29[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x4C[];   /* undeclared in any header */
extern char x50[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern char x66[];   /* undeclared in any header */
extern char x80[];   /* undeclared in any header */
extern char x99[];   /* undeclared in any header */
extern char xB3[];   /* undeclared in any header */
extern const struct Beatscript script_tap_trial_entry[];
extern const struct SubScene sub_scene_tap_trial;
extern struct Scene scene_tap_trial;
extern const struct Beatscript script_tap_trial_skipped_practice_entry[];
extern const struct SubScene sub_scene_tap_trial_skipped_practice;
extern struct Scene scene_tap_trial_skipped_practice;
extern const struct Beatscript script_tap_trial_prologue[];
extern const struct MarkingCriteria tap_trial_marking_criteria_0;
extern const struct MarkingCriteria tap_trial_marking_criteria_1;
extern const struct MarkingCriteria tap_trial_marking_criteria_2;
extern const struct MarkingCriteria tap_trial_marking_criteria_3;
extern const struct MarkingCriteria *tap_trial_marking_criteria[];
extern const struct Beatscript tap_trial_sub_08a0cefc[];
extern const struct Beatscript tap_trial_sub_08a0cf68[];
extern const struct Beatscript tap_trial_sub_08a0cfd4[];
extern const struct Beatscript tap_trial_sub_08a0d058[];
extern const struct Beatscript script_tap_trial_main[];
extern const struct Beatscript script_tap_trial_practice[];
extern const struct Beatscript script_tap_trial_skipped_practice[];

const struct Beatscript script_tap_trial_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(script_tap_trial_prologue), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_tap_trial_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_tap_trial = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_tap_trial_entry,
};

struct Scene scene_tap_trial = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_tap_trial),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_tap_trial_skipped_practice_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_tap_trial_skipped_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_tap_trial_skipped_practice = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_tap_trial_skipped_practice_entry,
};

struct Scene scene_tap_trial_skipped_practice = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_tap_trial_skipped_practice),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_tap_trial_prologue[] = {
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(8) },
    { 0x04, 0, (const void *)(gameplay_set_current_engine), (uintptr_t)(tap_trial_prologue_engine) },
    { 0x03, 0, (const void *)(stop_all_soundplayers), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x29, 0, NULL, (uintptr_t)(&s_jingle_tap_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(func_08047794), (uintptr_t)(1) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(func_08006d80), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(16) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct MarkingCriteria tap_trial_marking_criteria_0 = {
    /* positive */ D_0805c264,
    /* negative */ D_0805c248,
    /* flags    */ (CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0xB3,
    /* minHitsBeforeFail   */ 0x80,
    /* maxMissesBeforeFail */ 0x4C,
};

const struct MarkingCriteria tap_trial_marking_criteria_1 = {
    /* positive */ D_0805c290,
    /* negative */ D_0805c274,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0xB3,
    /* minHitsBeforeFail   */ 0x66,
    /* maxMissesBeforeFail */ 0x99,
};

const struct MarkingCriteria tap_trial_marking_criteria_2 = {
    /* positive */ D_0805c2bc,
    /* negative */ D_0805c2a8,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0xB3,
    /* minHitsBeforeFail   */ 0x4C,
    /* maxMissesBeforeFail */ 0x80,
};

const struct MarkingCriteria tap_trial_marking_criteria_3 = {
    /* positive */ D_0805c2e8,
    /* negative */ D_0805c2d4,
    /* flags    */ (CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x00,
    /* minHitsBeforeFail   */ 0x00,
    /* maxMissesBeforeFail */ 0x00,
};

const struct MarkingCriteria *tap_trial_marking_criteria[] = {
    (const struct MarkingCriteria *)(&tap_trial_marking_criteria_0),
    (const struct MarkingCriteria *)(&tap_trial_marking_criteria_1),
    (const struct MarkingCriteria *)(&tap_trial_marking_criteria_2),
    (const struct MarkingCriteria *)(&tap_trial_marking_criteria_3),
    (const struct MarkingCriteria *)(NULL),
};

const struct Beatscript tap_trial_sub_08a0cefc[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_sub_08a0cf68[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_sub_08a0cfd4[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_sub_08a0d058[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_tap_trial_main[] = {
    { 0x03, 0, (const void *)(results_set_header), (uintptr_t)(D_0805c2ec) },
    { 0x03, 0, (const void *)(results_import_marking_criteria), (uintptr_t)(tap_trial_marking_criteria) },
    { 0x03, 0, (const void *)(gameplay_set_mercy_count), (uintptr_t)(3) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(127) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_tapdance_bgm_seqData) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(50) },
    { 0x50, 0, (const void *)(256), (uintptr_t)(192) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c300) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_start_perfect_campaign), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805c318) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(NULL) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(139) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e10), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(NULL) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85f00), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85cf0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85c78), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85de0), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a85e88), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805c334) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_check_for_perfect), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_tap_trial_practice[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c348) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(&scene_tap_trial_skipped_practice) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(110) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(200) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_renshu_bgm1_seqData) },
    { 0x00, 0, NULL, (uintptr_t)(6) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c35c) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c374) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a0cefc), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c384) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a0cf68), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c39c) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a0cfd4), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c3b4) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_sub_08a0d058), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(NULL) },
    { 0x50, 0, NULL, (uintptr_t)(90) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c3cc) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_tap_trial_main), (uintptr_t)(0) },
};

const struct Beatscript script_tap_trial_skipped_practice[] = {
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(TRUE) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_tap_trial_main), (uintptr_t)(0) },
};
