/* Generated by tools/bs2c.py from games/tap_trial/tap_trial_unused.bs — do not edit. */
#include "global.h"
#include "src/main.h"
#include "src/audio.h"
#include "src/scenes/gameplay.h"
#include "src/scenes/results.h"
#include "src/code_0800b778.h"
#include "include/beatscript_consts.h"
#include "include/sequence_data.h"
#include "src/scenes/riq_main_scene.h"

extern char D_0805c0d0[];   /* undeclared in any header */
extern char D_0805c0ec[];   /* undeclared in any header */
extern char D_0805c104[];   /* undeclared in any header */
extern char D_0805c11c[];   /* undeclared in any header */
extern char D_0805c130[];   /* undeclared in any header */
extern char D_0805c144[];   /* undeclared in any header */
extern char D_0805c15c[];   /* undeclared in any header */
extern char D_0805c170[];   /* undeclared in any header */
extern char D_0805c174[];   /* undeclared in any header */
extern char D_0805c18c[];   /* undeclared in any header */
extern char D_0805c1a8[];   /* undeclared in any header */
extern char D_0805c1bc[];   /* undeclared in any header */
extern char D_0805c1d0[];   /* undeclared in any header */
extern char D_0805c1e8[];   /* undeclared in any header */
extern char D_0805c1f8[];   /* undeclared in any header */
extern char D_0805c210[];   /* undeclared in any header */
extern char D_0805c228[];   /* undeclared in any header */
extern char D_0805c240[];   /* undeclared in any header */
extern char h[];   /* undeclared in any header */
extern char tap_trial_engine[];   /* undeclared in any header */
extern char w[];   /* undeclared in any header */
extern char x00[];   /* undeclared in any header */
extern char x01[];   /* undeclared in any header */
extern char x03[];   /* undeclared in any header */
extern char x04[];   /* undeclared in any header */
extern char x0D[];   /* undeclared in any header */
extern char x0E[];   /* undeclared in any header */
extern char x0F[];   /* undeclared in any header */
extern char x10[];   /* undeclared in any header */
extern char x11[];   /* undeclared in any header */
extern char x28[];   /* undeclared in any header */
extern char x36[];   /* undeclared in any header */
extern char x4A[];   /* undeclared in any header */
extern char x4C[];   /* undeclared in any header */
extern char x50[];   /* undeclared in any header */
extern char x5BC[];   /* undeclared in any header */
extern char x66[];   /* undeclared in any header */
extern char x80[];   /* undeclared in any header */
extern char x99[];   /* undeclared in any header */
extern char xB3[];   /* undeclared in any header */
extern const struct Beatscript script_tap_trial_unused_entry[];
extern const struct SubScene sub_scene_tap_trial_unused;
extern struct Scene scene_tap_trial_unused;
extern const struct Beatscript script_tap_trial_unused_skipped_practice_entry[];
extern const struct SubScene sub_scene_tap_trial_unused_skipped_practice;
extern struct Scene scene_tap_trial_unused_skipped_practice;
extern const struct MarkingCriteria tap_trial_unused_marking_criteria_0;
extern const struct MarkingCriteria tap_trial_unused_marking_criteria_1;
extern const struct MarkingCriteria tap_trial_unused_marking_criteria_2;
extern const struct MarkingCriteria tap_trial_unused_marking_criteria_3;
extern const struct MarkingCriteria *tap_trial_unused_marking_criteria[];
extern const struct Beatscript tap_trial_unused_sub_08a0b6a8[];
extern const struct Beatscript tap_trial_unused_sub_08a0b720[];
extern const struct Beatscript tap_trial_unused_sub_08a0b810[];
extern const struct Beatscript tap_trial_unused_sub_08a0b840[];
extern const struct Beatscript tap_trial_unused_sub_08a0b8b8[];
extern const struct Beatscript tap_trial_unused_sub_08a0b930[];
extern const struct Beatscript tap_trial_unused_sub_08a0ba14[];
extern const struct Beatscript tap_trial_unused_sub_08a0ba80[];
extern const struct Beatscript tap_trial_unused_sub_08a0baec[];
extern const struct Beatscript tap_trial_unused_sub_08a0bb70[];
extern const struct Beatscript script_tap_trial_unused_main[];
extern const struct Beatscript script_tap_trial_unused_practice[];
extern const struct Beatscript script_tap_trial_unused_skipped_practice[];

const struct Beatscript script_tap_trial_unused_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x04, 6, (const void *)(gameplay_set_current_engine), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_tap_trial_unused_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_tap_trial_unused = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_tap_trial_unused_entry,
};

struct Scene scene_tap_trial_unused = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_tap_trial_unused),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct Beatscript script_tap_trial_unused_skipped_practice_entry[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(124) },
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x04, 6, (const void *)(gameplay_set_current_engine), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x0D, 0, (const void *)(script_tap_trial_unused_skipped_practice), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(pause_menu_enabled), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(gameplay_inputs_enabled), (uintptr_t)(FALSE) },
    { 0x36, TRUE, NULL, (uintptr_t)(48) },
    { 0x4A, 1, (const void *)(12), (uintptr_t)(BLACK) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x01, 0, NULL, (uintptr_t)(0) },
};

const struct SubScene sub_scene_tap_trial_unused_skipped_practice = {
    /* start  */ (void (*)())gameplay_start_scene, 0,
    /* paused */ (void (*)())gameplay_update_paused_scene, 0,
    /* update */ (void (*)())gameplay_update_scene, 0,
    /* stop   */ (void (*)())gameplay_stop_scene, 0,
    /* script */ script_tap_trial_unused_skipped_practice_entry,
};

struct Scene scene_tap_trial_unused_skipped_practice = {
    /* init   */ (void (*)())func_0801d86c, (void *)(&sub_scene_tap_trial_unused_skipped_practice),
    /* loop   */ (u32 (*)())func_0801d8d8, (void *)(NULL),
    /* end    */ (void (*)())NULL, (void *)(NULL),
    /* memory */ 0x5BC,
};

const struct MarkingCriteria tap_trial_unused_marking_criteria_0 = {
    /* positive */ D_0805c0ec,
    /* negative */ D_0805c0d0,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0xB3,
    /* minHitsBeforeFail   */ 0x80,
    /* maxMissesBeforeFail */ 0x4C,
};

const struct MarkingCriteria tap_trial_unused_marking_criteria_1 = {
    /* positive */ D_0805c11c,
    /* negative */ D_0805c104,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0xB3,
    /* minHitsBeforeFail   */ 0x66,
    /* maxMissesBeforeFail */ 0x99,
};

const struct MarkingCriteria tap_trial_unused_marking_criteria_2 = {
    /* positive */ D_0805c144,
    /* negative */ D_0805c130,
    /* flags    */ (CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0xB3,
    /* minHitsBeforeFail   */ 0x4C,
    /* maxMissesBeforeFail */ 0x80,
};

const struct MarkingCriteria tap_trial_unused_marking_criteria_3 = {
    /* positive */ D_0805c170,
    /* negative */ D_0805c15c,
    /* flags    */ (CHECK_AVERAGE_MISSES) & 0xFF, ((CHECK_AVERAGE_MISSES) >> 8) & 0xFF,
    /* minHitsForSuccess   */ 0x00,
    /* minHitsBeforeFail   */ 0x00,
    /* maxMissesBeforeFail */ 0x00,
};

const struct MarkingCriteria *tap_trial_unused_marking_criteria[] = {
    (const struct MarkingCriteria *)(&tap_trial_unused_marking_criteria_0),
    (const struct MarkingCriteria *)(&tap_trial_unused_marking_criteria_1),
    (const struct MarkingCriteria *)(&tap_trial_unused_marking_criteria_2),
    (const struct MarkingCriteria *)(&tap_trial_unused_marking_criteria_3),
    (const struct MarkingCriteria *)(NULL),
};

const struct Beatscript tap_trial_unused_sub_08a0b6a8[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(4) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0b720[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(15) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(15) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(5) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(5) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0b810[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(9) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0b840[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(10) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(14) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0b8b8[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(11) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(12) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0b930[] = {
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(8) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(6) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(7) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(12) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(6) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0ba14[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0ba80[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0baec[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript tap_trial_unused_sub_08a0bb70[] = {
    { 0x10, 0, NULL, (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(189) },
    { 0x04, EVENT_01, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x11, 0, NULL, (uintptr_t)(0) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_tap_trial_unused_main[] = {
    { 0x03, 0, (const void *)(results_import_marking_criteria), (uintptr_t)(tap_trial_unused_marking_criteria) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(TRUE) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(180) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c174) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_03, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805c18c) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(NULL) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x50, 0, (const void *)(90), (uintptr_t)(96) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(140) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(180) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x50, 0, (const void *)(120), (uintptr_t)(48) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b840), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(2) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(1) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b930), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(2) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_02, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b720), (uintptr_t)(0) },
    { 0x50, 0, (const void *)(180), (uintptr_t)(48) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_spawn_cue), (uintptr_t)(CUE_DEFAULT) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(4) },
    { 0x04, EVENT_00, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x00, 0, NULL, (uintptr_t)(14) },
    { 0x03, 0, (const void *)(scene_stop_music), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(10) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(1) },
    { 0x04, EVENT_06, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x03, 0, (const void *)(gameplay_set_marking_criteria), (uintptr_t)(3) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(0) },
    { 0x04, EVENT_05, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_karate_fan_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(22) },
    { 0x03, 0, (const void *)(scene_stop_music), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_karate_fan_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(22) },
    { 0x03, 0, (const void *)(scene_stop_music), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(2) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b6a8), (uintptr_t)(0) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_karate_fan_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_karate_fan_seqData) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x28, 0, (const void *)(DEFAULT_SOUND_PLAYER), (uintptr_t)(&s_karate_fan_seqData) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b810), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0b8b8), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_engine_event_param), (uintptr_t)(D_0805c1a8) },
    { 0x04, EVENT_04, (const void *)(gameplay_run_engine_event), (uintptr_t)(tap_trial_engine) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0E, 0, NULL, (uintptr_t)(0) },
};

const struct Beatscript script_tap_trial_unused_practice[] = {
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c1bc) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(&scene_tap_trial_unused_skipped_practice) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x03, 0, (const void *)(results_enable_input_tracking), (uintptr_t)(FALSE) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(110) },
    { 0x03, 0, (const void *)(scene_set_music_volume), (uintptr_t)(256) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c1d0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c1e8) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0ba14), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c1f8) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0ba80), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c210) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0baec), (uintptr_t)(0) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c228) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0D, 0, (const void *)(tap_trial_unused_sub_08a0bb70), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(gameplay_set_tutorial), (uintptr_t)(NULL) },
    { 0x50, 0, NULL, (uintptr_t)(90) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(D_0805c240) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x04, 1, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x04, 0, (const void *)(gameplay_run_common_event), (uintptr_t)(0) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_tap_trial_unused_main), (uintptr_t)(0) },
};

const struct Beatscript script_tap_trial_unused_skipped_practice[] = {
    { 0x03, 0, (const void *)(gameplay_set_screen_fade_in_time), (uintptr_t)(0) },
    { 0x03, 0, (const void *)(set_beatscript_tempo), (uintptr_t)(120) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x00, 0, NULL, (uintptr_t)(24) },
    { 0x0F, 0, (const void *)(script_tap_trial_unused_main), (uintptr_t)(0) },
};
